<?php
require_once __DIR__ . '/includes/http.php';
require_once __DIR__ . '/includes/seo.php';

$cbd_page_has_charset = true;
$page_styles = ['/assets/css/web-development.css'];

if (cbd_is_direct_script_request('landing-page-design.php')) {
    cbd_redirect_path('/landing-page-design');
}

$base = cbd_base_path();
$canonical = cbd_canonical_url('/landing-page-design');
$page_robots = 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1';
$pageTitle = 'Landing Page Design Services | Chulbul Design';
$pageDescription = 'Conversion-focused landing page design for Google Ads, Meta Ads, B2B lead generation and product campaigns, with responsive UX and tracking plans.';
$shareImage = cbd_public_url('/assets/images/service-heroes/landing-page-design-hero.webp');

$landingServices = [
    ['icon' => 'bi-bullseye', 'title' => 'Campaign Landing Page Strategy', 'text' => 'Define one audience, offer, traffic source and measurable action before deciding what the page should contain.'],
    ['icon' => 'bi-google', 'title' => 'Google Ads Landing Pages', 'text' => 'Focused pages with strong keyword-to-message continuity, relevant proof and a clear enquiry or purchase path.', 'href' => '/google-ads-ppc', 'link' => 'Explore Google Ads services'],
    ['icon' => 'bi-megaphone', 'title' => 'Meta & Social Ad Landing Pages', 'text' => 'Mobile-first post-click experiences that continue the promise and visual context introduced by the ad.'],
    ['icon' => 'bi-person-plus', 'title' => 'Lead Generation Pages', 'text' => 'Service, consultation and quote-request pages designed to collect useful lead information without unnecessary friction.'],
    ['icon' => 'bi-rocket-takeoff', 'title' => 'Product & Service Launch Pages', 'text' => 'Explain a new offer, address early objections and guide visitors toward a demo, waitlist, booking or purchase.'],
    ['icon' => 'bi-cart3', 'title' => 'Ecommerce Campaign Pages', 'text' => 'Curated category, product, bundle and seasonal pages that support focused shopping journeys from paid traffic.', 'href' => '/ecommerce-website-design', 'link' => 'Explore ecommerce design'],
    ['icon' => 'bi-ui-checks', 'title' => 'Form UX & Lead Capture', 'text' => 'Clear labels, sensible field order, validation and confirmation states planned around lead quality and completion.'],
    ['icon' => 'bi-layout-text-window', 'title' => 'Landing Page Content Hierarchy', 'text' => 'Structure the promise, detail, proof, objections and calls to action around the visitor’s decision process.'],
    ['icon' => 'bi-speedometer2', 'title' => 'Performance-Aware Design', 'text' => 'Responsive layouts, media and interaction choices planned to support fast delivery and Core Web Vitals.', 'href' => '/website-speed-optimization', 'link' => 'Improve website performance'],
    ['icon' => 'bi-bar-chart-line', 'title' => 'Tracking & Test Planning', 'text' => 'Define meaningful conversion events, analytics requirements and responsible hypotheses for future testing.', 'href' => '/conversion-rate-optimization', 'link' => 'Explore conversion optimization'],
];

$campaignTypes = [
    ['icon' => 'bi-google', 'title' => 'Search Campaigns', 'text' => 'Continue high-intent keyword context with a specific offer and relevant next action.'],
    ['icon' => 'bi-meta', 'title' => 'Paid Social Campaigns', 'text' => 'Bridge interruption-based ads with concise mobile storytelling and immediate relevance.'],
    ['icon' => 'bi-linkedin', 'title' => 'B2B Lead Generation', 'text' => 'Support longer decisions with business outcomes, process, credibility and qualified forms.'],
    ['icon' => 'bi-envelope-paper', 'title' => 'Email Campaigns', 'text' => 'Give subscribers a focused continuation for announcements, offers and segmented messages.'],
    ['icon' => 'bi-calendar-event', 'title' => 'Events & Webinars', 'text' => 'Communicate topic, speakers, schedule, audience and registration requirements clearly.'],
    ['icon' => 'bi-phone', 'title' => 'App & Product Launches', 'text' => 'Explain the use case and guide visitors toward demos, downloads, trials or waitlists.'],
    ['icon' => 'bi-geo-alt', 'title' => 'Local Service Leads', 'text' => 'Connect location-aware searches to service scope, proof, availability and quote requests.'],
    ['icon' => 'bi-cart-check', 'title' => 'Ecommerce Promotions', 'text' => 'Focus product collections, bundles and seasonal value without distracting store navigation.'],
    ['icon' => 'bi-download', 'title' => 'Resource Downloads', 'text' => 'Set accurate expectations for guides, reports and tools before requesting contact details.'],
    ['icon' => 'bi-chat-square-text', 'title' => 'Consultation Campaigns', 'text' => 'Qualify interest and prepare prospects for a useful sales or discovery conversation.'],
];

$faqs = [
    ['q' => 'What is a landing page?', 'a' => 'A landing page is a focused page created for a specific audience, offer and action. Visitors often arrive from an advertisement, email, social post or targeted campaign, and the page continues that message without the broader choices of a full website.'],
    ['q' => 'How is a landing page different from a homepage?', 'a' => 'A homepage introduces the wider business and supports several visitor journeys. A landing page serves one campaign context and usually prioritizes one primary conversion, such as an enquiry, registration, demo, call, download or purchase.'],
    ['q' => 'Do I need a separate landing page for every ad campaign?', 'a' => 'Not automatically. Separate pages are useful when audiences, search intent, offers or conversion actions differ meaningfully. Closely related ad groups can share a page when its message remains relevant; unnecessary duplication makes maintenance and measurement harder.'],
    ['q' => 'Can you design landing pages for Google Ads and Meta Ads?', 'a' => 'Yes. Google Search visitors often arrive with explicit intent, while paid social visitors may need more context. We adapt message order, proof, mobile behavior and calls to action to the campaign and audience rather than using one generic template.'],
    ['q' => 'Do you write the landing page copy?', 'a' => 'Content hierarchy and message guidance are part of the design process. Full copywriting, research or subject-matter interviews can be included when agreed in the scope. We always use realistic content during design so the final layout is not based on placeholder text.'],
    ['q' => 'How many form fields should a landing page have?', 'a' => 'The right number depends on the action and how the lead will be used. A simple callback may need very little information, while a project enquiry may need qualifying details. We balance completion effort with lead usefulness instead of applying one universal field count.'],
    ['q' => 'Can you add analytics and conversion tracking?', 'a' => 'Yes. We can define events for forms, calls, bookings, purchases or other meaningful actions and coordinate implementation through the agreed analytics and advertising platforms. Consent, access and platform configuration must also be handled correctly.'],
    ['q' => 'Will a landing page guarantee more conversions?', 'a' => 'No responsible designer can guarantee conversions. Results depend on traffic quality, offer, pricing, competition, copy, trust and follow-up as well as the page. Our role is to reduce avoidable friction, strengthen relevance and create a measurable experience that can be improved.'],
    ['q' => 'How much does landing page design cost?', 'a' => 'Cost depends on strategy, content support, number of variants, responsive complexity, forms, integrations, illustration, development, tracking and testing requirements. We provide a written scope after reviewing the campaign and conversion action.'],
    ['q' => 'Can you improve an existing landing page?', 'a' => 'Yes. We can review the current message, hierarchy, mobile experience, form, speed, tracking and available performance data. Recommendations distinguish clear usability issues from hypotheses that should be validated through measurement or testing.'],
];

$schemaOffers = [];
foreach ($landingServices as $service) {
    $schemaOffers[] = ['@type' => 'Offer', 'itemOffered' => ['@type' => 'Service', 'name' => $service['title']]];
}

$schema = [
    '@context' => 'https://schema.org',
    '@graph' => [
        [
            '@type' => 'Service',
            '@id' => $canonical . '#service',
            'name' => 'Landing Page Design Services',
            'serviceType' => 'Landing Page Design',
            'url' => $canonical,
            'description' => $pageDescription,
            'provider' => [
                '@type' => 'Organization',
                '@id' => CBD_CANONICAL_ORIGIN . '/#organization',
                'name' => 'Chulbul Design',
                'url' => CBD_CANONICAL_ORIGIN . '/',
                'telephone' => '+919990548795',
                'address' => [
                    '@type' => 'PostalAddress',
                    'streetAddress' => 'Sector 15, Flat No. 1277',
                    'addressLocality' => 'Gurugram',
                    'addressRegion' => 'Haryana',
                    'postalCode' => '122001',
                    'addressCountry' => 'IN',
                ],
            ],
            'areaServed' => 'Worldwide',
            'hasOfferCatalog' => ['@type' => 'OfferCatalog', 'name' => 'Landing Page Design Services', 'itemListElement' => $schemaOffers],
        ],
        [
            '@type' => 'BreadcrumbList',
            '@id' => $canonical . '#breadcrumb',
            'itemListElement' => [
                ['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => CBD_CANONICAL_ORIGIN . '/'],
                ['@type' => 'ListItem', 'position' => 2, 'name' => 'Web Design & Development', 'item' => cbd_canonical_url('/web-design-development')],
                ['@type' => 'ListItem', 'position' => 3, 'name' => 'Landing Page Design', 'item' => $canonical],
            ],
        ],
        [
            '@type' => 'FAQPage',
            '@id' => $canonical . '#faq',
            'mainEntity' => array_map(static fn(array $faq): array => ['@type' => 'Question', 'name' => $faq['q'], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq['a']]], $faqs),
        ],
    ],
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= cbd_escape_text($pageTitle) ?></title>
    <meta name="description" content="<?= cbd_escape_text($pageDescription) ?>">
    <link rel="canonical" href="<?= cbd_escape_text($canonical) ?>">
    <meta property="og:type" content="website"><meta property="og:title" content="<?= cbd_escape_text($pageTitle) ?>"><meta property="og:description" content="<?= cbd_escape_text($pageDescription) ?>"><meta property="og:url" content="<?= cbd_escape_text($canonical) ?>"><meta property="og:image" content="<?= cbd_escape_text($shareImage) ?>">
    <meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@chulbuldesign"><meta name="twitter:title" content="<?= cbd_escape_text($pageTitle) ?>"><meta name="twitter:description" content="<?= cbd_escape_text($pageDescription) ?>"><meta name="twitter:image" content="<?= cbd_escape_text($shareImage) ?>">
    <link rel="preload" as="image" href="<?= $base ?>/assets/images/service-heroes/landing-page-design-hero.webp" fetchpriority="high">
    <script type="application/ld+json"><?= cbd_json_ld($schema) ?></script>
    <?php require __DIR__ . '/includes/header.php'; ?>

<div class="wd-page">
    <section class="wd-hero" aria-labelledby="landing-page-title"><div class="wd-orb wd-orb-one" aria-hidden="true"></div><div class="wd-orb wd-orb-two" aria-hidden="true"></div><div class="wd-container wd-hero-grid">
        <div class="wd-hero-copy wd-reveal"><nav class="wd-breadcrumb" aria-label="Breadcrumb"><a href="<?= $base ?>/">Home</a><span aria-hidden="true">/</span><a href="<?= $base ?>/web-design-development">Web Design &amp; Development</a><span aria-hidden="true">/</span><span aria-current="page">Landing Page Design</span></nav><span class="wd-eyebrow"><i class="bi bi-bullseye" aria-hidden="true"></i> Landing Page Design Services</span><h1 id="landing-page-title">Landing Page Design Services for <span>Campaigns and Lead Generation</span></h1><p class="wd-hero-lead">We design focused landing pages that connect an ad, audience and offer with one meaningful next action. Message continuity, responsive UX, trustworthy proof, practical forms and measurement planning work together to reduce post-click confusion and create a page your team can improve.</p><div class="wd-actions"><a class="wd-button wd-button-primary" href="<?= $base ?>/contact-us"><i class="bi bi-chat-dots-fill" aria-hidden="true"></i> Discuss Your Campaign</a><a class="wd-button wd-button-secondary" href="#landing-services">Explore Landing Page Services <i class="bi bi-arrow-down" aria-hidden="true"></i></a></div><ul class="wd-trust-list" aria-label="Landing page design commitments"><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> One clear campaign goal</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Ad-to-page message match</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Mobile-first form experience</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Tracking-ready action plan</li></ul></div>
        <div class="wd-hero-visual wd-reveal"><div class="wd-browser"><div class="wd-browser-bar" aria-hidden="true"><span></span><span></span><span></span><b>your-campaign.com</b></div><img src="<?= $base ?>/assets/images/service-heroes/landing-page-design-hero.webp" alt="Conversion-focused landing page design showing campaign messaging, lead forms and analytics tracking" width="960" height="640" fetchpriority="high"><div class="wd-code-chip wd-code-chip-one" aria-hidden="true"><i class="bi bi-bullseye"></i><span>One focused action</span></div><div class="wd-code-chip wd-code-chip-two" aria-hidden="true"><i class="bi bi-bar-chart-line"></i><span>Built to measure</span></div></div></div>
    </div></section>

    <section class="wd-section wd-intro"><div class="wd-container wd-narrow wd-reveal"><span class="wd-kicker">The experience after the click</span><h2>A Good Ad Cannot Rescue an Unclear Landing Page</h2><p>Paid campaigns create expectations before a visitor reaches your website. A search ad may promise a specific service, price or location. A social ad may introduce a problem the visitor was not actively researching. If the destination opens with a broad company message, unrelated navigation and several competing actions, the visitor has to rebuild the connection for themselves.</p><p>Landing page design protects that connection. We identify the exact audience, campaign promise, traffic context and primary conversion before planning the page. The opening section confirms relevance quickly, the body answers the questions required for a decision and the call to action appears where it makes sense—not simply at fixed visual intervals.</p><p>Focused does not mean artificially short. A familiar low-risk offer may need a concise explanation, while a high-value B2B service may require process, proof, objections, security or pricing context. Page length follows decision complexity. The goal is to remove irrelevant choices while retaining the information a qualified visitor genuinely needs.</p></div></section>

    <section class="wd-section wd-section-soft" id="landing-services" aria-labelledby="landing-services-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Landing page capabilities</span><h2 id="landing-services-title">Landing Page Design Services</h2><p>Strategy, interface, forms and measurement aligned around the same campaign outcome.</p></div><div class="wd-service-grid"><?php foreach ($landingServices as $index => $service): ?><article class="wd-service-card wd-reveal"><span class="wd-card-number"><?= str_pad((string)($index + 1), 2, '0', STR_PAD_LEFT) ?></span><div class="wd-icon"><i class="bi <?= cbd_escape_text($service['icon']) ?>" aria-hidden="true"></i></div><h3><?= cbd_escape_text($service['title']) ?></h3><p><?= cbd_escape_text($service['text']) ?></p><?php if (!empty($service['href'])): ?><a href="<?= $base . cbd_escape_text($service['href']) ?>"><?= cbd_escape_text($service['link']) ?> <i class="bi bi-arrow-right" aria-hidden="true"></i></a><?php endif; ?></article><?php endforeach; ?></div></div></section>

    <section class="wd-section"><div class="wd-container wd-split"><div class="wd-media-panel wd-reveal"><img src="<?= $base ?>/assets/images/built-around-your-requirements.webp" alt="Landing page message and customer journey planning" width="900" height="725" loading="lazy"><div class="wd-media-caption"><i class="bi bi-arrow-down-right-circle" aria-hidden="true"></i><span>Ad promise → page evidence → campaign action</span></div></div><div class="wd-copy wd-reveal"><span class="wd-kicker">Message match and relevance</span><h2>Continue the Conversation Started by the Campaign</h2><p>Message match means the visitor can immediately recognize that the page is the expected next step. The headline, offer, terminology and visual context should support the source campaign without copying an ad mechanically. This is especially important when several ad groups target different services, audiences or problems.</p><p>We map the campaign promise against the evidence available on the page. If an ad emphasizes speed, the page should explain delivery and constraints. If it emphasizes specialist expertise, the page should demonstrate relevant process or work. Claims that cannot be supported are refined instead of enlarged through design.</p><ul class="wd-check-list"><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Traffic context:</strong> understand what the visitor searched, saw or was promised before arrival.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Opening confirmation:</strong> establish audience, offer and relevance without a long introduction.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Supporting evidence:</strong> connect real process, proof and details to the campaign’s central claim.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Consistent action:</strong> repeat one primary conversion logically without introducing competing journeys.</span></li></ul></div></div></section>

    <section class="wd-section wd-solutions" aria-labelledby="campaign-types-title"><div class="wd-container"><div class="wd-heading wd-heading-light wd-reveal"><span class="wd-kicker">Designed for campaign context</span><h2 id="campaign-types-title">Landing Pages for Different Traffic and Offers</h2><p>Search intent, audience awareness and decision complexity determine what the page needs to explain.</p></div><div class="wd-solution-grid"><?php foreach ($campaignTypes as $campaign): ?><article class="wd-solution-card wd-reveal"><i class="bi <?= cbd_escape_text($campaign['icon']) ?>" aria-hidden="true"></i><h3><?= cbd_escape_text($campaign['title']) ?></h3><p><?= cbd_escape_text($campaign['text']) ?></p></article><?php endforeach; ?></div></div></section>

    <section class="wd-section" aria-labelledby="landing-foundation-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">A focused conversion foundation</span><h2 id="landing-foundation-title">Offer, Evidence and Action Working Together</h2><p>Every section should help a qualified visitor understand the offer or become more confident in the next step.</p></div><div class="wd-stack-grid"><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">01 / Offer</span><h3>A specific reason to continue</h3><p>The page identifies who the offer is for, what it helps them achieve and what is included or expected.</p><div class="wd-tags"><span>Audience</span><span>Promise</span><span>Scope</span><span>Context</span></div></article><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">02 / Evidence</span><h3>Enough confidence to decide</h3><p>Process, work, details, answers and genuine trust signals support the claims that matter to this audience.</p><div class="wd-tags"><span>Proof</span><span>Process</span><span>Objections</span><span>FAQs</span></div></article><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">03 / Action</span><h3>A clear and usable next step</h3><p>The form, call, booking or purchase path asks for appropriate effort and explains what happens afterward.</p><div class="wd-tags"><span>CTA</span><span>Forms</span><span>Feedback</span><span>Tracking</span></div></article></div></div></section>

    <section class="wd-section wd-section-soft"><div class="wd-container wd-split wd-split-reverse"><div class="wd-copy wd-reveal"><span class="wd-kicker">Forms that respect the visitor</span><h2>Collect the Information Your Team Can Actually Use</h2><p>A form is part of the customer experience, not an administrative attachment at the bottom of a page. We define which information is necessary for the next business step and organize fields in a logical sequence. Optional and required details are clear, labels remain visible and errors explain how to continue.</p><p>Lead quality and form completion must be balanced. Removing every field can create unusable enquiries, while requesting internal sales qualification data too early can discourage suitable prospects. Confirmation states also matter: visitors should know whether a submission succeeded, when to expect a response and whether another action is required.</p><div class="wd-integration-list"><span><i class="bi bi-ui-checks"></i> Clear field labels</span><span><i class="bi bi-list-ol"></i> Logical question order</span><span><i class="bi bi-exclamation-circle"></i> Helpful error states</span><span><i class="bi bi-shield-check"></i> Privacy-aware consent</span><span><i class="bi bi-check-circle"></i> Useful confirmation</span><span><i class="bi bi-person-lines-fill"></i> CRM-ready lead data</span></div><a class="wd-text-link" href="<?= $base ?>/api-integration">Explore form and CRM integrations <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div><div class="wd-api-visual wd-reveal" aria-label="Illustration of landing page lead data connected to business systems"><div class="wd-api-core"><i class="bi bi-ui-checks" aria-hidden="true"></i><strong>Form</strong></div><div class="wd-api-node wd-api-node-one"><i class="bi bi-megaphone"></i><span>Campaign</span></div><div class="wd-api-node wd-api-node-two"><i class="bi bi-person-lines-fill"></i><span>CRM</span></div><div class="wd-api-node wd-api-node-three"><i class="bi bi-envelope-check"></i><span>Follow-up</span></div><div class="wd-api-node wd-api-node-four"><i class="bi bi-bar-chart"></i><span>Analytics</span></div></div></div></section>

    <section class="wd-section"><div class="wd-container wd-split"><div class="wd-media-panel wd-reveal"><img src="<?= $base ?>/assets/images/page-speed-1.webp" alt="Landing page analytics, performance and conversion measurement" width="900" height="725" loading="lazy"><div class="wd-media-caption"><i class="bi bi-graph-up-arrow" aria-hidden="true"></i><span>Measure → learn → prioritize → improve</span></div></div><div class="wd-copy wd-reveal"><span class="wd-kicker">Measurement before experiments</span><h2>Define a Conversion Before Reading the Dashboard</h2><p>Page views and button clicks are not automatically business outcomes. Before launch, we document the primary conversion and the supporting events that help explain the journey. A form success, confirmed booking, qualified call or completed purchase is more meaningful than an interaction that may not indicate intent.</p><p>Testing should follow evidence. If a page has insufficient traffic, an A/B result may be noise. We first confirm tracking quality, segment campaign sources and review obvious usability problems. Then hypotheses can target meaningful questions such as offer clarity, proof order, form effort or the relationship between ad and page.</p><ul class="wd-check-list"><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Conversion definition:</strong> agree which completed action represents campaign value.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Event plan:</strong> document forms, calls, bookings, purchases and useful supporting interactions.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Source continuity:</strong> preserve campaign attribution and use consistent naming where possible.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Evidence-led tests:</strong> prioritize hypotheses based on data and user friction rather than random color changes.</span></li></ul></div></div></section>

    <section class="wd-section" aria-labelledby="landing-quality-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Quality after the ad click</span><h2 id="landing-quality-title">Relevance, Usability, Performance and Measurement</h2><p>A conversion-focused page needs all four; a weakness in one can distort the campaign result.</p></div><div class="wd-quality-grid"><article class="wd-quality-card wd-reveal"><i class="bi bi-bullseye"></i><h3>Relevance</h3><p>The headline, offer and proof continue the context that motivated the visitor to click.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-hand-index"></i><h3>Usability</h3><p>Readable hierarchy, responsive controls and clear forms reduce avoidable task friction.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-lightning-charge"></i><h3>Performance</h3><p>Responsible media, code and third-party tools help the useful content arrive sooner.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-bar-chart"></i><h3>Measurement</h3><p>Valid events and campaign attribution support decisions after the page goes live.</p></article></div></div></section>

    <section class="wd-section wd-process" aria-labelledby="landing-process-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">A clear landing page process</span><h2 id="landing-process-title">From Campaign Brief to Measurable Launch</h2><p>Creative, development and tracking decisions remain connected through every stage.</p></div><ol class="wd-process-list"><li class="wd-reveal"><span>01</span><div><h3>Campaign Discovery</h3><p>We review traffic source, audience, offer, business goal, constraints and existing performance data.</p></div></li><li class="wd-reveal"><span>02</span><div><h3>Message &amp; Content Plan</h3><p>The campaign promise, visitor questions, proof, objections and primary action are organized.</p></div></li><li class="wd-reveal"><span>03</span><div><h3>Wireframe &amp; Form Journey</h3><p>Page hierarchy, CTA placement, fields and confirmation behavior are reviewed before styling.</p></div></li><li class="wd-reveal"><span>04</span><div><h3>Responsive Visual Design</h3><p>The approved structure becomes a focused brand experience across relevant screen sizes.</p></div></li><li class="wd-reveal"><span>05</span><div><h3>Development &amp; Tracking</h3><p>The page, integrations and agreed analytics events are implemented and validated.</p></div></li><li class="wd-reveal"><span>06</span><div><h3>QA, Launch &amp; Learning</h3><p>Content, links, forms, devices, speed and measurement are checked before observations begin.</p></div></li></ol></div></section>

    <section class="wd-section wd-proof" aria-labelledby="landing-proof-title"><div class="wd-container wd-proof-grid"><div class="wd-proof-copy wd-reveal"><span class="wd-kicker">Review relevant work</span><h2 id="landing-proof-title">Landing Page Decisions and Delivery Experience You Can Review</h2><p>Our portfolio includes digital delivery experience connected with Gurjar Pragati Manch, Kisaan Jee and Tera Ghar. Relevant examples provide practical context for evaluating message hierarchy, mobile journeys, forms and the relationship between campaign traffic and the next customer action.</p><p>During a consultation, we explain our role and walk through the decisions behind page structure, proof placement, responsive behavior, lead capture and tracking readiness. For broader engineering requirements, Chulbul Design can also collaborate with SoftLes as a technology partner.</p><a class="wd-button wd-button-primary" href="<?= $base ?>/#portfolio">Review Selected Work</a></div><div class="wd-proof-logos wd-reveal" aria-label="Selected client and partnership portfolio"><?php foreach ([['gurjar-pragati-manch.webp','Gurjar Pragati Manch'],['kisaanjee.webp','Kisaan Jee'],['tera-ghar.webp','Tera Ghar']] as $logo): ?><div><img src="<?= $base ?>/assets/images/client-logos/<?= cbd_escape_text($logo[0]) ?>" alt="<?= cbd_escape_text($logo[1]) ?>" width="180" height="72" loading="lazy"><span><?= cbd_escape_text($logo[1]) ?></span></div><?php endforeach; ?><a href="https://softles.in/" target="_blank" rel="noopener noreferrer"><strong>S</strong><span>Technology partner: SoftLes <i class="bi bi-box-arrow-up-right" aria-hidden="true"></i></span></a></div></div></section>

    <section class="wd-section" aria-labelledby="landing-why-title"><div class="wd-container wd-split"><div class="wd-copy wd-reveal"><span class="wd-kicker">Why Chulbul Design</span><h2 id="landing-why-title">Design, Development and Campaign Context in One Conversation</h2><p>A landing page sits between advertising and sales, so visual design cannot be isolated from message, implementation, tracking and follow-up. We keep those decisions visible in the scope and explain recommendations through visitor intent and business use—not through generic “best practice” claims.</p><p>Our Gurugram-based team serves businesses in India and international markets through planned remote collaboration. We agree meeting windows, milestones and feedback channels at the start without claiming offices where we do not have them.</p></div><div class="wd-reasons wd-reveal"><div><i class="bi bi-bullseye"></i><span><strong>Campaign-first planning</strong>The traffic, offer and conversion define the page purpose.</span></div><div><i class="bi bi-phone"></i><span><strong>Mobile-focused execution</strong>Hierarchy and forms reflect the screens most paid visitors use.</span></div><div><i class="bi bi-bar-chart-line"></i><span><strong>Measurement clarity</strong>Events are defined around business actions before launch.</span></div><div><i class="bi bi-code-slash"></i><span><strong>Design-to-build continuity</strong>Responsive and tracking requirements remain connected in development.</span></div></div></div></section>

    <section class="wd-section wd-section-soft" aria-labelledby="landing-cost-title"><div class="wd-container wd-cost-grid"><div class="wd-heading wd-heading-left wd-reveal"><span class="wd-kicker">Planning the investment</span><h2 id="landing-cost-title">What Affects Landing Page Design Cost?</h2><p>The estimate depends on the campaign system required—not simply whether a page has one URL.</p></div><div class="wd-cost-list wd-reveal"><div><span>01</span><p><strong>Strategy and variants</strong>Audiences, offers, traffic sources, research and number of distinct page versions.</p></div><div><span>02</span><p><strong>Content and creative</strong>Copy support, brand assets, illustration, photography, video and proof preparation.</p></div><div><span>03</span><p><strong>Forms and integrations</strong>Field logic, CRM, booking, payment, notifications and confirmation workflows.</p></div><div><span>04</span><p><strong>Development and performance</strong>Platform, responsive complexity, reusable sections, media and third-party scripts.</p></div><div><span>05</span><p><strong>Measurement and testing</strong>Analytics access, conversion events, attribution, QA and planned experiments.</p></div></div></div></section>

    <section class="wd-section" aria-labelledby="landing-related-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Related expertise</span><h2 id="landing-related-title">Connect the Landing Page to the Wider Growth System</h2><p>Campaign results also depend on traffic, development quality, measurement and ongoing improvement.</p></div><div class="wd-related-grid"><a class="wd-related-card wd-reveal" href="<?= $base ?>/web-design"><i class="bi bi-palette2"></i><span><strong>Web Design</strong>Strategy and responsive design for the wider website.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/google-ads-ppc"><i class="bi bi-google"></i><span><strong>Google Ads &amp; PPC</strong>Campaign structure, targeting and conversion measurement.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/conversion-rate-optimization"><i class="bi bi-graph-up-arrow"></i><span><strong>Conversion Optimization</strong>Evidence-led improvements to existing customer journeys.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/web-development"><i class="bi bi-code-slash"></i><span><strong>Web Development</strong>Responsive implementation, forms and integrations.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a></div></div></section>

    <section class="wd-section wd-faq" aria-labelledby="landing-faq-title"><div class="wd-container wd-faq-grid"><div class="wd-heading wd-heading-left wd-reveal"><span class="wd-kicker">Frequently asked questions</span><h2 id="landing-faq-title">Landing Page Design FAQs</h2><p>Clear answers for teams planning paid campaigns, lead-generation pages or conversion improvements.</p><a class="wd-text-link" href="<?= $base ?>/contact-us">Ask a campaign-specific question <i class="bi bi-arrow-right"></i></a></div><div class="wd-accordion wd-reveal"><?php foreach ($faqs as $index => $faq): ?><details<?= $index === 0 ? ' open' : '' ?>><summary><?= cbd_escape_text($faq['q']) ?><i class="bi bi-plus-lg" aria-hidden="true"></i></summary><p><?= cbd_escape_text($faq['a']) ?></p></details><?php endforeach; ?></div></div></section>

    <section class="wd-final-cta"><div class="wd-container wd-reveal"><span class="wd-kicker">Planning a paid campaign?</span><h2>Let’s Align the Ad, Page and Conversion Before Launch.</h2><p>Share your traffic source, audience, offer and intended action. We will help define a focused landing page scope and the next step.</p><div class="wd-actions"><a class="wd-button wd-button-white" href="<?= $base ?>/contact-us"><i class="bi bi-envelope-fill" aria-hidden="true"></i> Request a Campaign Discussion</a><a class="wd-button wd-button-outline" href="https://wa.me/919990548795?text=Hi%20Chulbul%20Design%2C%20I%20want%20to%20discuss%20a%20landing%20page%20design%20project." target="_blank" rel="noopener noreferrer"><i class="bi bi-whatsapp" aria-hidden="true"></i> Chat on WhatsApp</a></div></div></section>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    var items = document.querySelectorAll('.wd-reveal');
    if (!('IntersectionObserver' in window) || window.matchMedia('(prefers-reduced-motion: reduce)').matches) { items.forEach(function (item) { item.classList.add('is-visible'); }); return; }
    var observer = new IntersectionObserver(function (entries) { entries.forEach(function (entry) { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }); }, { threshold: 0.08, rootMargin: '0px 0px -40px' });
    items.forEach(function (item) { observer.observe(item); });
});
</script>

<?php require __DIR__ . '/includes/footer.php'; ?>
