<?php
require_once __DIR__ . '/includes/http.php';
require_once __DIR__ . '/includes/seo.php';

$cbd_page_has_charset = true;
$page_styles = ['/assets/css/web-development.css'];

if (cbd_is_direct_script_request('website-redesign.php')) {
    cbd_redirect_path('/website-redesign');
}

$base = cbd_base_path();
$canonical = cbd_canonical_url('/website-redesign');
$page_robots = 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1';
$pageTitle = 'Website Redesign Services | Chulbul Design';
$pageDescription = 'Strategic website redesign services covering UX, responsive design, content, SEO-safe migration, CMS modernization, accessibility and performance.';
$shareImage = cbd_public_url('/assets/images/service-heroes/website-redesign-hero.webp');

$redesignServices = [
    ['icon' => 'bi-clipboard-data', 'title' => 'Website Audit & Redesign Strategy', 'text' => 'Review business goals, analytics, content, search visibility, technology and customer friction before deciding what changes.'],
    ['icon' => 'bi-signpost-split', 'title' => 'Information Architecture Redesign', 'text' => 'Simplify navigation, page relationships and content hierarchy around the questions visitors actually need answered.'],
    ['icon' => 'bi-palette2', 'title' => 'Visual & Brand Redesign', 'text' => 'Create a contemporary, distinctive interface while retaining useful brand recognition and practical consistency.', 'href' => '/web-design', 'link' => 'Explore custom web design'],
    ['icon' => 'bi-phone', 'title' => 'Responsive UX Redesign', 'text' => 'Rework navigation, reading order, forms and interactions for mobile, tablet and desktop behavior.'],
    ['icon' => 'bi-file-earmark-text', 'title' => 'Content Restructuring', 'text' => 'Retain valuable information, remove duplication and reshape pages around clear audience intent and business action.'],
    ['icon' => 'bi-search', 'title' => 'SEO-Safe URL Migration', 'text' => 'Map important URLs, metadata, internal links and redirects to reduce avoidable organic-search disruption.', 'href' => '/technical-seo', 'link' => 'Explore technical SEO'],
    ['icon' => 'bi-speedometer2', 'title' => 'Performance-Focused Rebuild', 'text' => 'Address heavy templates, oversized media and inefficient frontend choices as part of the redesign implementation.', 'href' => '/website-speed-optimization', 'link' => 'Explore speed optimization'],
    ['icon' => 'bi-window-stack', 'title' => 'CMS Modernization', 'text' => 'Improve the editor experience, content structure, permissions and platform maintainability without losing ownership.', 'href' => '/cms-development', 'link' => 'Explore CMS development'],
    ['icon' => 'bi-universal-access', 'title' => 'Accessibility Improvement', 'text' => 'Plan semantic structure, contrast, focus, labels and keyboard-aware components into the new experience.'],
    ['icon' => 'bi-graph-up-arrow', 'title' => 'Conversion Journey Redesign', 'text' => 'Clarify value, proof, forms and calls to action, then define meaningful analytics events for improvement.', 'href' => '/conversion-rate-optimization', 'link' => 'Explore conversion optimization'],
];

$redesignReasons = [
    ['icon' => 'bi-hourglass-split', 'title' => 'An Outdated Brand Experience', 'text' => 'The website no longer reflects the quality, positioning or maturity of the organization.'],
    ['icon' => 'bi-phone', 'title' => 'Weak Mobile Usability', 'text' => 'Navigation, content, forms or calls to action become difficult on smaller screens.'],
    ['icon' => 'bi-diagram-3', 'title' => 'Confusing Structure', 'text' => 'Visitors struggle to compare services, find important pages or understand where to continue.'],
    ['icon' => 'bi-speedometer2', 'title' => 'Slow Page Experience', 'text' => 'Heavy themes, media and third-party scripts delay access to useful content.'],
    ['icon' => 'bi-pencil-square', 'title' => 'Difficult Content Updates', 'text' => 'Editors rely on developers or fragile page layouts for routine publishing work.'],
    ['icon' => 'bi-search', 'title' => 'Organic Search Risk', 'text' => 'Duplicate pages, broken links, missing structure or unmanaged migrations weaken crawl signals.'],
    ['icon' => 'bi-ui-checks', 'title' => 'Low-Quality Enquiries', 'text' => 'The offer, proof and forms do not help suitable prospects understand or qualify themselves.'],
    ['icon' => 'bi-shield-exclamation', 'title' => 'Unsupported Technology', 'text' => 'Old dependencies, themes or frameworks make security and maintenance increasingly difficult.'],
    ['icon' => 'bi-translate', 'title' => 'Content Has Outgrown the Site', 'text' => 'New services, regions or languages no longer fit the original navigation and templates.'],
    ['icon' => 'bi-people', 'title' => 'Business Change', 'text' => 'A merger, repositioning or audience shift requires a clearer digital story and ownership model.'],
];

$faqs = [
    ['q' => 'What is a website redesign?', 'a' => 'A website redesign is a planned improvement to an existing website’s structure, content, interface and often its technology. A responsible redesign begins with an audit so useful pages, customer journeys, data and search signals are not discarded simply because the visual style is changing.'],
    ['q' => 'How is a redesign different from a visual refresh?', 'a' => 'A visual refresh mainly changes typography, color, imagery and surface styling. A redesign may also change navigation, page hierarchy, content, forms, templates, CMS, integrations and conversion journeys. We recommend the smallest scope that addresses the actual problems.'],
    ['q' => 'Will a website redesign hurt our SEO?', 'a' => 'Any major website change can affect search performance, especially when URLs, content or internal links change. Risk can be reduced through audits, URL mapping, redirects, metadata preservation, crawl checks and post-launch monitoring, but no responsible provider can guarantee that rankings will never fluctuate.'],
    ['q' => 'Can you keep our existing URLs and content?', 'a' => 'Yes, when they remain useful and accurate. We review which URLs receive search traffic, links or business use, then decide what should stay, improve, merge or redirect. Valuable content is not removed merely to make the sitemap look simpler.'],
    ['q' => 'Can you redesign a WordPress or Joomla website?', 'a' => 'Yes. We can redesign the public experience while reviewing themes, extensions, editor workflows and the current platform version. The project may retain the CMS, modernize it or migrate to another option when there is a clear operational reason.'],
    ['q' => 'Should we redesign or rebuild the website?', 'a' => 'That decision follows a technical and content audit. A sound codebase may only need interface and template changes. Unsupported dependencies, severe performance constraints or a mismatched CMS can justify a rebuild, but rebuilding everything is not automatically the best option.'],
    ['q' => 'How long does a website redesign take?', 'a' => 'A focused marketing-site redesign may take several weeks, while a large content migration, multilingual platform or integration-heavy rebuild takes longer. Timing depends on audit findings, content readiness, template count, approvals, development and testing.'],
    ['q' => 'How much does website redesign cost?', 'a' => 'Cost depends on audit depth, page templates, content work, brand changes, CMS, migration volume, redirects, integrations, accessibility, performance and testing. We provide a written scope after reviewing the existing website and goals.'],
    ['q' => 'Can the current website stay live during redesign?', 'a' => 'Usually yes. Design and development take place in a separate environment, while the existing site remains available. Launch planning covers backups, content freeze, final migration, DNS or hosting changes, redirects, testing and a rollback decision if a critical issue appears.'],
    ['q' => 'What should we measure after launching the redesign?', 'a' => 'Useful measures depend on the website’s purpose. They may include qualified enquiries, successful forms, calls, bookings, purchases, organic landing-page performance, task completion, speed and error rates. Baseline data should be captured before launch for a meaningful comparison.'],
];

$schemaOffers = [];
foreach ($redesignServices as $service) {
    $schemaOffers[] = ['@type' => 'Offer', 'itemOffered' => ['@type' => 'Service', 'name' => $service['title']]];
}

$schema = [
    '@context' => 'https://schema.org',
    '@graph' => [
        [
            '@type' => 'Service', '@id' => $canonical . '#service', 'name' => 'Website Redesign Services',
            'serviceType' => 'Website Redesign', 'url' => $canonical, 'description' => $pageDescription,
            'provider' => [
                '@type' => 'Organization', '@id' => CBD_CANONICAL_ORIGIN . '/#organization', 'name' => 'Chulbul Design',
                'url' => CBD_CANONICAL_ORIGIN . '/', 'telephone' => '+919990548795',
                'address' => ['@type' => 'PostalAddress', 'streetAddress' => 'Sector 15, Flat No. 1277', 'addressLocality' => 'Gurugram', 'addressRegion' => 'Haryana', 'postalCode' => '122001', 'addressCountry' => 'IN'],
            ],
            'areaServed' => 'Worldwide',
            'hasOfferCatalog' => ['@type' => 'OfferCatalog', 'name' => 'Website Redesign Services', 'itemListElement' => $schemaOffers],
        ],
        [
            '@type' => 'BreadcrumbList', '@id' => $canonical . '#breadcrumb',
            'itemListElement' => [
                ['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => CBD_CANONICAL_ORIGIN . '/'],
                ['@type' => 'ListItem', 'position' => 2, 'name' => 'Web Design & Development', 'item' => cbd_canonical_url('/web-design-development')],
                ['@type' => 'ListItem', 'position' => 3, 'name' => 'Website Redesign', 'item' => $canonical],
            ],
        ],
        ['@type' => 'FAQPage', '@id' => $canonical . '#faq', 'mainEntity' => array_map(static fn(array $faq): array => ['@type' => 'Question', 'name' => $faq['q'], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq['a']]], $faqs)],
    ],
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= cbd_escape_text($pageTitle) ?></title>
    <meta name="description" content="<?= cbd_escape_text($pageDescription) ?>">
    <link rel="canonical" href="<?= cbd_escape_text($canonical) ?>">
    <meta property="og:type" content="website"><meta property="og:title" content="<?= cbd_escape_text($pageTitle) ?>"><meta property="og:description" content="<?= cbd_escape_text($pageDescription) ?>"><meta property="og:url" content="<?= cbd_escape_text($canonical) ?>"><meta property="og:image" content="<?= cbd_escape_text($shareImage) ?>">
    <meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@chulbuldesign"><meta name="twitter:title" content="<?= cbd_escape_text($pageTitle) ?>"><meta name="twitter:description" content="<?= cbd_escape_text($pageDescription) ?>"><meta name="twitter:image" content="<?= cbd_escape_text($shareImage) ?>">
    <link rel="preload" as="image" href="<?= $base ?>/assets/images/service-heroes/website-redesign-hero.webp" fetchpriority="high">
    <script type="application/ld+json"><?= cbd_json_ld($schema) ?></script>
    <?php require __DIR__ . '/includes/header.php'; ?>

<div class="wd-page">
    <section class="wd-hero" aria-labelledby="redesign-page-title"><div class="wd-orb wd-orb-one" aria-hidden="true"></div><div class="wd-orb wd-orb-two" aria-hidden="true"></div><div class="wd-container wd-hero-grid">
        <div class="wd-hero-copy wd-reveal"><nav class="wd-breadcrumb" aria-label="Breadcrumb"><a href="<?= $base ?>/">Home</a><span aria-hidden="true">/</span><a href="<?= $base ?>/web-design-development">Web Design &amp; Development</a><span aria-hidden="true">/</span><span aria-current="page">Website Redesign</span></nav><span class="wd-eyebrow"><i class="bi bi-arrow-repeat" aria-hidden="true"></i> Website Redesign Services</span><h1 id="redesign-page-title">Website Redesign Services for <span>Better UX, SEO and Performance</span></h1><p class="wd-hero-lead">We redesign outdated websites by identifying what should improve and what must be protected. Customer journeys, content, visual design, mobile usability, CMS, performance and search migration are planned together so the new experience solves real problems instead of only changing appearance.</p><div class="wd-actions"><a class="wd-button wd-button-primary" href="<?= $base ?>/contact-us"><i class="bi bi-chat-dots-fill" aria-hidden="true"></i> Request a Website Review</a><a class="wd-button wd-button-secondary" href="#redesign-services">Explore Redesign Services <i class="bi bi-arrow-down" aria-hidden="true"></i></a></div><ul class="wd-trust-list" aria-label="Website redesign commitments"><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Audit before redesign</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Important URLs mapped</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Responsive UX rebuilt</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Staged launch and QA</li></ul></div>
        <div class="wd-hero-visual wd-reveal"><div class="wd-browser"><div class="wd-browser-bar" aria-hidden="true"><span></span><span></span><span></span><b>your-new-website.com</b></div><img src="<?= $base ?>/assets/images/service-heroes/website-redesign-hero.webp" alt="Website redesign planning showing UX improvements, responsive layouts, SEO migration and performance" width="960" height="640" fetchpriority="high"><div class="wd-code-chip wd-code-chip-one" aria-hidden="true"><i class="bi bi-signpost-split"></i><span>Clearer customer journey</span></div><div class="wd-code-chip wd-code-chip-two" aria-hidden="true"><i class="bi bi-shield-check"></i><span>Migration planned</span></div></div></div>
    </div></section>

    <section class="wd-section wd-intro"><div class="wd-container wd-narrow wd-reveal"><span class="wd-kicker">Improve without discarding value</span><h2>A Redesign Should Preserve What Works and Fix What Does Not</h2><p>Websites accumulate history. New services are added to old navigation, campaigns create isolated pages, plugins introduce inconsistent interfaces and important content becomes difficult to find. The site may still contain valuable search visibility, customer familiarity and working business processes even when the overall experience feels outdated.</p><p>Starting from a blank canvas without examining that value creates unnecessary risk. Chulbul Design begins with the current website: its pages, traffic, search queries, forms, technology, content ownership and known customer problems. We separate evidence from preference. Some issues need a visual response, while others come from unclear positioning, duplicated content, slow infrastructure or a CMS that no longer fits the team.</p><p>The redesign plan defines what stays, what changes and why. That creates a stronger basis for scope, content preparation and migration. It also prevents the common situation where a visually polished replacement launches with missing pages, broken tracking, weak forms or redirects that were considered too late.</p></div></section>

    <section class="wd-section wd-section-soft" id="redesign-services" aria-labelledby="redesign-services-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Redesign capabilities</span><h2 id="redesign-services-title">Website Redesign Services</h2><p>Audit, experience, content, technology and migration coordinated as one controlled improvement program.</p></div><div class="wd-service-grid"><?php foreach ($redesignServices as $index => $service): ?><article class="wd-service-card wd-reveal"><span class="wd-card-number"><?= str_pad((string)($index + 1), 2, '0', STR_PAD_LEFT) ?></span><div class="wd-icon"><i class="bi <?= cbd_escape_text($service['icon']) ?>" aria-hidden="true"></i></div><h3><?= cbd_escape_text($service['title']) ?></h3><p><?= cbd_escape_text($service['text']) ?></p><?php if (!empty($service['href'])): ?><a href="<?= $base . cbd_escape_text($service['href']) ?>"><?= cbd_escape_text($service['link']) ?> <i class="bi bi-arrow-right" aria-hidden="true"></i></a><?php endif; ?></article><?php endforeach; ?></div></div></section>

    <section class="wd-section"><div class="wd-container wd-split"><div class="wd-media-panel wd-reveal"><img src="<?= $base ?>/assets/images/built-around-your-requirements.webp" alt="Existing website audit and redesign roadmap" width="900" height="725" loading="lazy"><div class="wd-media-caption"><i class="bi bi-clipboard-data" aria-hidden="true"></i><span>Audit → retain → improve → validate</span></div></div><div class="wd-copy wd-reveal"><span class="wd-kicker">Evidence before interface</span><h2>Audit the Existing Website Before Replacing It</h2><p>An audit creates a shared picture of the current state. We review business goals, audience journeys, page structure, analytics access, organic landing pages, content quality, forms, mobile behavior, accessibility indicators and technical constraints. The purpose is not to produce a long list of faults; it is to identify priorities that should shape the redesign.</p><p>Findings are grouped by impact and dependency. A navigation problem may need content consolidation before wireframes. Poor speed may come from hosting or scripts rather than visual layout. Low enquiries may reflect traffic intent or an unclear offer. This prevents design from being used as a superficial answer to every problem.</p><ul class="wd-check-list"><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Business audit:</strong> clarify offers, audiences, goals, internal ownership and known sales friction.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Content audit:</strong> identify valuable, outdated, duplicate and missing information.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>UX audit:</strong> review navigation, hierarchy, forms, responsive behavior and task completion.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Technical audit:</strong> examine platform, performance, integrations, crawlability and maintenance risk.</span></li></ul></div></div></section>

    <section class="wd-section wd-solutions" aria-labelledby="redesign-reasons-title"><div class="wd-container"><div class="wd-heading wd-heading-light wd-reveal"><span class="wd-kicker">Reasons to redesign</span><h2 id="redesign-reasons-title">Website Problems That Need More Than New Colors</h2><p>The redesign scope follows the underlying problem instead of treating every site as the same template replacement.</p></div><div class="wd-solution-grid"><?php foreach ($redesignReasons as $reason): ?><article class="wd-solution-card wd-reveal"><i class="bi <?= cbd_escape_text($reason['icon']) ?>" aria-hidden="true"></i><h3><?= cbd_escape_text($reason['title']) ?></h3><p><?= cbd_escape_text($reason['text']) ?></p></article><?php endforeach; ?></div></div></section>

    <section class="wd-section" aria-labelledby="redesign-foundation-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">A controlled redesign foundation</span><h2 id="redesign-foundation-title">Experience, Content and Technology Moving Together</h2><p>A redesign becomes fragile when these workstreams make independent decisions about the same website.</p></div><div class="wd-stack-grid"><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">01 / Experience</span><h3>A clearer customer journey</h3><p>Sitemap, navigation, hierarchy, responsive behavior and calls to action are rebuilt around real visitor tasks.</p><div class="wd-tags"><span>Research</span><span>Wireframes</span><span>UI System</span><span>Accessibility</span></div></article><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">02 / Content</span><h3>Useful information with ownership</h3><p>Existing pages are retained, improved, merged or retired through documented decisions and a practical content plan.</p><div class="wd-tags"><span>Audit</span><span>Mapping</span><span>Copy</span><span>Metadata</span></div></article><article class="wd-stack-card wd-reveal"><span class="wd-stack-label">03 / Technology</span><h3>A maintainable implementation</h3><p>CMS, templates, integrations, performance and deployment support the approved experience and future operation.</p><div class="wd-tags"><span>CMS</span><span>Code</span><span>APIs</span><span>Hosting</span></div></article></div></div></section>

    <section class="wd-section wd-section-soft"><div class="wd-container wd-split wd-split-reverse"><div class="wd-copy wd-reveal"><span class="wd-kicker">SEO-safe migration planning</span><h2>Change the Experience Without Carelessly Breaking Search Signals</h2><p>A redesign does not automatically require every URL to change. Existing pages may have rankings, external links, bookmarks or campaign history that are not obvious from the visual interface. We inventory current URLs and use search and analytics data where available before approving the new structure.</p><p>When a page moves, its closest relevant destination is documented. Permanent redirects are tested individually, internal links are updated and redirect chains are avoided. Canonicals, metadata, headings, schema, robots directives and sitemap output are reviewed on the new site. This reduces avoidable risk, but normal search reprocessing can still cause temporary movement after a major launch.</p><div class="wd-integration-list"><span><i class="bi bi-list-ul"></i> URL inventory</span><span><i class="bi bi-arrow-left-right"></i> Redirect mapping</span><span><i class="bi bi-link-45deg"></i> Internal-link updates</span><span><i class="bi bi-tags"></i> Metadata review</span><span><i class="bi bi-diagram-2"></i> Sitemap validation</span><span><i class="bi bi-graph-up"></i> Post-launch monitoring</span></div><a class="wd-text-link" href="<?= $base ?>/website-migration">Learn about website migration <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div><div class="wd-api-visual wd-reveal" aria-label="Illustration of old website URLs mapped to a redesigned website"><div class="wd-api-core"><i class="bi bi-arrow-repeat" aria-hidden="true"></i><strong>Redesign</strong></div><div class="wd-api-node wd-api-node-one"><i class="bi bi-file-earmark"></i><span>Old URLs</span></div><div class="wd-api-node wd-api-node-two"><i class="bi bi-signpost"></i><span>Redirects</span></div><div class="wd-api-node wd-api-node-three"><i class="bi bi-link-45deg"></i><span>Links</span></div><div class="wd-api-node wd-api-node-four"><i class="bi bi-search"></i><span>Search</span></div></div></div></section>

    <section class="wd-section"><div class="wd-container wd-split"><div class="wd-media-panel wd-reveal"><img src="<?= $base ?>/assets/images/responcive.webp" alt="Responsive website redesign across mobile and desktop" width="900" height="725" loading="lazy"><div class="wd-media-caption"><i class="bi bi-phone" aria-hidden="true"></i><span>Real content → responsive behavior → usable actions</span></div></div><div class="wd-copy wd-reveal"><span class="wd-kicker">Responsive redesign</span><h2>Rebuild Mobile Behavior, Not Just Desktop Styling</h2><p>Older websites often treat mobile as a smaller version of desktop. Large navigation, dense tables, fixed images and long forms become difficult to use even if the layout technically fits the screen. A redesign is an opportunity to reconsider priority, reading order and interaction—not simply introduce newer breakpoints.</p><p>We design with realistic content and identify responsive rules for repeated components. Navigation, comparison information, forms, galleries, calls to action and interactive states receive explicit behavior. Development QA then checks those decisions across representative devices and browsers.</p><ul class="wd-check-list"><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Content priority:</strong> essential information remains visible without preserving desktop order blindly.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Navigation:</strong> menus and wayfinding remain understandable for complex site structures.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Forms and actions:</strong> fields, validation and tap targets support comfortable mobile completion.</span></li><li><i class="bi bi-check2" aria-hidden="true"></i><span><strong>Media and components:</strong> imagery, cards, tables and interactive content adapt without hiding meaning.</span></li></ul></div></div></section>

    <section class="wd-section" aria-labelledby="redesign-quality-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Quality across the relaunch</span><h2 id="redesign-quality-title">UX, Search, Performance and Accessibility</h2><p>A successful redesign must improve the complete experience without trading one important quality for another.</p></div><div class="wd-quality-grid"><article class="wd-quality-card wd-reveal"><i class="bi bi-signpost-split"></i><h3>User Experience</h3><p>Clear structure, hierarchy and responsive actions help visitors complete meaningful tasks.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-search"></i><h3>Search Continuity</h3><p>Content value, URLs, redirects, metadata and crawl signals are mapped through migration.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-lightning-charge"></i><h3>Performance</h3><p>Templates, media, code and third-party tools are reviewed as part of the rebuild.</p></article><article class="wd-quality-card wd-reveal"><i class="bi bi-universal-access"></i><h3>Accessibility</h3><p>Semantic structure, contrast, focus, labels and keyboard use inform design and QA.</p></article></div></div></section>

    <section class="wd-section wd-process" aria-labelledby="redesign-process-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">A clear website redesign process</span><h2 id="redesign-process-title">From Existing-Site Audit to Monitored Relaunch</h2><p>Decisions are documented before content and URLs become launch-day surprises.</p></div><ol class="wd-process-list"><li class="wd-reveal"><span>01</span><div><h3>Discovery &amp; Baseline</h3><p>We confirm goals, audiences, current performance, stakeholders, technology and launch constraints.</p></div></li><li class="wd-reveal"><span>02</span><div><h3>UX, Content &amp; Technical Audit</h3><p>Pages, journeys, analytics, search signals, CMS and maintenance risks are reviewed together.</p></div></li><li class="wd-reveal"><span>03</span><div><h3>Sitemap &amp; Migration Plan</h3><p>The future structure, content decisions, URL mapping and ownership are documented.</p></div></li><li class="wd-reveal"><span>04</span><div><h3>Wireframes &amp; Visual Design</h3><p>Priority templates and responsive states are approved with realistic content and interactions.</p></div></li><li class="wd-reveal"><span>05</span><div><h3>Development, Content &amp; QA</h3><p>The new system is built, migrated and tested across functionality, devices, search and accessibility.</p></div></li><li class="wd-reveal"><span>06</span><div><h3>Launch &amp; Monitoring</h3><p>Backups, redirects, analytics and production checks are followed by post-launch review.</p></div></li></ol></div></section>

    <section class="wd-section wd-proof" aria-labelledby="redesign-proof-title"><div class="wd-container wd-proof-grid"><div class="wd-proof-copy wd-reveal"><span class="wd-kicker">Review relevant work</span><h2 id="redesign-proof-title">Website Redesign Work and Decisions You Can Review</h2><p>Our portfolio includes digital delivery experience connected with Gurjar Pragati Manch, Kisaan Jee and Tera Ghar. Relevant examples help demonstrate how existing content, navigation, responsive components and technical constraints can be assessed before a redesigned experience is implemented.</p><p>During a consultation, we explain our role and review the decisions behind information architecture, reusable components, content management, performance and migration planning. For broader engineering requirements, Chulbul Design can also collaborate with SoftLes as a technology partner.</p><a class="wd-button wd-button-primary" href="<?= $base ?>/#portfolio">Review Selected Work</a></div><div class="wd-proof-logos wd-reveal" aria-label="Selected client and partnership portfolio"><?php foreach ([['gurjar-pragati-manch.webp','Gurjar Pragati Manch'],['kisaanjee.webp','Kisaan Jee'],['tera-ghar.webp','Tera Ghar']] as $logo): ?><div><img src="<?= $base ?>/assets/images/client-logos/<?= cbd_escape_text($logo[0]) ?>" alt="<?= cbd_escape_text($logo[1]) ?>" width="180" height="72" loading="lazy"><span><?= cbd_escape_text($logo[1]) ?></span></div><?php endforeach; ?><a href="https://softles.in/" target="_blank" rel="noopener noreferrer"><strong>S</strong><span>Technology partner: SoftLes <i class="bi bi-box-arrow-up-right" aria-hidden="true"></i></span></a></div></div></section>

    <section class="wd-section" aria-labelledby="redesign-why-title"><div class="wd-container wd-split"><div class="wd-copy wd-reveal"><span class="wd-kicker">Why Chulbul Design</span><h2 id="redesign-why-title">Redesign Decisions Connected to Evidence and Ownership</h2><p>We do not assume everything old is wrong or everything new is better. Recommendations are connected to customers, content, analytics, search, implementation and long-term maintenance. Stakeholders can see why a page, feature or URL is being retained, changed or retired.</p><p>Our Gurugram-based team serves businesses in India and international markets through planned remote collaboration. We agree meeting windows, milestones and feedback channels at the start without claiming offices where we do not have them.</p></div><div class="wd-reasons wd-reveal"><div><i class="bi bi-clipboard-data"></i><span><strong>Audit-led scope</strong>Current value and risk are understood before replacement begins.</span></div><div><i class="bi bi-signpost-split"></i><span><strong>Customer-centered structure</strong>Navigation and content follow real questions and actions.</span></div><div><i class="bi bi-shield-check"></i><span><strong>Migration discipline</strong>URLs, content, integrations and analytics have documented ownership.</span></div><div><i class="bi bi-life-preserver"></i><span><strong>Post-launch support</strong>Monitoring and improvement continue after the redesigned site is live.</span></div></div></div></section>

    <section class="wd-section wd-section-soft" aria-labelledby="redesign-cost-title"><div class="wd-container wd-cost-grid"><div class="wd-heading wd-heading-left wd-reveal"><span class="wd-kicker">Planning the investment</span><h2 id="redesign-cost-title">What Affects Website Redesign Cost?</h2><p>The estimate depends on what must be understood, preserved and rebuilt—not only the number of current pages.</p></div><div class="wd-cost-list wd-reveal"><div><span>01</span><p><strong>Audit and strategy</strong>Stakeholders, analytics, search data, content inventory and technical discovery.</p></div><div><span>02</span><p><strong>Design and templates</strong>Brand direction, number of page types, responsive states and interaction complexity.</p></div><div><span>03</span><p><strong>Content and migration</strong>Copy support, media, languages, URL mapping, redirects and data quality.</p></div><div><span>04</span><p><strong>Technology and integrations</strong>CMS, custom development, forms, CRM, ecommerce and external systems.</p></div><div><span>05</span><p><strong>Quality and launch</strong>Accessibility, performance, testing, training, deployment and monitoring needs.</p></div></div></div></section>

    <section class="wd-section" aria-labelledby="redesign-related-title"><div class="wd-container"><div class="wd-heading wd-reveal"><span class="wd-kicker">Related expertise</span><h2 id="redesign-related-title">Build the Right Redesign Team Around the Findings</h2><p>The audit determines which design, development, migration and optimization capabilities are actually required.</p></div><div class="wd-related-grid"><a class="wd-related-card wd-reveal" href="<?= $base ?>/web-design"><i class="bi bi-palette2"></i><span><strong>Web Design</strong>Strategy, responsive interfaces and reusable design systems.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/web-development"><i class="bi bi-code-slash"></i><span><strong>Web Development</strong>Maintainable implementation, forms, systems and integrations.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/website-migration"><i class="bi bi-arrow-left-right"></i><span><strong>Website Migration</strong>Content, URLs, redirects and controlled platform moves.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a><a class="wd-related-card wd-reveal" href="<?= $base ?>/website-maintenance"><i class="bi bi-tools"></i><span><strong>Website Maintenance</strong>Post-launch updates, monitoring and technical support.</span><b>Explore <i class="bi bi-arrow-right"></i></b></a></div></div></section>

    <section class="wd-section wd-faq" aria-labelledby="redesign-faq-title"><div class="wd-container wd-faq-grid"><div class="wd-heading wd-heading-left wd-reveal"><span class="wd-kicker">Frequently asked questions</span><h2 id="redesign-faq-title">Website Redesign FAQs</h2><p>Clear answers for organizations considering a visual refresh, structural redesign or full rebuild.</p><a class="wd-text-link" href="<?= $base ?>/contact-us">Ask about your existing website <i class="bi bi-arrow-right"></i></a></div><div class="wd-accordion wd-reveal"><?php foreach ($faqs as $index => $faq): ?><details<?= $index === 0 ? ' open' : '' ?>><summary><?= cbd_escape_text($faq['q']) ?><i class="bi bi-plus-lg" aria-hidden="true"></i></summary><p><?= cbd_escape_text($faq['a']) ?></p></details><?php endforeach; ?></div></div></section>

    <section class="wd-final-cta"><div class="wd-container wd-reveal"><span class="wd-kicker">Has your website outgrown its original design?</span><h2>Let’s Audit What Should Change Before Rebuilding It.</h2><p>Share your current URL, business goals and known problems. We will help define a practical redesign scope and the next step.</p><div class="wd-actions"><a class="wd-button wd-button-white" href="<?= $base ?>/contact-us"><i class="bi bi-envelope-fill" aria-hidden="true"></i> Request a Website Review</a><a class="wd-button wd-button-outline" href="https://wa.me/919990548795?text=Hi%20Chulbul%20Design%2C%20I%20want%20to%20discuss%20redesigning%20my%20website." target="_blank" rel="noopener noreferrer"><i class="bi bi-whatsapp" aria-hidden="true"></i> Chat on WhatsApp</a></div></div></section>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    var items = document.querySelectorAll('.wd-reveal');
    if (!('IntersectionObserver' in window) || window.matchMedia('(prefers-reduced-motion: reduce)').matches) { items.forEach(function (item) { item.classList.add('is-visible'); }); return; }
    var observer = new IntersectionObserver(function (entries) { entries.forEach(function (entry) { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }); }, { threshold: 0.08, rootMargin: '0px 0px -40px' });
    items.forEach(function (item) { observer.observe(item); });
});
</script>

<?php require __DIR__ . '/includes/footer.php'; ?>
