<?php

/**
 * Editorial source for the Ecommerce Development hub and service pages.
 * The renderer overlays published database values when they are available,
 * while this file keeps every clean URL usable during deployment or recovery.
 */
return [
    'ecommerce-development' => [
        'name' => 'eCommerce Development',
        'meta_title' => 'eCommerce Development Company in India | Chulbul Design',
        'meta_desc' => 'Custom eCommerce development for scalable online stores, B2B commerce and marketplaces using Shopify, WooCommerce, Magento and tailored technology.',
        'focus' => 'eCommerce development company in India',
        'hero_badge' => 'eCommerce Development Services',
        'hero_h1' => 'eCommerce Development for <span>Scalable Online Selling</span>',
        'hero_desc' => 'We plan and build dependable online stores, custom commerce platforms and multi-vendor marketplaces around your products, customers and operations—not around a pre-selected platform.',
        'hero_img' => '/assets/images/service-heroes/ecommerce-development-hero.webp',
        'hero_img_alt' => 'Ecommerce development ecosystem showing storefront, catalogue, checkout, payments, shipping and analytics',
        'browser_label' => 'your-commerce-platform.com',
        'chips' => [['bi-cart-check', 'Buyer-ready journeys'], ['bi-diagram-3', 'Operations connected']],
        'intro_heading' => 'Choose the Right Commerce Model Before Choosing the Technology',
        'intro' => [
            'An eCommerce project is more than a catalogue and a payment button. Customers need to find the right product, understand the offer, trust the business and complete checkout without unnecessary effort. Behind that journey, your team needs reliable inventory, order, shipping, tax, support and reporting workflows. Good eCommerce development connects both sides of the business.',
            'Chulbul Design starts with your catalogue, sales model and operational reality. We look at product complexity, expected order volume, customer groups, payment methods, fulfilment process, content ownership and required integrations. That evidence helps us decide whether Shopify, WooCommerce, Magento, a headless setup or a custom commerce platform is the sensible foundation.',
            'The result is a clearly scoped build with useful milestones, realistic platform constraints and room for measured growth. Our role can cover UX planning, interface design, development, migration, integration, testing and post-launch improvement without pretending that one platform is ideal for every business.'
        ],
        'cards_heading' => 'eCommerce Development Services',
        'cards_subtitle' => 'Select a platform-specific service or start with the broader store and business requirements.',
        'cards' => [
            ['bi-window', 'eCommerce Website Development', 'Catalogue, product, cart and checkout experiences for businesses launching or rebuilding an online store.', '/ecommerce-website-development'],
            ['bi-braces', 'Custom eCommerce Development', 'Purpose-built commerce systems for unusual pricing, B2B workflows, subscriptions and connected operations.', '/custom-ecommerce-development'],
            ['bi-bag-check', 'Shopify Development', 'Custom Shopify storefronts, theme sections, app integrations, migration and performance improvement.', '/shopify-development'],
            ['bi-wordpress', 'WooCommerce Development', 'Flexible WooCommerce stores with tailored product logic, payments, shipping and maintainable WordPress content.', '/woocommerce-development'],
            ['bi-shop', 'Magento Development', 'Magento 2 and Adobe Commerce delivery for large catalogues, customer groups, multi-store and B2B requirements.', '/magento-development'],
            ['bi-people', 'Multi-Vendor Marketplace', 'Buyer, seller and administrator journeys with commissions, catalogue controls, orders and payouts.', '/multi-vendor-marketplace'],
        ],
        'sections' => [
            [
                'h2' => 'A Commerce Architecture That Fits Products, Customers and Operations',
                'para' => "Platform selection should follow the business model. A focused direct-to-consumer catalogue may benefit from a managed platform and a lean app stack. A manufacturer with account pricing, approvals and repeat ordering may need deeper product and customer rules. A marketplace introduces seller onboarding, moderation, commissions and payout responsibilities that do not exist in a standard store.\n\nWe map these requirements before interface production begins. Product types, variants, bundles, subscriptions, customer groups, tax rules, fulfilment locations and integrations are documented as connected decisions. This reduces expensive workarounds later and makes it easier to define what belongs in the first release.",
                'bullets' => ['Catalogue and product-model planning', 'B2C, D2C, B2B and marketplace workflows', 'Platform and hosting recommendation', 'Roadmap for integrations and later releases'],
                'img' => '/assets/images/service-heroes/custom-ecommerce-development-hero.webp',
                'img_alt' => 'Custom ecommerce architecture connecting storefront, business rules, APIs and operational data',
            ],
            [
                'h2' => 'Product Discovery and Checkout Designed as One Customer Journey',
                'para' => "A store can attract relevant traffic and still lose buyers when navigation, filtering, product information or checkout creates uncertainty. We treat category pages, search, filters, comparison, product detail, cart and checkout as one connected decision journey. Mobile behaviour receives particular attention because smaller screens expose weak hierarchy and excessive form effort quickly.\n\nPayment options, shipping expectations, returns information and trust cues are introduced where they help a decision. We avoid decorative urgency and unsupported conversion claims. The objective is a clear, accessible purchasing experience that can be measured and improved after launch.",
                'bullets' => ['Search, navigation, filters and merchandising', 'Product information and variation selection', 'Mobile cart and checkout usability', 'Analytics and meaningful conversion events'],
                'img' => '/assets/images/service-heroes/ecommerce-website-development-hero.webp',
                'img_alt' => 'Responsive ecommerce customer journey across product discovery, cart and secure checkout',
            ],
            [
                'h2' => 'Payments, Shipping, Inventory and Business Systems Working Together',
                'para' => "Store operations become harder when orders must be copied between disconnected tools. Depending on the project, we can integrate documented services for payments, shipping, tax, inventory, CRM, accounting, messaging and analytics. The technical plan covers authentication, webhooks, retries, error visibility and ownership rather than assuming a connector will always work perfectly.\n\nBefore recommending custom integration, we check whether a maintained native option already meets the requirement. This keeps the solution supportable and avoids unnecessary code. Where custom logic is justified, interfaces and failure states are documented so your team understands how information moves through the system.",
                'bullets' => ['Stripe, PayPal, Razorpay and supported gateways', 'Shipping and fulfilment integrations', 'Inventory, ERP, CRM and accounting connections', 'Order notifications and operational reporting'],
                'img' => '/assets/images/built-around-your-requirements.webp',
                'img_alt' => 'Ecommerce integration planning for payments, shipping, inventory and business systems',
            ],
            [
                'h2' => 'Migration, Performance and SEO Planned Before Launch',
                'para' => "Replatforming an existing store requires more than moving products. Customer accounts, orders, categories, product URLs, redirects, metadata, media, analytics and integrations need an agreed migration plan. We identify valuable organic landing pages and business-critical data before the destination store is configured.\n\nPerformance work includes image strategy, code and app review, caching, hosting considerations and Core Web Vitals testing. Launch checks cover responsive behaviour, accessibility, payment scenarios, tax and shipping rules, tracking, indexability and recovery steps. This protects continuity while giving the new platform a cleaner foundation.",
                'bullets' => ['Product, customer and order migration planning', 'SEO URL mapping and permanent redirects', 'Core Web Vitals and mobile performance checks', 'Pre-launch QA with rollback planning'],
                'img' => '/assets/images/page-speed-1.webp',
                'img_alt' => 'Ecommerce migration, technical SEO and website performance validation before launch',
            ],
        ],
        'process_heading' => 'Our eCommerce Development Process',
        'steps' => [
            ['01', 'bi-chat-square-text', 'Discovery', 'Clarify products, customers, sales model, operations, constraints and success criteria.'],
            ['02', 'bi-diagram-3', 'Architecture', 'Map catalogue, journeys, platform, data, integrations and the first useful release.'],
            ['03', 'bi-bezier2', 'UX & Interface', 'Design responsive discovery, product and checkout experiences with realistic content.'],
            ['04', 'bi-code-slash', 'Build & Integrate', 'Develop the approved solution and connect tested operational services.'],
            ['05', 'bi-shield-check', 'QA & Launch', 'Validate transactions, performance, accessibility, tracking and migration before release.'],
        ],
        'faqs' => [
            ['q' => 'Which eCommerce platform should my business use?', 'a' => 'The answer depends on catalogue size, product rules, customer groups, budget, integrations, editing needs and internal technical capacity. Shopify often suits teams wanting managed operations, WooCommerce offers flexible WordPress ownership, Magento supports complex enterprise commerce, and custom development is appropriate when standard platforms cannot model the workflow cleanly.'],
            ['q' => 'Can you redesign or migrate an existing online store?', 'a' => 'Yes. We can audit the current store, plan the destination architecture and migrate agreed products, categories, customers, orders and content. URL mapping, redirects, analytics and integration testing are included in the migration plan so avoidable SEO and operational disruption is reduced.'],
            ['q' => 'Do you integrate payment gateways and shipping providers?', 'a' => 'Yes, when the provider offers suitable documentation and account access. We commonly work with payment, shipping, messaging, CRM, inventory and analytics services. Final compatibility and responsibility are confirmed during discovery.'],
            ['q' => 'How much does eCommerce development cost?', 'a' => 'Cost depends on platform, catalogue complexity, custom design, migration, product rules, integrations, customer roles and testing. We provide a written scope and milestone-based estimate after reviewing these requirements instead of quoting a misleading one-price-fits-all package.'],
            ['q' => 'Will the store be mobile-friendly and SEO-ready?', 'a' => 'Responsive behaviour, semantic content, crawlability, metadata, structured data, performance and analytics are considered during the build. Rankings and conversion outcomes also depend on competition, content, authority, pricing and ongoing marketing, so no responsible agency can guarantee a specific result.'],
        ],
    ],

    'ecommerce-website-development' => [
        'name' => 'eCommerce Website Development',
        'meta_title' => 'eCommerce Website Development Company | Chulbul Design',
        'meta_desc' => 'Conversion-focused eCommerce website development for responsive product catalogues, secure checkout, payments, shipping, analytics and store migration.',
        'focus' => 'eCommerce website development company',
        'hero_badge' => 'Online Store Design & Development',
        'hero_h1' => 'eCommerce Website Development <span>Built Around the Buyer Journey</span>',
        'hero_desc' => 'We create responsive online stores that make products easier to discover, evaluate and buy while giving your team practical control over catalogue, orders and content.',
        'hero_img' => '/assets/images/service-heroes/ecommerce-website-development-hero.webp',
        'hero_img_alt' => 'Responsive ecommerce website showing product catalogue, mobile product page, shopping cart and secure checkout',
        'browser_label' => 'your-online-store.com',
        'chips' => [['bi-phone', 'Mobile-first buying'], ['bi-credit-card', 'Clear checkout']],
        'intro_heading' => 'An Online Store Must Support Confident Decisions and Reliable Fulfilment',
        'intro' => [
            'eCommerce website development combines customer experience with operational detail. The visible store must help people browse categories, compare options, understand products and complete payment. The administrative side must keep product information, stock, orders, shipping and customer communication manageable.',
            'We plan these requirements together. Rather than beginning with a theme demo, we define the catalogue structure, essential page types, customer questions, checkout rules and team responsibilities. This gives design and development a useful foundation and helps prevent a visually attractive store from becoming difficult to operate.',
            'The service is suitable for businesses launching a first serious online store, replacing a limited storefront or consolidating fragmented sales workflows. Platform choice remains open until the scope makes the trade-offs clear.'
        ],
        'cards_heading' => 'What Your eCommerce Website Can Include',
        'cards_subtitle' => 'A practical store foundation covering product discovery, purchase and day-to-day management.',
        'cards' => [
            ['bi-grid', 'Catalogue Architecture', 'Categories, attributes, variants and collections organized around how customers actually shop.', ''],
            ['bi-search', 'Search & Filtering', 'Useful search, filters, sorting and merchandising for faster product discovery.', ''],
            ['bi-card-list', 'Product Page UX', 'Clear product information, media, options, availability, policies and supporting proof.', ''],
            ['bi-cart-check', 'Cart & Checkout', 'Responsive cart and checkout flows with appropriate payment and delivery choices.', ''],
            ['bi-box-seam', 'Orders & Fulfilment', 'Order states, shipping connections, notifications and practical administration.', ''],
            ['bi-graph-up-arrow', 'Analytics & Tracking', 'Documented purchase funnel events for reliable reporting and improvement.', ''],
        ],
        'sections' => [
            ['h2' => 'Catalogue Structure That Helps Customers Find the Right Product', 'para' => "The catalogue is the information architecture of an online store. We define categories, collections, product types, attributes, variations and filters using real inventory rather than placeholder products. This keeps navigation understandable as the range grows and prevents duplicated or inconsistent product paths.\n\nProduct-detail templates are planned around the decision: essential specifications, media, option selection, availability, delivery expectations, returns and relevant supporting content. The structure supports SEO without repeating generic keyword blocks across every category.", 'bullets' => ['Category and collection planning', 'Attributes, variants, bundles and related products', 'Search, filters, sorting and merchandising', 'Reusable product-content standards'], 'img' => '/assets/images/service-heroes/ecommerce-website-development-hero.webp', 'img_alt' => 'Ecommerce catalogue architecture with category navigation, product cards and mobile product details'],
            ['h2' => 'Mobile Checkout With Fewer Surprises', 'para' => "Checkout should collect what is necessary, explain cost changes and provide clear feedback. We review guest checkout, account creation, address entry, delivery selection, coupon behaviour, payment states and order confirmation as one flow. Error messages and recovery paths matter as much as the success screen.\n\nThe mobile version is tested with realistic keyboards, tap targets and form behaviour. Supported wallets and gateways are selected according to the target market and platform. We do not promise a universal conversion uplift; we remove identifiable friction and establish tracking so later decisions can use evidence.", 'bullets' => ['Guest and account checkout decisions', 'Payment, shipping and tax configuration', 'Form validation and failed-payment recovery', 'Purchase and checkout analytics'], 'img' => '/assets/images/page-speed-1.webp', 'img_alt' => 'Mobile ecommerce checkout performance and conversion tracking dashboard'],
            ['h2' => 'Store Administration Your Team Can Use', 'para' => "A store should not require a developer for every product or content update. We configure manageable product fields, order views, promotion rules and content areas, then document the agreed workflow. Permissions can separate catalogue, fulfilment, marketing and administrative responsibilities where the platform supports them.\n\nIntegrations are chosen carefully. A maintained connector may be better than custom code; a custom integration may be justified when the operational rule is genuinely unique. Either way, the scope identifies data ownership, sync direction and what happens when an external service is unavailable.", 'bullets' => ['Product and content editing workflow', 'Roles and operational permissions', 'Promotions, coupons and merchandising controls', 'Inventory, CRM and fulfilment connections'], 'img' => '/assets/images/built-around-your-requirements.webp', 'img_alt' => 'Online store administration workflow for catalogue, orders, promotions and integrations'],
            ['h2' => 'SEO-Safe Store Rebuilds and Migrations', 'para' => "When an existing store is replaced, organic landing pages and business data need deliberate handling. We inventory important URLs, product and category relationships, metadata, media, customer records, orders and tracking before migration. Redirects are mapped to the most relevant destination instead of sending everything to the homepage.\n\nAfter launch, we verify indexability, canonical tags, structured data, analytics events and common transaction paths. Search performance should be monitored over time because crawling, reprocessing and ranking changes do not happen immediately.", 'bullets' => ['Product and category URL inventory', 'Canonical and redirect mapping', 'Data and media migration checks', 'Post-launch crawl and analytics review'], 'img' => '/assets/images/service-heroes/ecommerce-development-hero.webp', 'img_alt' => 'Ecommerce website migration connecting products, customer data, redirects and analytics'],
        ],
        'process_heading' => 'Our eCommerce Website Development Process',
        'steps' => [['01','bi-clipboard-data','Store Discovery','Review catalogue, customers, operations and current platform constraints.'],['02','bi-signpost-split','Journey Planning','Map navigation, product decisions, cart, checkout and administration.'],['03','bi-palette2','Responsive Design','Design key templates with realistic products and mobile behaviour.'],['04','bi-code-slash','Development','Build the store, integrations, content controls and tracking plan.'],['05','bi-check2-circle','Commerce QA','Test products, payments, shipping, emails, performance and launch requirements.']],
        'faqs' => [
            ['q'=>'What is included in eCommerce website development?','a'=>'A typical scope may include catalogue architecture, responsive page templates, product setup rules, cart and checkout, payments, shipping, tax configuration, administration, analytics and launch testing. Migration, ERP connections or unusual product logic are scoped separately when required.'],
            ['q'=>'Can you build an eCommerce website for a small business?','a'=>'Yes. The first release can focus on the catalogue and operations the business needs now while keeping later improvements visible. We avoid loading a smaller store with enterprise complexity that its team cannot maintain.'],
            ['q'=>'Which payment gateways can be integrated?','a'=>'Compatibility depends on the chosen platform, country, currency and merchant account. Stripe, PayPal, Razorpay and other documented gateways can be considered after confirming the business and technical requirements.'],
            ['q'=>'Can you migrate products and customer data from my old store?','a'=>'Yes, subject to source access and data quality. We define exactly which products, variants, customers, orders, media and content will move, then validate representative records before final migration.'],
            ['q'=>'How long does an eCommerce website take to build?','a'=>'A focused catalogue with standard operations can take several weeks. Large catalogues, custom workflows, content preparation and integrations require more time. A realistic schedule is provided after discovery and dependency review.'],
        ],
    ],

    'custom-ecommerce-development' => [
        'name' => 'Custom eCommerce Development',
        'meta_title' => 'Custom eCommerce Development Company | Chulbul Design',
        'meta_desc' => 'Custom eCommerce development for B2B portals, subscriptions, headless storefronts, complex pricing, ERP integration and unique commerce workflows.',
        'focus' => 'custom eCommerce development company',
        'hero_badge' => 'Purpose-Built Commerce Engineering',
        'hero_h1' => 'Custom eCommerce Development for <span>Complex Business Models</span>',
        'hero_desc' => 'When standard plugins cannot express your pricing, customer roles, approvals or operations cleanly, we design a commerce system around the actual rules of your business.',
        'hero_img' => '/assets/images/service-heroes/custom-ecommerce-development-hero.webp',
        'hero_img_alt' => 'Custom ecommerce engineering architecture showing storefront, APIs, database, payments and business rules',
        'browser_label' => 'your-commerce-system.com',
        'chips' => [['bi-braces', 'Custom business rules'], ['bi-plug', 'Systems connected']],
        'intro_heading' => 'Custom Development Is Valuable When the Workflow Is Truly Different',
        'intro' => [
            'Custom eCommerce development should solve a defined limitation, not become a fashionable way to rebuild features a supported platform already provides. It is appropriate when customer groups, contract pricing, approval chains, product configuration, subscriptions, marketplaces or operational integrations create requirements that standard extensions cannot support safely.',
            'We begin by documenting roles, rules, data and exceptions. Buyers, account managers, administrators and operational teams may each need different views and permissions. Pricing can depend on contracts, quantities, geography or product configuration. Orders may require approval, staged payment, fulfilment events or synchronization with an ERP.',
            'That discovery becomes a phased technical plan. The objective is a maintainable commerce product with clear ownership, testable behaviour and an architecture that can evolve without concealing unnecessary complexity.'
        ],
        'cards_heading' => 'Custom Commerce Capabilities',
        'cards_subtitle' => 'Designed for requirements that do not fit a conventional online-store workflow.',
        'cards' => [['bi-building','B2B Commerce','Account pricing, quote requests, approvals, purchase orders and repeat ordering for business buyers.',''],['bi-arrow-repeat','Subscriptions','Recurring products, billing states, entitlement rules and customer self-service.',''],['bi-sliders','Product Configurators','Guided product choices, compatibility rules, calculations and made-to-order workflows.',''],['bi-window-stack','Headless Storefronts','Decoupled frontend experiences connected to commerce services through APIs.',''],['bi-diagram-3','ERP & PIM Integration','Structured exchange of products, stock, customers, orders and fulfilment events.',''],['bi-person-lock','Role-Based Portals','Different catalogue, pricing, content and actions for customers, teams and partners.','']],
        'sections' => [
            ['h2'=>'Requirements and Domain Rules Before Framework Decisions','para'=>"Complex commerce projects fail when assumptions remain hidden until development. We run structured discovery around users, products, pricing, order states, permissions, integrations and exceptions. Important rules are expressed in plain language and converted into acceptance criteria that stakeholders can review.\n\nOnly then do we recommend architecture. A modular Laravel application, API layer, headless frontend or carefully extended platform may each be valid. The choice considers maintainability, hosting, team skills, security and total operational cost—not framework popularity.",'bullets'=>['User roles and permission matrix','Pricing, quotation and approval rules','Product and order state modelling','Acceptance criteria for critical workflows'],'img'=>'/assets/images/built-around-your-requirements.webp','img_alt'=>'Custom ecommerce requirements planning for roles, pricing rules, orders and integrations'],
            ['h2'=>'B2B Portals, Contract Pricing and Assisted Ordering','para'=>"Business buyers often need negotiated catalogues, account-level prices, tax information, purchase orders, quote approval and repeat ordering. These journeys are different from a consumer checkout and should not be hidden behind dozens of fragile plugins. We map buyer and internal-sales responsibilities so each step has a clear owner.\n\nDashboards can expose relevant orders, documents, saved lists and account information without revealing data from other organizations. Audit trails and administrative controls are included where the workflow carries financial or contractual importance.",'bullets'=>['Customer-specific catalogues and pricing','Quotes, approvals and purchase orders','Saved lists and repeat-order workflows','Account dashboards and audit history'],'img'=>'/assets/images/service-heroes/custom-ecommerce-development-hero.webp','img_alt'=>'Custom B2B ecommerce portal with account pricing, approvals and connected order workflows'],
            ['h2'=>'API-First and Headless Commerce Without Unnecessary Complexity','para'=>"A headless architecture can support distinctive storefronts, multiple channels and independent frontend releases, but it also introduces deployment, caching, preview, search and integration responsibilities. We recommend it when those benefits address a real need. Simpler stores may be better served by a well-built conventional platform.\n\nFor API-first systems, contracts, authentication, error handling, rate limits and webhooks are designed explicitly. Monitoring helps the team identify when a dependency fails instead of discovering the problem through customer complaints.",'bullets'=>['REST or GraphQL integration contracts','Authentication and role-aware access','Caching, search and frontend performance','Logging, monitoring and failure recovery'],'img'=>'/assets/images/webapp.webp','img_alt'=>'Headless ecommerce storefront connected to APIs, search, payments and backend services'],
            ['h2'=>'Incremental Delivery for a Business-Critical Platform','para'=>"A custom platform is safer when delivered in reviewable releases. We identify the smallest useful commerce journey, test it with representative data and add complexity in planned increments. Transaction, permission and integration tests focus on the areas where failure would affect customers or operations most.\n\nDeployment includes environment configuration, backups, monitoring and handover documentation. Ongoing support can address security updates, operational issues and prioritized product improvements after real usage begins.",'bullets'=>['Milestone-based product releases','Representative catalogue and transaction testing','Deployment, backups and monitoring','Technical documentation and support planning'],'img'=>'/assets/images/page-speed-1.webp','img_alt'=>'Custom ecommerce deployment monitoring performance, transactions and operational reliability'],
        ],
        'process_heading'=>'Our Custom eCommerce Development Process',
        'steps'=>[['01','bi-people','Workflow Discovery','Interview stakeholders and document users, rules, data and exceptions.'],['02','bi-diagram-3','Solution Architecture','Define boundaries, integrations, security and a phased release plan.'],['03','bi-layout-text-window','Prototype','Validate complex buyer and administrator journeys before full development.'],['04','bi-code-slash','Iterative Build','Develop and demonstrate reviewable modules with representative data.'],['05','bi-shield-check','Release & Support','Test critical behaviour, deploy safely and document ongoing ownership.']],
        'faqs'=>[
            ['q'=>'When should a business choose custom eCommerce development?','a'=>'Choose custom development when validated requirements such as contract pricing, complex configuration, multi-role approvals, unusual subscriptions or deep system integration cannot be supported cleanly by a maintained platform. Standard commerce should remain the first option when it meets the need.'],
            ['q'=>'Can a custom commerce platform integrate with our ERP or CRM?','a'=>'Yes, provided the systems expose suitable APIs, files or middleware access. Discovery identifies data ownership, identifiers, sync frequency, error handling and security before the integration is estimated.'],
            ['q'=>'Do you build headless eCommerce websites?','a'=>'Yes. We can design API-connected storefronts where independent frontend delivery or multiple channels justify the additional architecture. We also explain the operational cost so the decision is made with realistic trade-offs.'],
            ['q'=>'How is custom eCommerce development priced?','a'=>'Pricing depends on roles, business rules, interfaces, integrations, migration, security and release requirements. Discovery is usually needed before a dependable estimate can be tied to milestones.'],
            ['q'=>'Who owns the custom code?','a'=>'Ownership, repositories, third-party licences and handover responsibilities are defined in the proposal and agreement. We recommend that business-critical source code and deployment access remain clearly documented.'],
        ],
    ],

    'shopify-development' => [
        'name'=>'Shopify Development','meta_title'=>'Shopify Development Company in India | Chulbul Design','meta_desc'=>'Custom Shopify development for responsive themes, Shopify 2.0 sections, app integrations, store migration, performance and international selling.','focus'=>'Shopify development company in India','hero_badge'=>'Custom Shopify Development','hero_h1'=>'Shopify Development for <span>Fast, Manageable Online Stores</span>','hero_desc'=>'We design and develop Shopify storefronts with flexible theme sections, clear product journeys, carefully selected apps and a practical setup your team can manage.','hero_img'=>'/assets/images/service-heroes/shopify-development-hero.webp','hero_img_alt'=>'Custom Shopify-style store development showing modular theme sections, product catalogue, apps and mobile checkout','browser_label'=>'your-shopify-store.com','chips'=>[['bi-layout-text-window','Flexible theme sections'],['bi-speedometer2','Lean app stack']],
        'intro_heading'=>'Use Shopify’s Managed Foundation Without Settling for a Generic Store','intro'=>['Shopify can reduce hosting and platform maintenance for teams that want a managed commerce foundation. The quality of the store still depends on catalogue structure, theme implementation, app choices, content and operational configuration. Installing a theme is not the same as building a useful buying experience.','We create custom Shopify storefronts around the brand, product range and customer journey. Online Store 2.0 sections are planned so internal teams can assemble approved layouts without breaking hierarchy. Product templates, collection filters, navigation, cart behaviour and mobile checkout are reviewed with real catalogue examples.','Apps are treated as dependencies with cost, performance and support implications. We prefer native capabilities and maintained integrations, then use custom theme or app development where the requirement genuinely needs it.'],
        'cards_heading'=>'Shopify Development Services','cards_subtitle'=>'From a new storefront to migration and improvement of an established Shopify store.','cards'=>[['bi-palette2','Custom Shopify Theme','Responsive Liquid theme implementation based on approved brand and customer journeys.',''],['bi-grid-1x2','Shopify 2.0 Sections','Reusable sections and blocks that keep day-to-day page editing controlled and flexible.',''],['bi-plug','App Integration','Careful selection and configuration of apps for payments, shipping, reviews and operations.',''],['bi-arrow-left-right','Shopify Migration','Planned migration of products, customers, orders, content and important SEO URLs.',''],['bi-globe2','Shopify Markets','Country, currency, domain, catalogue and content planning for supported international selling.',''],['bi-speedometer2','Shopify Performance','Theme, media, script and app review focused on mobile experience and Core Web Vitals.','']],
        'sections'=>[
            ['h2'=>'Custom Shopify Theme Development With Practical Editing','para'=>"A custom theme should represent the brand without turning every page into a one-off component. We define a reusable visual system and build sections for the content patterns the team will use: merchandising, product education, comparison, proof, editorial content and campaign landing pages.\n\nLiquid templates, section settings and content fields are kept understandable. Guardrails prevent common layout problems while preserving useful flexibility. Responsive states, keyboard interaction and image behaviour are reviewed alongside visual design.",'bullets'=>['Liquid theme and template development','Online Store 2.0 sections and blocks','Responsive and accessible components','Documented theme editing patterns'],'img'=>'/assets/images/service-heroes/shopify-development-hero.webp','img_alt'=>'Shopify theme development with reusable sections, product templates and responsive storefront components'],
            ['h2'=>'Product, Collection and Checkout Journeys','para'=>"Collections, filters and product options should reflect how customers choose rather than the internal spreadsheet alone. We structure product data, navigation and merchandising around those decisions. Product templates explain variants, availability, delivery, returns and supporting details without burying the primary action.\n\nCart drawers, discount behaviour, shipping expectations and supported checkout customizations are scoped within Shopify plan and platform constraints. Where a request is restricted by Shopify, we explain the limitation before promising a workaround.",'bullets'=>['Collection and navigation architecture','Product variants, metafields and media','Cart, discount and shipping behaviour','Checkout options within platform limits'],'img'=>'/assets/images/service-heroes/ecommerce-website-development-hero.webp','img_alt'=>'Shopify product collection, product detail, cart and mobile checkout customer journey'],
            ['h2'=>'Shopify Apps and Integrations Chosen With Restraint','para'=>"Every app can add recurring cost, scripts, data access and maintenance risk. We first check native Shopify capabilities, then compare maintained apps against the requirement. Reviews, subscriptions, search, loyalty, shipping and marketing integrations are configured with attention to customer experience and data flow.\n\nWhen custom integration is necessary, API access, webhooks, rate limits and failure handling are documented. The goal is a store your team can support, not an app stack that becomes difficult to audit.",'bullets'=>['Native capability review before adding apps','Payment, fulfilment and marketing integrations','Webhook and API planning','App cost and performance review'],'img'=>'/assets/images/built-around-your-requirements.webp','img_alt'=>'Shopify app and API integration planning for payments, shipping, reviews and operations'],
            ['h2'=>'Shopify Migration, SEO and Performance','para'=>"Migration includes more than product import. We map products, variants, collections, customers, historical orders, content and media according to the agreed scope. Important source URLs are redirected to relevant destinations, and canonical, metadata and structured-data behaviour are reviewed after launch.\n\nPerformance work focuses on theme code, image delivery, fonts, scripts and app impact. Because Shopify infrastructure is managed, frontend decisions and third-party additions often provide the largest practical opportunities.",'bullets'=>['Product, collection and customer migration','SEO URL and redirect plan','Theme and app performance audit','Analytics and launch verification'],'img'=>'/assets/images/page-speed-1.webp','img_alt'=>'Shopify migration SEO redirects and storefront performance optimization dashboard'],
        ],
        'process_heading'=>'Our Shopify Development Process','steps'=>[['01','bi-bag','Store Discovery','Review catalogue, brand, operations, apps, markets and migration needs.'],['02','bi-signpost-split','Store Architecture','Plan navigation, templates, product data and Shopify capabilities.'],['03','bi-palette2','Theme Design','Design reusable responsive sections with realistic products and content.'],['04','bi-code-slash','Shopify Build','Develop the theme, configure apps, products, settings and tracking.'],['05','bi-check2-circle','Testing & Launch','Test devices, products, payments, redirects, analytics and team handover.']],
        'faqs'=>[['q'=>'Do you build custom Shopify themes?','a'=>'Yes. We can implement a custom Liquid theme and reusable Online Store 2.0 sections based on approved designs, content patterns and responsive requirements.'],['q'=>'Can you migrate WooCommerce or Magento to Shopify?','a'=>'Yes. The migration scope can cover products, variants, collections, customers, orders, content and redirects. Data quality and Shopify feature differences are reviewed before the final plan.'],['q'=>'Can you improve an existing Shopify store?','a'=>'Yes. An audit can cover navigation, product templates, theme code, mobile usability, app impact, tracking and Core Web Vitals, followed by a prioritized improvement plan.'],['q'=>'Do you develop private Shopify apps?','a'=>'Custom app or integration development can be considered when maintained public apps and native capabilities do not meet a validated requirement. API scope and ongoing ownership are confirmed first.'],['q'=>'How much does Shopify development cost?','a'=>'Cost depends on theme complexity, templates, product setup, content, apps, integrations and migration. After discovery, we provide a written scope tied to deliverables.']],
    ],

    'woocommerce-development' => [
        'name'=>'WooCommerce Development','meta_title'=>'WooCommerce Development Company | Chulbul Design','meta_desc'=>'Custom WooCommerce development for themes, product rules, plugins, payments, shipping, store migration, security and performance optimization.','focus'=>'WooCommerce development company','hero_badge'=>'Custom WooCommerce Development','hero_h1'=>'WooCommerce Development for <span>Flexible, Owned Online Stores</span>','hero_desc'=>'We build and improve WooCommerce stores with maintainable WordPress content, tailored product logic, carefully controlled plugins and dependable commerce workflows.','hero_img'=>'/assets/images/service-heroes/woocommerce-development-hero.webp','hero_img_alt'=>'Custom WooCommerce store development showing products, plugins, payments, shipping and performance controls','browser_label'=>'your-woocommerce-store.com','chips'=>[['bi-wordpress','Content and commerce'],['bi-shield-check','Controlled extensions']],
        'intro_heading'=>'WooCommerce Works Best When Flexibility Is Managed Carefully','intro'=>['WooCommerce combines WordPress content management with a flexible commerce ecosystem. It can support focused product catalogues, content-led brands, subscriptions and tailored workflows. That flexibility also means theme, plugin, hosting and maintenance decisions have a direct effect on performance and reliability.','We design WooCommerce stores around product data, customer journeys and operational needs before selecting extensions. Custom code is used where it creates a maintainable advantage; supported plugins are used where they already solve the requirement responsibly. This balance keeps the store adaptable without accumulating unnecessary dependencies.','The service covers new stores, redesigns, migrations, custom functionality, integrations and technical improvement of existing WooCommerce websites.'],
        'cards_heading'=>'WooCommerce Development Services','cards_subtitle'=>'A complete WordPress commerce foundation with practical control over content and operations.','cards'=>[['bi-palette2','Custom WooCommerce Theme','Responsive templates for collections, products, cart, account and content-led journeys.',''],['bi-sliders','Product Logic','Variations, bundles, subscriptions, pricing and catalogue behaviour configured around the offer.',''],['bi-plugin','Plugin Development','Custom extensions or integrations when a maintained standard plugin cannot meet the need.',''],['bi-credit-card','Payments & Shipping','Gateway, tax, delivery and fulfilment configuration for supported markets.',''],['bi-arrow-left-right','Store Migration','Structured migration from another platform or an ageing WooCommerce installation.',''],['bi-speedometer2','Speed & Security','Hosting, caching, database, plugin and security review for a healthier store.','']],
        'sections'=>[
            ['h2'=>'WooCommerce Theme and Product Architecture','para'=>"We define product types, categories, attributes and reusable content before theme development. Templates support the information customers need for selection while keeping editing practical for the internal team. Content pages, guides and product collections can work together without creating duplicate navigation.\n\nTheme development uses WordPress and WooCommerce conventions where they improve compatibility. Responsive components, account areas, cart states and important plugin output are tested rather than assuming a desktop product template will adapt automatically.",'bullets'=>['Custom product and collection templates','Variation, attribute and bundle planning','Content-led product discovery','Responsive account, cart and checkout states'],'img'=>'/assets/images/service-heroes/woocommerce-development-hero.webp','img_alt'=>'WooCommerce theme and catalogue architecture with products, content modules and responsive checkout'],
            ['h2'=>'Plugins and Custom Functionality Without Extension Sprawl','para'=>"Plugins can shorten delivery, but overlapping extensions create update conflicts and performance problems. We review the requirement, maintenance history, support model and data access before adding a dependency. Existing stores can be audited to identify abandoned or duplicated plugins.\n\nCustom WooCommerce development is reserved for workflows that need it: product configuration, pricing, fulfilment, membership, account behaviour or external system integration. Code is kept in an appropriate custom plugin or theme layer so future updates are easier to reason about.",'bullets'=>['Plugin and dependency audit','Custom WooCommerce extension development','Hooks, checkout and account customization','Update and rollback planning'],'img'=>'/assets/images/built-around-your-requirements.webp','img_alt'=>'WooCommerce plugin architecture and custom functionality planning around business requirements'],
            ['h2'=>'Payments, Shipping, Tax and Operational Integration','para'=>"Gateway and shipping configuration is tested with the actual currency, delivery rules and merchant account. Taxes, coupons, order emails and status changes are reviewed together because a small configuration error can create customer-service and accounting work.\n\nWooCommerce can connect with inventory, fulfilment, CRM, accounting and messaging services through maintained connectors or APIs. The integration plan states which system owns each data field and how failures will be detected.",'bullets'=>['Supported payment gateway configuration','Shipping zones, methods and fulfilment rules','Tax, coupon and order-status testing','CRM, ERP and analytics connections'],'img'=>'/assets/images/service-heroes/ecommerce-development-hero.webp','img_alt'=>'WooCommerce operations connecting payments, tax, shipping, inventory and analytics'],
            ['h2'=>'WooCommerce Performance, Security and Migration','para'=>"Performance depends on hosting, database health, theme code, images, plugins and third-party scripts. We measure representative pages and prioritize improvements that affect real customer journeys. Security work includes maintained software, least-privilege access, backups, monitoring and appropriate protection at the hosting layer.\n\nMigration planning covers catalogue, accounts, orders, content, URLs and integrations. Launch is followed by transaction, crawl and analytics checks rather than treating deployment as the final step.",'bullets'=>['Core Web Vitals and database review','Plugin, script and image optimization','Backup, access and update controls','SEO-safe migration and launch checks'],'img'=>'/assets/images/page-speed-1.webp','img_alt'=>'WooCommerce performance security and migration validation for a responsive online store'],
        ],
        'process_heading'=>'Our WooCommerce Development Process','steps'=>[['01','bi-clipboard-data','Requirements Audit','Review catalogue, content, plugins, hosting, operations and migration scope.'],['02','bi-diagram-3','Store Plan','Define WordPress architecture, product data, extensions and integrations.'],['03','bi-palette2','UX & Theme','Design responsive store templates and manageable content components.'],['04','bi-code-slash','Build & Configure','Develop the theme, functionality, payments, shipping and tracking.'],['05','bi-shield-check','QA & Handover','Test transactions, updates, performance, security and team workflows.']],
        'faqs'=>[['q'=>'Why choose WooCommerce for an online store?','a'=>'WooCommerce is useful when a business values WordPress content flexibility, broad hosting choice and customizable product workflows. The trade-off is greater responsibility for hosting, updates, plugins, performance and security.'],['q'=>'Can you build a custom WooCommerce theme?','a'=>'Yes. We can develop responsive WooCommerce and WordPress templates around approved design and content requirements without relying on a generic visual theme.'],['q'=>'Can you fix a slow WooCommerce website?','a'=>'Yes. We first measure hosting, database, theme, image, plugin and script impact, then prioritize changes. The achievable result depends on the stack and third-party services, so a fixed score is not promised before testing.'],['q'=>'Do you develop custom WooCommerce plugins?','a'=>'Yes, where a validated business rule cannot be supported safely by an existing maintained extension. The plugin scope, update compatibility and ownership are documented.'],['q'=>'Can you migrate Shopify to WooCommerce?','a'=>'Yes. Products, customers, orders, content, media, URLs and integrations can be mapped according to an agreed migration scope and validated before launch.']],
    ],

    'magento-development' => [
        'name'=>'Magento Development','meta_title'=>'Magento Development Company in India | Chulbul Design','meta_desc'=>'Magento 2 and Adobe Commerce development for large catalogues, B2B pricing, multi-store operations, ERP integration, migration and performance.','focus'=>'Magento development company in India','hero_badge'=>'Magento 2 & Adobe Commerce','hero_h1'=>'Magento Development for <span>Complex, High-Scale Commerce</span>','hero_desc'=>'We plan Magento 2 and Adobe Commerce solutions for large catalogues, B2B customer groups, multiple storefronts and connected enterprise operations.','hero_img'=>'/assets/images/service-heroes/magento-development-hero.webp','hero_img_alt'=>'Enterprise Magento commerce platform showing large catalogue, customer groups, inventory, ERP and performance monitoring','browser_label'=>'your-enterprise-store.com','chips'=>[['bi-boxes','Large catalogue ready'],['bi-building','B2B workflows']],
        'intro_heading'=>'Magento Is an Enterprise Decision, Not Simply a Larger Store Theme','intro'=>['Magento 2 and Adobe Commerce are suited to organizations that need substantial catalogue control, customer-specific pricing, multi-store operations, complex promotions or deep enterprise integration. They also demand disciplined architecture, infrastructure and ongoing maintenance. Choosing Magento without those requirements can create avoidable cost.','We evaluate catalogue size, traffic patterns, customer groups, fulfilment, content, integrations, internal ownership and release process before recommending the platform. For a suitable project, Magento provides a strong foundation for sophisticated commerce rules and multiple business models.','Our work can cover discovery, UX, theme implementation, module development, migration, integration, performance and support with an emphasis on upgrade-compatible decisions.'],
        'cards_heading'=>'Magento Development Services','cards_subtitle'=>'Enterprise commerce capabilities planned for maintainability, scale and operational control.','cards'=>[['bi-palette2','Magento Theme Development','Responsive storefront implementation using maintainable Magento frontend conventions.',''],['bi-boxes','Catalogue Architecture','Attributes, product types, categories and indexing planned for large or complex ranges.',''],['bi-building','B2B Commerce','Company accounts, shared catalogues, quotes, approval and negotiated pricing workflows.',''],['bi-shop-window','Multi-Store Setup','Websites, stores and views organized for brands, markets, languages and catalogues.',''],['bi-plug','ERP & PIM Integration','Product, inventory, customer, order and fulfilment exchange with enterprise systems.',''],['bi-speedometer2','Performance & Upgrade','Caching, indexing, infrastructure, code audit and version-upgrade planning.','']],
        'sections'=>[
            ['h2'=>'Magento Catalogue and Store Architecture','para'=>"Large catalogues need a consistent attribute model, product types, category hierarchy and indexing strategy. We work with representative products and operational stakeholders to define the structure before bulk import. This helps search, filtering, merchandising, feeds and integrations use the same product meaning.\n\nMulti-store architecture separates websites, stores and store views only where business rules require it. Currency, language, catalogue, pricing and customer differences are documented so configuration does not become an accidental maze.",'bullets'=>['Attributes, product types and category model','Search, layered navigation and indexing','Websites, stores and store-view planning','Import and catalogue-governance workflow'],'img'=>'/assets/images/service-heroes/magento-development-hero.webp','img_alt'=>'Magento catalogue and multi-store architecture for enterprise ecommerce operations'],
            ['h2'=>'Adobe Commerce and Magento B2B Workflows','para'=>"B2B buyers may need company accounts, user roles, shared catalogues, negotiated prices, quotes, requisition lists and purchase-order approval. These features should be configured around the organization’s actual sales process rather than enabled as isolated modules.\n\nWe map the relationship between buyer, account manager, finance and fulfilment teams. Permissions, price sources and order states are tested with realistic accounts so customer-specific information remains correctly separated.",'bullets'=>['Company accounts and buyer roles','Shared catalogues and contract pricing','Quotes, requisition lists and approvals','Account-specific order and document access'],'img'=>'/assets/images/built-around-your-requirements.webp','img_alt'=>'Magento B2B commerce workflow for company accounts, negotiated pricing, quotes and approvals'],
            ['h2'=>'Magento Extensions and Enterprise Integrations','para'=>"ERP, PIM, warehouse, CRM, tax, payment and shipping integrations often determine whether the commerce operation succeeds. We define identifiers, ownership, sync direction, frequency, queues and error handling before development. Asynchronous processing is considered for workflows that should not block the customer experience.\n\nThird-party extensions are assessed for support, compatibility and upgrade impact. Custom modules follow Magento conventions and are documented to reduce surprises during future platform updates.",'bullets'=>['ERP, PIM, WMS and CRM integration','Queues, webhooks and scheduled synchronization','Extension compatibility review','Documented custom Magento modules'],'img'=>'/assets/images/webapp.webp','img_alt'=>'Magento enterprise integration connecting ERP PIM warehouse payments and customer systems'],
            ['h2'=>'Magento Migration, Performance and Ongoing Support','para'=>"Magento migrations include product, customer, order, content and configuration mapping as well as extension replacement and SEO continuity. A rehearsal with representative data helps expose transformation and timing issues before the production cutover.\n\nPerformance work covers application code, indexing, caching, media, database and infrastructure. Monitoring and a release process are essential because an enterprise store continues to change after launch. Support scope can include upgrades, security patches, incident response and planned enhancements.",'bullets'=>['Magento 1 or platform migration planning','Caching, indexing and infrastructure review','SEO redirects and data validation','Security updates and release management'],'img'=>'/assets/images/page-speed-1.webp','img_alt'=>'Magento migration performance monitoring indexing and enterprise release management'],
        ],
        'process_heading'=>'Our Magento Development Process','steps'=>[['01','bi-clipboard-data','Enterprise Discovery','Review catalogue, business units, B2B rules, systems and ownership.'],['02','bi-diagram-3','Solution Architecture','Plan Magento structure, integrations, infrastructure and release phases.'],['03','bi-layout-text-window','UX & Theme','Design responsive storefront and account journeys for real catalogue needs.'],['04','bi-code-slash','Build & Integrate','Configure Magento and develop tested modules and system connections.'],['05','bi-rocket-takeoff','Migration & Release','Rehearse data migration, validate performance and manage production launch.']],
        'faqs'=>[['q'=>'When should a business choose Magento 2 or Adobe Commerce?','a'=>'Magento is most appropriate for substantial catalogues, B2B requirements, multi-store operations, complex promotions or enterprise integration. A simpler platform may offer lower ownership cost when those capabilities are not needed.'],['q'=>'Do you provide Magento 2 custom development?','a'=>'Yes. Work can include themes, modules, B2B configuration, integrations, data migration, performance and ongoing support based on a documented scope.'],['q'=>'Can you migrate Magento 1 to Magento 2?','a'=>'Yes. The project requires data mapping, extension and theme replacement, integration review, SEO redirects, rehearsal and launch planning because it is a platform rebuild rather than a direct version update.'],['q'=>'Can Magento integrate with ERP and PIM systems?','a'=>'Yes, when suitable interfaces are available. The integration design defines product and inventory ownership, identifiers, sync timing, queues, retries and operational visibility.'],['q'=>'How much does Magento development cost?','a'=>'Cost varies significantly with edition, catalogue, B2B features, storefronts, migration, integrations, infrastructure and support. Discovery is required before a dependable estimate can be provided.']],
    ],

    'multi-vendor-marketplace' => [
        'name'=>'Multi-Vendor Marketplace','meta_title'=>'Multi-Vendor Marketplace Development | Chulbul Design','meta_desc'=>'Custom multi-vendor marketplace development with seller onboarding, catalogue approval, commissions, split payouts, orders and marketplace administration.','focus'=>'multi-vendor marketplace development company','hero_badge'=>'Marketplace Website Development','hero_h1'=>'Multi-Vendor Marketplace Development for <span>Buyers, Sellers and Operations</span>','hero_desc'=>'We design marketplace platforms around three connected experiences: confident buying, manageable selling and responsible administration of catalogue, orders, commissions and payouts.','hero_img'=>'/assets/images/service-heroes/multi-vendor-marketplace-hero.webp','hero_img_alt'=>'Multi-vendor marketplace showing buyer storefront, seller shops, vendor dashboard, commissions, payouts and order flow','browser_label'=>'your-marketplace.com','chips'=>[['bi-shop','Seller-ready tools'],['bi-cash-coin','Commission controls']],
        'intro_heading'=>'A Marketplace Is a Multi-Sided Operating Model, Not a Store With Extra Accounts','intro'=>['Multi-vendor marketplace development introduces responsibilities that a single-seller store does not have. Sellers need onboarding, catalogue tools, order visibility and payout information. Buyers need consistent product information, trust, support and clear responsibility. The marketplace operator needs moderation, commissions, disputes, reporting and risk controls.','We define these relationships before selecting technology. The commercial model—commission, subscription, listing fee, lead fee or a combination—affects registration, transactions and reporting. Product marketplaces, service marketplaces and B2B exchanges also require different discovery and fulfilment journeys.','A phased release usually begins with the smallest end-to-end transaction that proves the operating model. Additional seller automation, promotions, mobile applications and advanced reporting can follow evidence from real usage.'],
        'cards_heading'=>'Marketplace Platform Capabilities','cards_subtitle'=>'Connected tools for sellers, buyers and the team responsible for operating the platform.','cards'=>[['bi-person-plus','Seller Onboarding','Applications, verification steps, agreements and approval states matched to marketplace risk.',''],['bi-card-list','Catalogue Moderation','Seller product creation with structured data, review queues and publishing controls.',''],['bi-percent','Commissions','Category, seller or order-level commission rules with clear transaction records.',''],['bi-wallet2','Payouts','Payout eligibility, schedules, adjustments and reconciliation with supported providers.',''],['bi-box-seam','Orders & Returns','Seller fulfilment, buyer communication, cancellations, returns and dispute ownership.',''],['bi-speedometer2','Admin Operations','Dashboards for users, listings, orders, commissions, support and marketplace health.','']],
        'sections'=>[
            ['h2'=>'Seller Onboarding and Catalogue Governance','para'=>"Seller growth is valuable only when the marketplace can maintain trust and consistent information. We map application fields, verification, agreements, approval, suspension and offboarding. The process should collect what the operator genuinely needs without creating unnecessary abandonment.\n\nCatalogue tools define categories, required attributes, media, variants and moderation states. Operators can review changes and enforce standards, while sellers receive understandable feedback. The design depends on whether sellers offer products, services, bookings or business quotations.",'bullets'=>['Seller registration and verification workflow','Agreements, approval and account states','Structured listing and product fields','Moderation queues and catalogue standards'],'img'=>'/assets/images/service-heroes/multi-vendor-marketplace-hero.webp','img_alt'=>'Seller onboarding and catalogue moderation workflow for a multi-vendor marketplace'],
            ['h2'=>'Buyer Discovery, Trust and Multi-Seller Orders','para'=>"Marketplace search and navigation must handle inconsistent seller inventory while presenting a coherent customer experience. Filters, seller profiles, availability, delivery, ratings and policies are positioned according to the buying decision. Reviews require moderation and eligibility rules if they are expected to support trust.\n\nA cart may contain products from several sellers, creating separate fulfilment, shipping, cancellation and return states. We document how those states appear to buyers, sellers and support teams before checkout implementation.",'bullets'=>['Marketplace search, filters and seller pages','Review and trust-signal rules','Multi-seller cart and order splitting','Returns, cancellations and buyer support'],'img'=>'/assets/images/service-heroes/ecommerce-website-development-hero.webp','img_alt'=>'Marketplace buyer journey with product discovery seller information cart and checkout'],
            ['h2'=>'Commissions, Payments and Seller Payouts','para'=>"Marketplace money movement requires more than displaying a commission percentage. The model must define when commission is earned, which fees and taxes apply, when a seller becomes eligible for payout, how refunds affect balances and how adjustments are recorded. Legal and tax advice remains the operator’s responsibility.\n\nWe integrate supported marketplace or split-payment providers where available and design a clear ledger of orders, commissions, refunds and payouts. Provider onboarding, KYC and regional restrictions are confirmed early because they can determine the feasible payment architecture.",'bullets'=>['Commission and fee rules','Split-payment provider assessment','Seller balances and payout schedules','Refund, adjustment and reconciliation records'],'img'=>'/assets/images/built-around-your-requirements.webp','img_alt'=>'Marketplace commission split payment seller balance and payout architecture'],
            ['h2'=>'Marketplace Administration, Safety and Scale','para'=>"Operators need a consolidated view of users, sellers, listings, orders, support and financial events. Role-based administration separates daily operations from sensitive settings. Audit history is valuable for moderation and money-related changes.\n\nScale planning focuses on measurable bottlenecks such as search, catalogue imports, media, notifications and reporting. Monitoring, backups and incident procedures are part of responsible operation. Security and privacy controls are scoped according to the data and markets involved rather than described through generic badges.",'bullets'=>['Role-based operator dashboard','Moderation and support workflows','Audit logs and operational reporting','Monitoring, backups and security planning'],'img'=>'/assets/images/page-speed-1.webp','img_alt'=>'Marketplace administration dashboard monitoring catalogue orders commissions and platform performance'],
        ],
        'process_heading'=>'Our Marketplace Development Process','steps'=>[['01','bi-people','Model Discovery','Define users, commercial model, catalogue, fulfilment and operator responsibility.'],['02','bi-diagram-3','Workflow Architecture','Map seller, buyer, admin, money and exception journeys end to end.'],['03','bi-layout-text-window','Marketplace UX','Prototype core onboarding, discovery, order and dashboard experiences.'],['04','bi-code-slash','Phased Development','Build the smallest complete marketplace transaction and expand in releases.'],['05','bi-shield-check','Operational Launch','Test roles, money states, moderation, support, monitoring and handover.']],
        'faqs'=>[['q'=>'What is included in multi-vendor marketplace development?','a'=>'A marketplace may include seller onboarding, profiles, listings, catalogue moderation, buyer search, orders, commissions, payouts, reviews, disputes and operator dashboards. The exact scope depends on whether it handles products, services, bookings or leads.'],['q'=>'Can sellers manage their own products and orders?','a'=>'Yes. Seller permissions can cover approved catalogue actions, stock, pricing, fulfilment and reports. Operator review and policy controls are defined according to the marketplace model.'],['q'=>'How do marketplace commissions and payouts work?','a'=>'The platform records agreed fees against transactions and determines payout eligibility based on order, delivery, return and dispute states. Actual split-payment capability depends on provider, country, KYC and merchant-account rules.'],['q'=>'Can you build marketplace mobile apps?','a'=>'Yes, but a responsive web platform is often the most efficient first release. Native or cross-platform apps can follow when usage patterns and operational readiness justify them.'],['q'=>'How much does a multi-vendor marketplace cost?','a'=>'Cost depends on user roles, catalogue model, commissions, payment architecture, fulfilment, messaging, moderation, reporting, integrations and mobile applications. Discovery is necessary before a responsible estimate.']],
    ],
];
