<?php

/**
 * Page-specific content for the shared service-page design components.
 * These blocks mirror the established six-page service system without
 * repeating platform-neutral copy across every ecommerce URL.
 */
return [
    'ecommerce-development' => [
        'solutions_kicker' => 'Commerce models need different architecture',
        'solutions_heading' => 'eCommerce Solutions for Different Ways of Selling',
        'solutions_intro' => 'Products, customers, pricing and fulfilment determine the right platform and release plan.',
        'solutions' => [
            ['bi-bag', 'Direct-to-Consumer Stores', 'Brand-led storefronts connecting product discovery, education, checkout and repeat purchase.'],
            ['bi-building', 'B2B Commerce', 'Account pricing, buyer roles, quotations, approvals and repeat-order workflows for business customers.'],
            ['bi-arrow-repeat', 'Subscriptions & Memberships', 'Recurring products or access models with clear billing, account and cancellation journeys.'],
            ['bi-globe2', 'International Commerce', 'Markets, currencies, languages, taxes and fulfilment responsibilities planned before expansion.'],
            ['bi-box-arrow-in-right', 'Store Migration', 'Products, customers, orders, content and valuable URLs moved through a controlled launch plan.'],
            ['bi-people', 'Multi-Vendor Marketplaces', 'Connected buyer, seller and operator experiences for listings, orders, commissions and payouts.'],
        ],
        'foundation_kicker' => 'A complete commerce foundation',
        'foundation_heading' => 'Storefront, Operations and Measurement Working Together',
        'foundation_intro' => 'A dependable commerce system supports the buying journey and the people responsible for delivering every order.',
        'foundations' => [
            ['01 / Experience', 'A clear path from discovery to checkout', 'Navigation, search, product information and checkout help customers make informed purchase decisions.', ['Catalogue', 'Search', 'Product UX', 'Checkout']],
            ['02 / Operations', 'Workflows the team can manage', 'Inventory, orders, shipping, returns and customer communication remain visible and responsibly owned.', ['Inventory', 'Orders', 'Shipping', 'Returns']],
            ['03 / Growth', 'Evidence for the next improvement', 'SEO foundations, analytics and meaningful events support decisions after real customers begin using the store.', ['SEO', 'Analytics', 'Events', 'Iteration']],
        ],
        'integration_core' => ['bi-cart3', 'Commerce'],
        'integration_nodes' => [['bi-credit-card', 'Payments'], ['bi-boxes', 'Inventory'], ['bi-truck', 'Shipping'], ['bi-bar-chart', 'Analytics']],
        'quality_kicker' => 'Quality across the transaction',
        'quality_heading' => 'Usability, Reliability, Performance and Visibility',
        'quality_intro' => 'The store must remain understandable for customers and dependable for the team operating it.',
        'quality' => [
            ['bi-hand-index', 'Usability', 'Responsive discovery, product and checkout journeys reduce avoidable customer effort.'],
            ['bi-shield-check', 'Reliability', 'Documented states and error handling protect orders when a connected service fails.'],
            ['bi-lightning-charge', 'Performance', 'Responsible media, code and platform choices keep useful content responsive.'],
            ['bi-search', 'Search Visibility', 'Crawlable architecture, metadata and migration planning support organic discovery.'],
        ],
        'why_heading' => 'Commerce Strategy and Engineering in One Accountable Team',
        'why_paragraphs' => [
            'An eCommerce project crosses customer experience, content, technology and operations. We keep those decisions connected so a visually polished storefront does not create avoidable work for fulfilment, support or marketing teams.',
            'Chulbul Design works from Gurugram with businesses in India and international markets through planned remote collaboration. Platform recommendations, dependencies, milestones and responsibilities are documented before development commitments are made.',
        ],
        'reasons' => [
            ['bi-compass', 'Requirement-led advice', 'The business model guides the platform—not a preferred sales partnership.'],
            ['bi-diagram-3', 'End-to-end thinking', 'Customer, data and operational journeys are mapped as one system.'],
            ['bi-code-slash', 'Design-to-build continuity', 'Approved UX decisions remain connected to technical implementation.'],
            ['bi-journal-check', 'Clear ownership', 'Integrations, content, testing and handover responsibilities are documented.'],
        ],
    ],

    'ecommerce-website-development' => [
        'solutions_kicker' => 'Stores shaped around the buying decision',
        'solutions_heading' => 'Online Stores for Different Products and Customer Journeys',
        'solutions_intro' => 'Catalogue depth, purchase frequency and fulfilment change what an ecommerce website needs to explain.',
        'solutions' => [
            ['bi-rocket-takeoff', 'New Online Stores', 'A practical first release with structured products, payments, shipping and clear administration.'],
            ['bi-grid', 'Large Product Catalogues', 'Categories, attributes, filters and search designed for ranges customers need to compare.'],
            ['bi-phone', 'Mobile-First Retail', 'Compact discovery and checkout journeys planned for customers purchasing on smaller screens.'],
            ['bi-shop-window', 'Omnichannel Businesses', 'Store, inventory and fulfilment decisions aligned with existing retail or distribution operations.'],
            ['bi-calendar-check', 'Repeat & Subscription Sales', 'Account, reorder and recurring-purchase journeys that make ongoing relationships manageable.'],
            ['bi-arrow-left-right', 'Store Redesign & Migration', 'Existing products, customers, analytics and search URLs protected during a controlled rebuild.'],
        ],
        'foundation_kicker' => 'A buyer-ready store foundation',
        'foundation_heading' => 'Catalogue, Checkout and Administration Working Together',
        'foundation_intro' => 'Customers see the storefront, but long-term store quality also depends on the tools behind it.',
        'foundations' => [
            ['01 / Discover', 'Products customers can find', 'Clear categories, search, filters and merchandising connect different shopping behaviours to the right products.', ['Categories', 'Filters', 'Search', 'Merchandising']],
            ['02 / Decide', 'Information customers can trust', 'Product media, options, delivery and policy information answer practical questions before checkout.', ['Product Data', 'Media', 'Delivery', 'Policies']],
            ['03 / Deliver', 'Orders the team can fulfil', 'Administration, inventory, notifications and reporting support the work that begins after payment.', ['Admin', 'Inventory', 'Orders', 'Reporting']],
        ],
        'integration_core' => ['bi-shop', 'Store'],
        'integration_nodes' => [['bi-credit-card', 'Payment'], ['bi-truck', 'Delivery'], ['bi-box-seam', 'Orders'], ['bi-graph-up', 'Tracking']],
        'quality_kicker' => 'Quality throughout the store',
        'quality_heading' => 'Clarity, Accessibility, Speed and Transaction Confidence',
        'quality_intro' => 'A complete online store must work beyond the ideal desktop purchase demonstration.',
        'quality' => [
            ['bi-signpost-split', 'Clarity', 'Customers can understand categories, product options, cost and the next action.'],
            ['bi-universal-access', 'Accessibility', 'Labels, focus, structure and keyboard behaviour support a wider range of shoppers.'],
            ['bi-lightning-charge', 'Speed', 'Image, code and application decisions protect mobile product and checkout performance.'],
            ['bi-credit-card-2-front', 'Transaction Confidence', 'Payment, delivery and error states explain what happened and what comes next.'],
        ],
        'why_heading' => 'A Store Designed for Customers and the Team Running It',
        'why_paragraphs' => [
            'We evaluate the public buying experience and the day-to-day administration together. Product editing, order handling, promotions and reporting are part of the scope conversation—not problems left for the team after launch.',
            'Our Gurugram-based team collaborates remotely with businesses across markets using agreed milestones and review points. We explain platform limits, third-party costs and migration dependencies before they become launch surprises.',
        ],
        'reasons' => [
            ['bi-person-check', 'Buyer-led structure', 'Real product questions shape navigation, templates and checkout.'],
            ['bi-window-sidebar', 'Manageable administration', 'Content and operational controls reflect the team’s actual responsibilities.'],
            ['bi-phone', 'Mobile purchase thinking', 'Small-screen discovery, forms and checkout are planned from the start.'],
            ['bi-clipboard-check', 'Commerce-specific QA', 'Products, payments, shipping, emails and tracking are tested together.'],
        ],
    ],

    'custom-ecommerce-development' => [
        'solutions_kicker' => 'When standard store logic is not enough',
        'solutions_heading' => 'Custom Commerce for Complex Products and Business Rules',
        'solutions_intro' => 'Purpose-built development is useful when the workflow—not visual preference—cannot be modelled responsibly by a standard setup.',
        'solutions' => [
            ['bi-building', 'B2B Ordering Portals', 'Account catalogues, negotiated prices, quotations, approvals and repeat ordering.'],
            ['bi-sliders', 'Product Configurators', 'Guided options, compatibility rules and pricing for configurable or made-to-order products.'],
            ['bi-arrow-repeat', 'Subscription Platforms', 'Recurring billing, plans, entitlements, upgrades and customer account management.'],
            ['bi-braces', 'Headless Storefronts', 'Independent frontend delivery connected to commerce and content services through documented APIs.'],
            ['bi-diagram-3', 'Operational Automation', 'Orders and customer data connected with ERP, CRM, fulfilment and finance workflows.'],
            ['bi-layers', 'Multi-Channel Commerce', 'Shared product and transaction logic supporting several storefronts or customer channels.'],
        ],
        'foundation_kicker' => 'A maintainable custom foundation',
        'foundation_heading' => 'Business Rules, Interfaces and Data Boundaries',
        'foundation_intro' => 'Custom code creates value only when the underlying responsibilities remain understandable and testable.',
        'foundations' => [
            ['01 / Domain', 'Rules expressed clearly', 'Products, pricing, eligibility, roles and order states are documented in business language before code.', ['Products', 'Pricing', 'Roles', 'States']],
            ['02 / Interface', 'Journeys matched to each role', 'Buyer, account, sales and operations users receive the information and controls their tasks require.', ['Buyer UX', 'Accounts', 'Admin', 'Accessibility']],
            ['03 / Integration', 'Systems connected responsibly', 'APIs, events, ownership and failure recovery are planned around operational consequences.', ['APIs', 'Events', 'Retries', 'Audit']],
        ],
        'integration_core' => ['bi-braces', 'Custom'],
        'integration_nodes' => [['bi-boxes', 'ERP'], ['bi-people', 'CRM'], ['bi-database', 'PIM'], ['bi-receipt', 'Finance']],
        'quality_kicker' => 'Quality for business-critical software',
        'quality_heading' => 'Maintainability, Security, Reliability and Observability',
        'quality_intro' => 'Custom commerce should make unique workflows possible without becoming an undocumented dependency.',
        'quality' => [
            ['bi-diagram-2', 'Maintainability', 'Separated responsibilities and documented interfaces make future change safer.'],
            ['bi-shield-lock', 'Security', 'Roles, validation, access and sensitive operations receive explicit technical review.'],
            ['bi-arrow-clockwise', 'Reliability', 'Retries, idempotency and failure states protect connected transactions.'],
            ['bi-activity', 'Observability', 'Logs, alerts and meaningful events help teams understand production behaviour.'],
        ],
        'why_heading' => 'Custom Development With a Clear Business Reason',
        'why_paragraphs' => [
            'We do not recommend custom code simply to make a project sound sophisticated. Existing platform capabilities and maintained integrations are evaluated first; custom development is proposed where it creates a meaningful workflow, ownership or experience advantage.',
            'Discovery separates first-release requirements from later opportunities. The resulting architecture, milestones and acceptance criteria give stakeholders a shared view of what is being built and how it will be supported.',
        ],
        'reasons' => [
            ['bi-search', 'Build-versus-buy review', 'Custom effort is reserved for requirements standard tools cannot meet well.'],
            ['bi-bezier2', 'Workflow-first UX', 'Interfaces follow real roles, decisions and exceptions.'],
            ['bi-plug', 'Documented integrations', 'Data ownership and failure behaviour are agreed before implementation.'],
            ['bi-git', 'Handover-ready delivery', 'Source, environments, dependencies and release responsibilities stay visible.'],
        ],
    ],

    'shopify-development' => [
        'solutions_kicker' => 'Shopify shaped around the operating model',
        'solutions_heading' => 'Shopify Stores for Launch, Growth and International Selling',
        'solutions_intro' => 'The right theme, apps and configuration depend on catalogue, team workflow and market requirements.',
        'solutions' => [
            ['bi-rocket-takeoff', 'New Shopify Stores', 'A focused storefront, catalogue and checkout setup for businesses moving into serious online selling.'],
            ['bi-palette2', 'Shopify 2.0 Redesign', 'Custom sections and templates that improve brand expression without weakening editor control.'],
            ['bi-building', 'Shopify Plus & B2B', 'Company accounts, catalogues and enterprise workflows assessed against available platform capability.'],
            ['bi-globe2', 'Shopify Markets', 'International domains, currency, language and catalogue decisions planned by target market.'],
            ['bi-arrow-repeat', 'Subscriptions & Retention', 'Account, recurring-order and communication flows integrated through suitable maintained apps.'],
            ['bi-box-arrow-in-right', 'Migration to Shopify', 'Products, customers, orders, content and important URLs mapped into the destination store.'],
        ],
        'foundation_kicker' => 'A disciplined Shopify foundation',
        'foundation_heading' => 'Theme, Apps and Store Operations in Balance',
        'foundation_intro' => 'Shopify is easier to operate when presentation, extensions and product data each have a clear responsibility.',
        'foundations' => [
            ['01 / Theme', 'A lean responsive storefront', 'Custom sections support brand and merchandising needs without turning every page into a one-off layout.', ['Liquid', 'Sections', 'Templates', 'Responsive']],
            ['02 / Apps', 'Extensions chosen deliberately', 'Apps are reviewed for overlap, storefront weight, support quality and ownership cost before installation.', ['App Audit', 'Compatibility', 'Webhooks', 'Cost']],
            ['03 / Operations', 'Products and orders stay manageable', 'Markets, inventory, fulfilment and reporting reflect how the business actually runs the store.', ['Markets', 'Inventory', 'Orders', 'Reports']],
        ],
        'integration_core' => ['bi-bag-check', 'Shopify'],
        'integration_nodes' => [['bi-grid', 'Apps'], ['bi-globe', 'Markets'], ['bi-boxes', 'ERP'], ['bi-bar-chart', 'Analytics']],
        'quality_kicker' => 'Shopify quality beyond the theme demo',
        'quality_heading' => 'Theme Quality, App Discipline, Performance and Maintainability',
        'quality_intro' => 'A manageable Shopify store needs clean boundaries between native features, theme code and extensions.',
        'quality' => [
            ['bi-layout-text-window', 'Theme Quality', 'Reusable sections preserve visual consistency and responsive behaviour.'],
            ['bi-grid', 'App Discipline', 'Each extension must justify its cost, access and storefront impact.'],
            ['bi-lightning-charge', 'Performance', 'Media, Liquid, scripts and apps are reviewed around real templates.'],
            ['bi-pencil-square', 'Maintainability', 'Editors can manage agreed content without modifying fragile theme code.'],
        ],
        'why_heading' => 'Shopify Expertise Without an App-First Sales Pitch',
        'why_paragraphs' => [
            'We begin with the catalogue, customer journey and operating workflow, then decide what Shopify should handle natively, what belongs in the theme and where an app or custom function is justified. This keeps the stack easier to understand.',
            'Our remote process uses reviewable milestones for structure, design, development, content and QA. Subscription costs, third-party limits and merchant responsibilities are stated clearly before launch.',
        ],
        'reasons' => [
            ['bi-bag-check', 'Shopify-aware planning', 'Native platform capability is used before unnecessary customization.'],
            ['bi-palette2', 'Original storefront design', 'The interface reflects the brand while remaining manageable in Shopify.'],
            ['bi-grid', 'Controlled app stack', 'Overlap, access, performance and recurring cost are reviewed.'],
            ['bi-arrow-left-right', 'Migration continuity', 'Data, URLs, tracking and launch responsibilities are mapped.'],
        ],
    ],

    'woocommerce-development' => [
        'solutions_kicker' => 'Commerce with WordPress flexibility',
        'solutions_heading' => 'WooCommerce Stores for Content-Rich and Flexible Selling',
        'solutions_intro' => 'WooCommerce works well when content ownership and tailored product logic justify active technical management.',
        'solutions' => [
            ['bi-journal-richtext', 'Content-Led Commerce', 'Editorial, guides and product content managed together within a structured WordPress system.'],
            ['bi-sliders', 'Complex Products', 'Variations, add-ons, bundles and product rules matched to realistic catalogue requirements.'],
            ['bi-people', 'Membership Stores', 'Protected products, account access and recurring relationships connected through suitable extensions.'],
            ['bi-calendar3', 'Bookings & Service Sales', 'Availability, deposits, appointments or service checkout integrated into the website journey.'],
            ['bi-building', 'Wholesale & B2B', 'Role-based catalogues, account pricing and ordering workflows for business customers.'],
            ['bi-arrow-left-right', 'WooCommerce Migration', 'Products, customers, orders, content and search URLs moved with staged validation.'],
        ],
        'foundation_kicker' => 'A maintainable WooCommerce foundation',
        'foundation_heading' => 'WordPress Content, Commerce Logic and Extensions',
        'foundation_intro' => 'Clear ownership between theme, plugin and content layers makes the store safer to update.',
        'foundations' => [
            ['01 / Content', 'Structured editing for real teams', 'Products, pages and reusable content remain manageable without allowing accidental layout damage.', ['Blocks', 'Products', 'Fields', 'Roles']],
            ['02 / Commerce', 'Product and checkout rules', 'Catalogue, tax, shipping, payment and order behaviour are configured around the sales model.', ['Catalogue', 'Checkout', 'Tax', 'Orders']],
            ['03 / Extensions', 'Functionality with boundaries', 'Plugins and integrations are assessed for overlap, maintenance, security and upgrade impact.', ['Plugins', 'APIs', 'Updates', 'Security']],
        ],
        'integration_core' => ['bi-wordpress', 'Woo'],
        'integration_nodes' => [['bi-credit-card', 'Payments'], ['bi-truck', 'Shipping'], ['bi-people', 'CRM'], ['bi-graph-up', 'Analytics']],
        'quality_kicker' => 'WooCommerce quality under active ownership',
        'quality_heading' => 'Performance, Security, Compatibility and Editor Control',
        'quality_intro' => 'A flexible store remains dependable only when the WordPress stack is managed as one system.',
        'quality' => [
            ['bi-lightning-charge', 'Performance', 'Templates, queries, media and extensions are reviewed on important store journeys.'],
            ['bi-shield-check', 'Security', 'Access, updates, backups and payment responsibilities remain documented.'],
            ['bi-puzzle', 'Compatibility', 'Theme, plugins and integrations are tested together before production updates.'],
            ['bi-pencil-square', 'Editor Control', 'Product and content workflows are structured for the people maintaining them.'],
        ],
        'why_heading' => 'WooCommerce Flexibility With Responsible Technical Ownership',
        'why_paragraphs' => [
            'We treat WooCommerce as an application running on WordPress, not as a collection of plugins. Theme code, product extensions, payments, shipping, caching and hosting are reviewed as connected responsibilities.',
            'Recommendations account for ongoing updates and support after launch. Where a managed commerce platform would be more suitable, we explain that trade-off instead of forcing every store into WooCommerce.',
        ],
        'reasons' => [
            ['bi-wordpress', 'WordPress architecture', 'Content and commerce are structured around editor and customer needs.'],
            ['bi-puzzle', 'Extension discipline', 'Plugins are selected for quality, compatibility and clear purpose.'],
            ['bi-speedometer2', 'Store-specific performance', 'Product, cart, account and checkout templates receive focused review.'],
            ['bi-tools', 'Ongoing maintainability', 'Updates, backups, staging and ownership remain part of the plan.'],
        ],
    ],

    'magento-development' => [
        'solutions_kicker' => 'Enterprise commerce needs disciplined architecture',
        'solutions_heading' => 'Magento for Complex Catalogues, Customers and Markets',
        'solutions_intro' => 'Magento is most valuable when sophisticated commerce requirements justify its operating and technical depth.',
        'solutions' => [
            ['bi-bag', 'Enterprise B2C', 'Large catalogues, promotions and customer journeys supported through scalable commerce operations.'],
            ['bi-building', 'Adobe Commerce B2B', 'Companies, buyer roles, shared catalogues, quotes and approval workflows.'],
            ['bi-shop-window', 'Multi-Brand Commerce', 'Separate websites, stores and views organized around genuine brand or business differences.'],
            ['bi-boxes', 'Large Catalogue Retail', 'Attributes, search, indexing and merchandising designed for substantial product ranges.'],
            ['bi-globe2', 'International Stores', 'Language, currency, tax, catalogue and fulfilment responsibilities separated by market.'],
            ['bi-arrow-repeat', 'Magento Migration & Upgrade', 'Data, extensions, integrations and SEO continuity managed through rehearsed releases.'],
        ],
        'foundation_kicker' => 'An enterprise Magento foundation',
        'foundation_heading' => 'Catalogue, Commerce Rules and Enterprise Systems',
        'foundation_intro' => 'Magento implementations succeed when product meaning and operational ownership are agreed across teams.',
        'foundations' => [
            ['01 / Catalogue', 'A governed product model', 'Attributes, product types, categories and search use consistent definitions across the organization.', ['Attributes', 'Products', 'Search', 'Governance']],
            ['02 / Commerce', 'Rules matched to customers', 'Pricing, promotions, accounts, quotations and approvals reflect real B2C or B2B processes.', ['Pricing', 'Promotions', 'B2B', 'Approvals']],
            ['03 / Enterprise', 'Systems connected at scale', 'ERP, PIM, warehouse and CRM exchanges have documented timing, ownership and failure handling.', ['ERP', 'PIM', 'WMS', 'CRM']],
        ],
        'integration_core' => ['bi-shop', 'Magento'],
        'integration_nodes' => [['bi-boxes', 'ERP'], ['bi-database', 'PIM'], ['bi-box-seam', 'WMS'], ['bi-people', 'CRM']],
        'quality_kicker' => 'Enterprise commerce quality',
        'quality_heading' => 'Architecture, Performance, Security and Release Discipline',
        'quality_intro' => 'A Magento store needs repeatable engineering and operational practices beyond feature configuration.',
        'quality' => [
            ['bi-diagram-3', 'Architecture', 'Modules, storefronts and integrations maintain clear responsibilities.'],
            ['bi-speedometer2', 'Performance', 'Caching, indexing, media, code and infrastructure are reviewed together.'],
            ['bi-shield-lock', 'Security', 'Patches, access and sensitive commerce operations follow documented ownership.'],
            ['bi-git', 'Release Discipline', 'Staging, migration rehearsals and rollback plans reduce production risk.'],
        ],
        'why_heading' => 'Magento Delivery Grounded in Operational Reality',
        'why_paragraphs' => [
            'Magento can support sophisticated commerce, but it introduces infrastructure, release and maintenance responsibilities that should be justified. We assess whether the catalogue, B2B model, multi-store needs and integrations make that investment sensible.',
            'For appropriate projects, discovery connects business teams and technical systems before implementation. The scope identifies data ownership, extensions, migration, performance and post-launch responsibility rather than treating them as separate afterthoughts.',
        ],
        'reasons' => [
            ['bi-clipboard-data', 'Enterprise discovery', 'Catalogue, teams, markets and connected systems are reviewed together.'],
            ['bi-boxes', 'Catalogue discipline', 'Product structure is agreed before bulk migration or integration.'],
            ['bi-plug', 'Integration architecture', 'Queues, timing, retries and operational visibility are planned.'],
            ['bi-git', 'Controlled releases', 'QA, migration rehearsals and production ownership stay explicit.'],
        ],
    ],

    'multi-vendor-marketplace' => [
        'solutions_kicker' => 'Marketplace models create different responsibilities',
        'solutions_heading' => 'Marketplace Platforms for Products, Services and B2B Exchange',
        'solutions_intro' => 'The commercial model and transaction journey determine seller tools, operator controls and payment architecture.',
        'solutions' => [
            ['bi-box-seam', 'Product Marketplaces', 'Multiple sellers offering structured products through consistent discovery and order journeys.'],
            ['bi-calendar-check', 'Service Marketplaces', 'Provider profiles, availability, requests or bookings organized around service decisions.'],
            ['bi-building', 'B2B Exchanges', 'Business accounts, enquiries, catalogues and negotiated transactions for professional buyers.'],
            ['bi-geo-alt', 'Local Marketplaces', 'Location-aware discovery, fulfilment and service areas without unsupported local claims.'],
            ['bi-shield-check', 'Managed Marketplaces', 'Operator-led onboarding, listing review, support and transaction oversight.'],
            ['bi-cash-stack', 'Hybrid Revenue Models', 'Commission, subscription, listing or lead fees reflected in reporting and access rules.'],
        ],
        'foundation_kicker' => 'A three-sided marketplace foundation',
        'foundation_heading' => 'Buyer Trust, Seller Tools and Operator Control',
        'foundation_intro' => 'Marketplace quality depends on balancing the needs and responsibilities of all three participant groups.',
        'foundations' => [
            ['01 / Buyers', 'Consistent discovery and support', 'Search, listings, seller context, checkout and policies create one understandable marketplace experience.', ['Search', 'Listings', 'Trust', 'Support']],
            ['02 / Sellers', 'Tools for responsible fulfilment', 'Onboarding, catalogue, orders, balances and feedback help sellers meet marketplace standards.', ['Onboarding', 'Catalogue', 'Orders', 'Payouts']],
            ['03 / Operators', 'Control of quality and risk', 'Moderation, commissions, disputes, reporting and audit history support accountable operation.', ['Moderation', 'Fees', 'Disputes', 'Audit']],
        ],
        'integration_core' => ['bi-people', 'Market'],
        'integration_nodes' => [['bi-person-plus', 'Sellers'], ['bi-credit-card', 'Payments'], ['bi-wallet2', 'Payouts'], ['bi-headset', 'Support']],
        'quality_kicker' => 'Quality across every marketplace role',
        'quality_heading' => 'Trust, Governance, Transaction Clarity and Operational Visibility',
        'quality_intro' => 'Growth is useful only when the operator can maintain quality and understand what is happening.',
        'quality' => [
            ['bi-person-check', 'Trust', 'Identity, seller context, policies and eligible reviews support informed decisions.'],
            ['bi-shield-check', 'Governance', 'Onboarding, moderation and account states apply marketplace standards consistently.'],
            ['bi-receipt', 'Transaction Clarity', 'Orders, fees, refunds and payouts remain understandable to each role.'],
            ['bi-activity', 'Operational Visibility', 'Dashboards, audit records and alerts help teams identify issues early.'],
        ],
        'why_heading' => 'Marketplace Development That Includes the Operating Model',
        'why_paragraphs' => [
            'A marketplace is not complete when sellers can register and buyers can pay. Policies, moderation, support, commissions, refunds and payouts must also be manageable by the team responsible for the platform.',
            'We map the smallest end-to-end marketplace transaction first, including exceptions and ownership. Later automation and channels can then follow evidence from actual seller, buyer and operator behaviour.',
        ],
        'reasons' => [
            ['bi-people', 'Three-sided discovery', 'Buyer, seller and operator needs are reviewed together.'],
            ['bi-signpost-split', 'Exception-aware journeys', 'Disputes, cancellations and failed states are designed before launch.'],
            ['bi-wallet2', 'Money-flow clarity', 'Commissions, refunds and payout eligibility remain documented.'],
            ['bi-speedometer2', 'Phased marketplace growth', 'The first complete transaction comes before unnecessary feature volume.'],
        ],
    ],
];
