<?php
/** Public service routes and exact menu labels for industry cards. */
function cbd_industry_service_catalog(): array
{
    return [
        'web-design' => ['title' => 'Web Design', 'icon' => 'bi-globe2'],
        'web-development' => ['title' => 'Web Development', 'icon' => 'bi-globe2'],
        'wordpress-development' => ['title' => 'WordPress Development', 'icon' => 'bi-globe2'],
        'landing-page-design' => ['title' => 'Landing Page Design', 'icon' => 'bi-globe2'],
        'website-redesign' => ['title' => 'Website Redesign', 'icon' => 'bi-globe2'],
        'cms-development' => ['title' => 'CMS Development', 'icon' => 'bi-globe2'],
        'ecommerce-website-development' => ['title' => 'eCommerce Website Development', 'icon' => 'bi-cart4'],
        'custom-ecommerce-development' => ['title' => 'Custom eCommerce Development', 'icon' => 'bi-cart4'],
        'shopify-development' => ['title' => 'Shopify Development', 'icon' => 'bi-cart4'],
        'woocommerce-development' => ['title' => 'WooCommerce Development', 'icon' => 'bi-cart4'],
        'magento-development' => ['title' => 'Magento Development', 'icon' => 'bi-cart4'],
        'multi-vendor-marketplace' => ['title' => 'Multi-Vendor Marketplace', 'icon' => 'bi-cart4'],
        'android-app-development' => ['title' => 'Android App Development', 'icon' => 'bi-phone'],
        'ios-app-development' => ['title' => 'iOS App Development', 'icon' => 'bi-phone'],
        'custom-software-development' => ['title' => 'Custom Software Development', 'icon' => 'bi-phone'],
        'saas-development' => ['title' => 'SaaS Development', 'icon' => 'bi-phone'],
        'crm-development' => ['title' => 'CRM Development', 'icon' => 'bi-phone'],
        'erp-software-development' => ['title' => 'ERP Development', 'icon' => 'bi-phone'],
        'nodejs-development' => ['title' => 'Node.js Development', 'icon' => 'bi-code-square'],
        'reactjs-development' => ['title' => 'React JS Development', 'icon' => 'bi-code-square'],
        'laravel-development' => ['title' => 'Laravel Development', 'icon' => 'bi-code-square'],
        'php-development' => ['title' => 'PHP Development', 'icon' => 'bi-code-square'],
        'joomla' => ['title' => 'Joomla Development', 'icon' => 'bi-code-square'],
        'nextjs-development' => ['title' => 'Next.js Development', 'icon' => 'bi-code-square'],
        'seo-services' => ['title' => 'SEO Services', 'icon' => 'bi-graph-up-arrow'],
        'local-seo-services' => ['title' => 'Local SEO', 'icon' => 'bi-graph-up-arrow'],
        'technical-seo' => ['title' => 'Technical SEO', 'icon' => 'bi-graph-up-arrow'],
        'google-ads-ppc' => ['title' => 'Google Ads / PPC', 'icon' => 'bi-graph-up-arrow'],
        'social-media-marketing' => ['title' => 'Social Media Marketing', 'icon' => 'bi-graph-up-arrow'],
        'content-marketing' => ['title' => 'Content Marketing', 'icon' => 'bi-graph-up-arrow'],
        'ui-ux-design' => ['title' => 'UI/UX Design', 'icon' => 'bi-vector-pen'],
        'figma-design' => ['title' => 'Figma Design', 'icon' => 'bi-vector-pen'],
        'graphic-design' => ['title' => 'Graphic Design', 'icon' => 'bi-vector-pen'],
        'logo-design' => ['title' => 'Logo Design', 'icon' => 'bi-vector-pen'],
        'branding-identity' => ['title' => 'Branding & Identity', 'icon' => 'bi-vector-pen'],
        'dashboard-ui-design' => ['title' => 'Dashboard UI Design', 'icon' => 'bi-vector-pen'],
        'website-maintenance' => ['title' => 'Website Maintenance', 'icon' => 'bi-tools'],
        'website-speed-optimization' => ['title' => 'Speed Optimization', 'icon' => 'bi-tools'],
        'core-web-vitals-optimization' => ['title' => 'Core Web Vitals Optimization', 'icon' => 'bi-tools'],
        'website-migration' => ['title' => 'Website Migration', 'icon' => 'bi-tools'],
        'website-security' => ['title' => 'Website Security', 'icon' => 'bi-tools'],
        'website-performance-optimization' => ['title' => 'Website Performance Optimization', 'icon' => 'bi-tools'],
        'ai-chatbot-integration' => ['title' => 'AI Chatbot Development', 'icon' => 'bi-robot'],
        'whatsapp-automation' => ['title' => 'WhatsApp Automation', 'icon' => 'bi-robot'],
        'workflow-automation' => ['title' => 'Workflow Automation', 'icon' => 'bi-robot'],
        'ai-integration' => ['title' => 'AI Integration', 'icon' => 'bi-robot'],
        'ai-business-automation' => ['title' => 'Business Process Automation', 'icon' => 'bi-robot'],
        'ai-agent-development' => ['title' => 'AI Agent Development', 'icon' => 'bi-robot'],
    ];
}
