<?php
$services_detail = [

    // WEB DESIGN & DEV
    'landing-page-design' => [
        'slug'=>'landing-page-design','title'=>'Landing Page Design','category'=>'Web Design & Development','cat_color'=>'#3b82f6','cat_bg'=>'rgba(59,130,246,.1)','icon'=>'bi-layout-text-window-reverse',
        'meta_title'=>'Landing Page Design Services in India | High-Converting Pages — Chulbul Design',
        'meta_desc'=>'Professional landing page design services in India. Fast, mobile-first landing pages optimised for conversions, Google Ads and lead generation. Free quote.',
        'canonical'=>'https://www.chulbuldesign.com/landing-page-design',
        'h1'=>'Landing Page Design Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'High-converting landing pages built for Google Ads, Meta Ads & organic traffic.',
        'intro'=>'A landing page is the first thing your paid traffic sees — and a poorly designed one burns your ad budget without results. Chulbul Design builds landing pages that load in under 2 seconds, communicate your offer clearly, and convert visitors into leads. We have built landing pages for coaching institutes, SaaS products, real estate builders and clinics across India.',
        'features'=>['Custom design — no templates','Mobile-first & PageSpeed 95+','A/B test ready structure','Lead capture forms with CRM integration','Google Ads / Meta Ads optimised','Analytics & heatmap setup'],
        'stats'=>[['num'=>'2s','label'=>'Avg Load Time'],['num'=>'3x','label'=>'More Conversions'],['num'=>'95+','label'=>'PageSpeed Score'],['num'=>'7d','label'=>'Delivery Time']],
        'faq'=>[['q'=>'How much does a landing page cost in India?','a'=>'A professional landing page starts from ₹8,000 depending on complexity and integrations.'],['q'=>'How long does landing page design take?','a'=>'Standard landing page delivered in 5–7 working days.'],['q'=>'Can you connect the form to our CRM?','a'=>'Yes — HubSpot, Zoho, Salesforce, WhatsApp, Google Sheets and any webhook CRM.']],
    ],
    'website-redesign' => [
        'slug'=>'website-redesign','title'=>'Website Redesign Services','category'=>'Web Design & Development','cat_color'=>'#3b82f6','cat_bg'=>'rgba(59,130,246,.1)','icon'=>'bi-arrow-repeat',
        'meta_title'=>'Website Redesign Services in India | Modern, Fast & SEO-Ready — Chulbul Design',
        'meta_desc'=>'Expert website redesign company in India. We modernise outdated websites — better UI, faster load times, SEO-optimised and mobile-first. 500+ projects delivered.',
        'canonical'=>'https://www.chulbuldesign.com/website-redesign',
        'h1'=>'Website Redesign Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Transform your outdated website into a modern, fast, conversion-focused digital presence.',
        'intro'=>'An outdated website is costing you customers every single day. Poor mobile experience, slow load times and old design signal to visitors — and to Google — that your business is not credible. Chulbul Design specialises in full website redesigns that preserve your SEO rankings while completely transforming the look, speed and performance.',
        'features'=>['Full UI/UX audit before redesign','SEO-preserving URL structure migration','Mobile-first responsive rebuild','PageSpeed 90+ guaranteed','Content migration from old site','301 redirects & GSC setup'],
        'stats'=>[['num'=>'90+','label'=>'PageSpeed After'],['num'=>'2x','label'=>'More Enquiries'],['num'=>'60%','label'=>'Lower Bounce Rate'],['num'=>'2-4wk','label'=>'Delivery']],
        'faq'=>[['q'=>'Will my SEO rankings drop after redesign?','a'=>'No — we follow SEO-safe redesign practices including 301 redirects and proper URL migration.'],['q'=>'How much does website redesign cost?','a'=>'Website redesign starts from ₹20,000. Ecommerce redesigns from ₹35,000.'],['q'=>'How long does a website redesign take?','a'=>'Typically 2–4 weeks depending on pages and content.']],
    ],
    'cms-development' => [
        'slug'=>'cms-development','title'=>'CMS Development','category'=>'Web Design & Development','cat_color'=>'#3b82f6','cat_bg'=>'rgba(59,130,246,.1)','icon'=>'bi-pencil-square',
        'meta_title'=>'CMS Development Company in India | WordPress, Custom CMS — Chulbul Design',
        'meta_desc'=>'Custom CMS development services in India. Easy-to-manage content management systems using WordPress, Laravel and custom PHP. Free consultation.',
        'canonical'=>'https://www.chulbuldesign.com/cms-development',
        'h1'=>'CMS Development Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Manage your website content easily — without developers or technical knowledge.',
        'intro'=>'A website without a CMS means every content update requires a developer — wasted time and money. Chulbul Design builds CMS-powered websites where your team can update pages, blogs, products and media independently. We work with WordPress, Laravel-based custom CMS and headless CMS solutions.',
        'features'=>['WordPress CMS development','Custom admin panel in Laravel/PHP','Role-based access control','Blog, news & media management','Product & catalogue management','Full CMS training included'],
        'stats'=>[['num'=>'0','label'=>'Dev Needed for Updates'],['num'=>'3hrs','label'=>'CMS Training'],['num'=>'100%','label'=>'Team Manageable'],['num'=>'10yr','label'=>'Experience']],
        'faq'=>[['q'=>'Which CMS do you recommend?','a'=>'WordPress for most business websites. Custom Laravel CMS for complex workflows or specific business logic.'],['q'=>'Can non-technical staff manage it?','a'=>'Yes — we build the admin panel for non-technical users and provide full training.'],['q'=>'How much does CMS development cost?','a'=>'CMS starts from ₹15,000 for WordPress. Custom CMS from ₹40,000.']],
    ],
    'api-integration' => [
        'slug'=>'api-integration','title'=>'API Integration Services','category'=>'Web Design & Development','cat_color'=>'#3b82f6','cat_bg'=>'rgba(59,130,246,.1)','icon'=>'bi-plug',
        'meta_title'=>'API Integration Services India | Payment, CRM & Custom API — Chulbul Design',
        'meta_desc'=>'Expert API integration services in India. Payment gateways, CRM, ERP, WhatsApp, Google Maps, logistics APIs and custom REST/GraphQL API development.',
        'canonical'=>'https://www.chulbuldesign.com/api-integration',
        'h1'=>'API Integration Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Connect your website or app to any third-party service — payments, CRM, logistics, and more.',
        'intro'=>'Modern businesses run on connected systems — payment gateways, CRMs, shipping partners, WhatsApp and ERPs all need to talk to your website. Chulbul Design handles API integration for all major platforms and builds custom REST APIs for unique business requirements.',
        'features'=>['Payment gateway (Razorpay, PayU, Stripe)','WhatsApp Business API','Google Maps & Places API','CRM integration (HubSpot, Zoho)','Logistics API (Shiprocket, Delhivery)','Custom REST & GraphQL API'],
        'stats'=>[['num'=>'50+','label'=>'APIs Integrated'],['num'=>'99.9%','label'=>'Uptime SLA'],['num'=>'3-7d','label'=>'Integration Time'],['num'=>'10yr','label'=>'Experience']],
        'faq'=>[['q'=>'How long does API integration take?','a'=>'Simple integrations take 2–5 days. Complex multi-system integrations take 1–3 weeks.'],['q'=>'Can you build a custom API?','a'=>'Yes — REST and GraphQL APIs in Laravel and Node.js.'],['q'=>'Do you integrate Indian payment gateways?','a'=>'Yes — Razorpay, PayU, CCAvenue, Cashfree, UPI and all major gateways.']],
    ],

    // ECOMMERCE
    'shopify-development' => [
        'slug'=>'shopify-development','title'=>'Shopify Development','category'=>'Ecommerce Solutions','cat_color'=>'#10b981','cat_bg'=>'rgba(16,185,129,.1)','icon'=>'bi-bag-check',
        'meta_title'=>'Shopify Development Company in India | Custom Shopify Store — Chulbul Design',
        'meta_desc'=>'Expert Shopify development company in India. Custom Shopify stores with fast checkout, Indian payment gateways and conversion-optimised design. Free quote.',
        'canonical'=>'https://www.chulbuldesign.com/shopify-development',
        'h1'=>'Shopify Development Company <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Custom Shopify stores built to sell — fast checkout, Indian payments, mobile-first design.',
        'intro'=>'Shopify is the world\'s fastest growing ecommerce platform. Chulbul Design builds custom Shopify stores for Indian D2C brands, exporters and retailers — with UPI, Razorpay and COD payment options, fast-loading product pages and mobile-first design.',
        'features'=>['Custom Shopify theme development','Indian payment gateway (Razorpay, UPI)','Product catalogue & variant setup','Shopify Apps integration','Speed optimisation & Core Web Vitals','Inventory & order management setup'],
        'stats'=>[['num'=>'4x','label'=>'Avg Sales Increase'],['num'=>'2s','label'=>'Store Load Time'],['num'=>'2wk','label'=>'Launch Time'],['num'=>'0%','label'=>'Template Dependency']],
        'faq'=>[['q'=>'How much does Shopify development cost in India?','a'=>'Custom Shopify store starts from ₹25,000 including theme, payment setup and product upload.'],['q'=>'Do you integrate Indian payment gateways?','a'=>'Yes — Razorpay, PayU, Cashfree, UPI and COD.'],['q'=>'Can you migrate WooCommerce to Shopify?','a'=>'Yes — products, orders, customer data and SEO settings migrated with zero data loss.']],
    ],
    'woocommerce-development' => [
        'slug'=>'woocommerce-development','title'=>'WooCommerce Development','category'=>'Ecommerce Solutions','cat_color'=>'#10b981','cat_bg'=>'rgba(16,185,129,.1)','icon'=>'bi-wordpress',
        'meta_title'=>'WooCommerce Development Company in India | Custom WooCommerce Store — Chulbul Design',
        'meta_desc'=>'Expert WooCommerce development services in India. Custom stores, payment integration, speed optimisation and maintenance. 500+ projects. Free quote.',
        'canonical'=>'https://www.chulbuldesign.com/woocommerce-development',
        'h1'=>'WooCommerce Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Powerful WooCommerce stores built for Indian businesses — fast, SEO-ready and conversion-optimised.',
        'intro'=>'WooCommerce powers over 30% of all online stores worldwide. Chulbul Design builds and optimises WooCommerce stores from scratch — custom themes, streamlined checkout, Indian payment gateways and product catalogues built for performance and conversions.',
        'features'=>['Custom WooCommerce theme','Razorpay, UPI & COD integration','Checkout optimisation (1-2 step)','Product variations & attribute setup','WooCommerce speed optimisation','GST-ready invoice generation'],
        'stats'=>[['num'=>'2-step','label'=>'Checkout Flow'],['num'=>'90+','label'=>'PageSpeed Score'],['num'=>'4x','label'=>'More Conversions'],['num'=>'3wk','label'=>'Delivery']],
        'faq'=>[['q'=>'How much does WooCommerce development cost?','a'=>'WooCommerce store starts from ₹22,000 including theme, payment gateway and product setup.'],['q'=>'Is WooCommerce better than Shopify for India?','a'=>'WooCommerce offers more customisation. We help you choose based on your specific needs.'],['q'=>'Can you optimise my existing WooCommerce store?','a'=>'Yes — we reduce load time from 8+ seconds to under 2 seconds.']],
    ],
    'magento-development' => [
        'slug'=>'magento-development','title'=>'Magento Development','category'=>'Ecommerce Solutions','cat_color'=>'#10b981','cat_bg'=>'rgba(16,185,129,.1)','icon'=>'bi-shop',
        'meta_title'=>'Magento Development Company in India | Custom Magento 2 Store — Chulbul Design',
        'meta_desc'=>'Expert Magento development company in India. Custom Magento 2 stores for large catalogues, B2B ecommerce and enterprise retail. Free consultation.',
        'canonical'=>'https://www.chulbuldesign.com/magento-development',
        'h1'=>'Magento Development Company <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Enterprise-grade Magento 2 stores for large catalogues and B2B ecommerce.',
        'intro'=>'Magento is the platform of choice for large-scale ecommerce — thousands of SKUs, multiple warehouses and complex shipping rules. Chulbul Design builds custom Magento 2 stores for exporters, manufacturers and retail chains that need power and scale.',
        'features'=>['Magento 2 custom theme development','Multi-store & multi-language setup','B2B catalogue with custom pricing','ERP & inventory integration','Performance optimisation for large catalogues','Payment & logistics integration'],
        'stats'=>[['num'=>'10k+','label'=>'SKUs Supported'],['num'=>'B2B','label'=>'Price List Ready'],['num'=>'Multi','label'=>'Store Support'],['num'=>'10yr','label'=>'Experience']],
        'faq'=>[['q'=>'When should I choose Magento?','a'=>'Choose Magento for 500+ SKUs, complex B2B pricing or multiple storefronts.'],['q'=>'How much does Magento development cost?','a'=>'Magento 2 starts from ₹80,000. Enterprise setups from ₹2,00,000.'],['q'=>'Do you do Magento 1 to Magento 2 migration?','a'=>'Yes — complete migration including data, extensions and themes.']],
    ],
    'multi-vendor-marketplace' => [
        'slug'=>'multi-vendor-marketplace','title'=>'Multi Vendor Marketplace Development','category'=>'Ecommerce Solutions','cat_color'=>'#10b981','cat_bg'=>'rgba(16,185,129,.1)','icon'=>'bi-grid',
        'meta_title'=>'Multi Vendor Marketplace Development India | Build Your Own Marketplace — Chulbul Design',
        'meta_desc'=>'Custom multi-vendor marketplace development in India. Build your own Amazon or Meesho-style platform with vendor management, commissions and payouts.',
        'canonical'=>'https://www.chulbuldesign.com/multi-vendor-marketplace',
        'h1'=>'Multi Vendor Marketplace Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Build your own Amazon or Meesho — custom marketplace with vendor management, commissions and payouts.',
        'intro'=>'A multi-vendor marketplace lets multiple sellers list and sell products through your platform while you earn a commission. Chulbul Design builds custom marketplace platforms for B2B, B2C and hyperlocal use cases — with vendor onboarding, product approval workflows and integrated payouts.',
        'features'=>['Vendor registration & dashboard','Product listing & approval workflow','Commission & payout management','Buyer & seller rating system','Multi-currency support','Razorpay split payment integration'],
        'stats'=>[['num'=>'∞','label'=>'Vendors Supported'],['num'=>'Auto','label'=>'Commission Split'],['num'=>'Custom','label'=>'Commission %'],['num'=>'8-12wk','label'=>'Build Time']],
        'faq'=>[['q'=>'How much does marketplace development cost?','a'=>'Basic marketplace starts from ₹1,20,000. Full-featured with mobile apps from ₹3,00,000.'],['q'=>'Can vendors manage their own products?','a'=>'Yes — each vendor gets a dedicated dashboard.'],['q'=>'Do you build marketplace mobile apps?','a'=>'Yes — Android and iOS apps for buyers and vendors.']],
    ],

    // MOBILE & SOFTWARE
    'android-app-development' => [
        'slug'=>'android-app-development','title'=>'Android App Development','category'=>'Mobile & Software','cat_color'=>'#7c3aed','cat_bg'=>'rgba(124,58,237,.1)','icon'=>'bi-android2',
        'meta_title'=>'Android App Development Company in India | Native & React Native — Chulbul Design',
        'meta_desc'=>'Top Android app development company in India. Native Android and React Native apps for startups, SMEs and enterprises. Play Store launch included. Free quote.',
        'canonical'=>'https://www.chulbuldesign.com/android-app-development',
        'h1'=>'Android App Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Custom Android apps for Indian businesses — from prototype to Play Store in record time.',
        'intro'=>'India has over 700 million Android users. Chulbul Design builds custom Android applications for logistics, retail, healthcare and education — native Android for maximum performance or React Native for cross-platform efficiency.',
        'features'=>['Native Android (Kotlin/Java)','React Native cross-platform','Google Play Store submission','Offline functionality support','Push notifications & Firebase','Payment gateway integration'],
        'stats'=>[['num'=>'700M+','label'=>'Android Users in India'],['num'=>'4wk','label'=>'Avg Build Time'],['num'=>'Play','label'=>'Store Launch'],['num'=>'100%','label'=>'In-House Dev']],
        'faq'=>[['q'=>'How much does Android app development cost?','a'=>'Basic app starts from ₹40,000. Complex apps with backend from ₹1,20,000.'],['q'=>'React Native or native Android?','a'=>'Native for maximum performance. React Native if you also need iOS.'],['q'=>'Do you handle Play Store submission?','a'=>'Yes — complete submission process including store listing and compliance.']],
    ],
    'ios-app-development' => [
        'slug'=>'ios-app-development','title'=>'iOS App Development','category'=>'Mobile & Software','cat_color'=>'#7c3aed','cat_bg'=>'rgba(124,58,237,.1)','icon'=>'bi-apple',
        'meta_title'=>'iOS App Development Company in India | iPhone & iPad Apps — Chulbul Design',
        'meta_desc'=>'Expert iOS app development company in India. Native Swift and React Native iOS apps. App Store launch included. Free consultation.',
        'canonical'=>'https://www.chulbuldesign.com/ios-app-development',
        'h1'=>'iOS App Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Custom iPhone and iPad apps — premium design, App Store launch, built for performance.',
        'intro'=>'iOS users represent the premium segment of mobile consumers — higher spending power and higher conversion rates. Chulbul Design builds iOS apps for startups, enterprises and consumer brands using Swift for native performance or React Native for cross-platform launches.',
        'features'=>['Native Swift iOS development','React Native for iOS & Android','Apple App Store submission','In-app purchase & subscription','Apple Pay integration','iPad-responsive UI design'],
        'stats'=>[['num'=>'Swift','label'=>'Native Dev'],['num'=>'App','label'=>'Store Launch'],['num'=>'4wk','label'=>'Avg Build Time'],['num'=>'100%','label'=>'In-House']],
        'faq'=>[['q'=>'How much does iOS app development cost?','a'=>'Basic iOS app starts from ₹50,000. Full-featured apps from ₹1,50,000.'],['q'=>'Do you build both Android and iOS?','a'=>'Yes — React Native for both platforms, saving up to 40% cost.'],['q'=>'Do you handle App Store submission?','a'=>'Yes — complete Apple App Store review process.']],
    ],
    'saas-development' => [
        'slug'=>'saas-development','title'=>'SaaS Application Development','category'=>'Mobile & Software','cat_color'=>'#7c3aed','cat_bg'=>'rgba(124,58,237,.1)','icon'=>'bi-cloud-arrow-up',
        'meta_title'=>'SaaS Application Development Company India | Custom SaaS Platform — Chulbul Design',
        'meta_desc'=>'Custom SaaS application development in India. Multi-tenant SaaS platforms with subscription billing, dashboards and scalable cloud architecture.',
        'canonical'=>'https://www.chulbuldesign.com/saas-development',
        'h1'=>'SaaS Application Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Build your SaaS product from idea to launch — multi-tenant, subscription-ready and scalable.',
        'intro'=>'SaaS is the fastest-growing business model in technology. Chulbul Design has built SaaS platforms for HR, logistics, healthcare and education startups across India — with multi-tenancy, subscription billing, onboarding flows and scalable cloud architecture.',
        'features'=>['Multi-tenant architecture','Subscription billing (Razorpay, Stripe)','User onboarding & role management','Analytics dashboard','AWS / DigitalOcean deployment','API-first architecture'],
        'stats'=>[['num'=>'Multi','label'=>'Tenant Ready'],['num'=>'Sub','label'=>'Billing Built-in'],['num'=>'API','label'=>'First Design'],['num'=>'Cloud','label'=>'Native']],
        'faq'=>[['q'=>'How much does SaaS development cost?','a'=>'SaaS MVP starts from ₹1,50,000. Full-featured SaaS from ₹4,00,000.'],['q'=>'How long does it take?','a'=>'MVP takes 8–12 weeks. Full platform 16–24 weeks.'],['q'=>'Do you help with product strategy?','a'=>'Yes — product scoping sessions before development.']],
    ],
    'crm-development' => [
        'slug'=>'crm-development','title'=>'CRM Development','category'=>'Mobile & Software','cat_color'=>'#7c3aed','cat_bg'=>'rgba(124,58,237,.1)','icon'=>'bi-people',
        'meta_title'=>'Custom CRM Development Company India | Sales CRM Software — Chulbul Design',
        'meta_desc'=>'Custom CRM development services in India. Sales CRM, lead management systems and customer portals tailored to your workflow. Free consultation.',
        'canonical'=>'https://www.chulbuldesign.com/crm-development',
        'h1'=>'Custom CRM Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Stop paying monthly SaaS fees — get a custom CRM built exactly for your sales process.',
        'intro'=>'Off-the-shelf CRMs like Salesforce and HubSpot are expensive and over-engineered for Indian SMEs. Chulbul Design builds custom CRM systems tailored to your exact sales workflow — lead capture, follow-up reminders, pipeline tracking, quotation generation and reporting.',
        'features'=>['Lead capture & source tracking','Sales pipeline & deal stages','Follow-up reminder & task management','Quotation & invoice generation','WhatsApp integration','Custom reports & analytics'],
        'stats'=>[['num'=>'0','label'=>'Monthly SaaS Fee'],['num'=>'100%','label'=>'Custom to Your Process'],['num'=>'WA','label'=>'Integration Ready'],['num'=>'8-12wk','label'=>'Build Time']],
        'faq'=>[['q'=>'How much does custom CRM cost?','a'=>'Basic lead management CRM starts from ₹80,000. Full CRM with mobile app from ₹2,00,000.'],['q'=>'Can you integrate with WhatsApp?','a'=>'Yes — WhatsApp Business API integration included.'],['q'=>'Is it better to build or buy a CRM?','a'=>'For 10+ person sales teams, custom CRM pays for itself within 18 months.']],
    ],
    'erp-software-development' => [
        'slug'=>'erp-software-development','title'=>'ERP Software Development','category'=>'Mobile & Software','cat_color'=>'#7c3aed','cat_bg'=>'rgba(124,58,237,.1)','icon'=>'bi-diagram-3',
        'meta_title'=>'ERP Software Development Company India | Custom ERP Solutions — Chulbul Design',
        'meta_desc'=>'Custom ERP software development in India. Manufacturing ERP, inventory management and enterprise resource planning for SMEs and enterprises.',
        'canonical'=>'https://www.chulbuldesign.com/erp-software-development',
        'h1'=>'ERP Software Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Custom ERP for manufacturing, retail and service businesses — no per-user licensing.',
        'intro'=>'ERP software connects your entire business — inventory, production, sales, HR and accounts — into one integrated system. Chulbul Design builds custom ERP for manufacturers and distributors who need more control than SAP or Tally provides, without per-user licensing costs.',
        'features'=>['Inventory & warehouse management','Production & manufacturing tracking','Purchase order & vendor management','Sales, invoicing & GST compliance','HR & payroll module','Custom reporting & MIS'],
        'stats'=>[['num'=>'0','label'=>'Per-User License Fee'],['num'=>'GST','label'=>'Compliant'],['num'=>'Custom','label'=>'Workflows'],['num'=>'16+wk','label'=>'Build Time']],
        'faq'=>[['q'=>'How much does custom ERP cost?','a'=>'Basic 3-module ERP from ₹2,50,000. Full enterprise ERP from ₹8,00,000.'],['q'=>'Can you integrate with Tally?','a'=>'Yes — financial data syncs automatically with Tally.'],['q'=>'How long does ERP development take?','a'=>'Basic ERP 12–16 weeks. Full enterprise 20–36 weeks.']],
    ],

    // TECHNOLOGIES
    'reactjs-development' => [
        'slug'=>'reactjs-development','title'=>'React JS Development','category'=>'Technologies','cat_color'=>'#0ea5e9','cat_bg'=>'rgba(14,165,233,.1)','icon'=>'bi-braces',
        'meta_title'=>'React JS Development Company India | Custom React Applications — Chulbul Design',
        'meta_desc'=>'Expert React JS development company in India. Fast, interactive web applications, dashboards and SPAs using React JS, Next.js and Redux.',
        'canonical'=>'https://www.chulbuldesign.com/reactjs-development',
        'h1'=>'React JS Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Lightning-fast React applications, dashboards and SPAs built by experienced developers.',
        'intro'=>'React JS is the most popular JavaScript framework for building interactive, high-performance web applications. Chulbul Design\'s React developers build scalable, maintainable applications — from SaaS dashboards and admin panels to ecommerce frontends and real-time apps.',
        'features'=>['React JS & Next.js development','Single Page Application (SPA)','Interactive dashboard & admin panel','REST & GraphQL API integration','Redux & Context state management','TypeScript support'],
        'stats'=>[['num'=>'Fast','label'=>'Virtual DOM Rendering'],['num'=>'SPA','label'=>'Single Page App'],['num'=>'Next.js','label'=>'SSR Support'],['num'=>'10yr','label'=>'Experience']],
        'faq'=>[['q'=>'When should I use React JS?','a'=>'Use React for interactive dashboards, SaaS products, real-time apps and complex UI with filters or live updates.'],['q'=>'How much does React JS development cost?','a'=>'React web app starts from ₹60,000. Complex SaaS dashboards from ₹1,50,000.'],['q'=>'Do you use Next.js for SEO?','a'=>'Yes — Next.js with SSR for public-facing React apps that need Google indexing.']],
    ],
    'nodejs-development' => [
        'slug'=>'nodejs-development','title'=>'Node.js Development','category'=>'Technologies','cat_color'=>'#0ea5e9','cat_bg'=>'rgba(14,165,233,.1)','icon'=>'bi-server',
        'meta_title'=>'Node.js Development Company India | Backend & API Development — Chulbul Design',
        'meta_desc'=>'Expert Node.js development in India. Scalable REST APIs, real-time applications and microservices using Node.js and Express.',
        'canonical'=>'https://www.chulbuldesign.com/nodejs-development',
        'h1'=>'Node.js Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Scalable Node.js backends, APIs and real-time applications for modern businesses.',
        'intro'=>'Node.js is the preferred backend for high-performance APIs and real-time applications. Its event-driven architecture makes it ideal for chat apps, live notifications and high-concurrency systems. Chulbul Design builds Node.js backends that scale to thousands of concurrent users.',
        'features'=>['REST API with Express','Real-time apps with Socket.io','Microservices architecture','MongoDB & PostgreSQL','JWT authentication & OAuth','AWS / DigitalOcean deployment'],
        'stats'=>[['num'=>'Real','label'=>'Time Ready'],['num'=>'Scale','label'=>'Horizontally'],['num'=>'API','label'=>'First Design'],['num'=>'Cloud','label'=>'Deployable']],
        'faq'=>[['q'=>'Is Node.js good for Indian startups?','a'=>'Yes — cost-efficient, handles high concurrency and integrates well with React.'],['q'=>'How much does Node.js development cost?','a'=>'REST API from ₹40,000. Full-stack Node.js + React from ₹1,00,000.'],['q'=>'Can you migrate PHP to Node.js?','a'=>'Yes — we rewrite PHP backends in Node.js for better performance.']],
    ],
    'laravel-development' => [
        'slug'=>'laravel-development','title'=>'Laravel Development','category'=>'Technologies','cat_color'=>'#0ea5e9','cat_bg'=>'rgba(14,165,233,.1)','icon'=>'bi-code-slash',
        'meta_title'=>'Laravel Development Company India | Custom Laravel Web Applications — Chulbul Design',
        'meta_desc'=>'Expert Laravel development in India. Robust web applications, REST APIs, admin panels and SaaS platforms using the Laravel PHP framework.',
        'canonical'=>'https://www.chulbuldesign.com/laravel-development',
        'h1'=>'Laravel Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Robust Laravel web applications, APIs and custom admin panels — built to last.',
        'intro'=>'Laravel is the most elegant PHP framework for building web applications — with built-in authentication, database migrations and a rich ecosystem. Chulbul Design uses Laravel for custom CRM systems, SaaS platforms, REST APIs, booking systems and complex business applications.',
        'features'=>['Laravel 10/11 development','REST API with Sanctum','Custom admin panel (Filament)','MySQL & PostgreSQL','Queue & scheduled tasks','Unit & feature test coverage'],
        'stats'=>[['num'=>'L10','label'=>'Latest Laravel'],['num'=>'REST','label'=>'API Ready'],['num'=>'Queue','label'=>'Job Support'],['num'=>'10yr','label'=>'PHP Experience']],
        'faq'=>[['q'=>'Why choose Laravel?','a'=>'Rapid development, built-in security, elegant ORM and a massive ecosystem — most productive PHP framework.'],['q'=>'How much does Laravel development cost?','a'=>'Laravel app from ₹50,000. Complex applications from ₹1,50,000.'],['q'=>'Can you migrate CodeIgniter to Laravel?','a'=>'Yes — complete migration while maintaining all functionality.']],
    ],
    'php-development' => [
        'slug'=>'php-development','title'=>'PHP Development','category'=>'Technologies','cat_color'=>'#0ea5e9','cat_bg'=>'rgba(14,165,233,.1)','icon'=>'bi-filetype-php',
        'meta_title'=>'PHP Development Company India | Custom PHP Web Development — Chulbul Design',
        'meta_desc'=>'Expert PHP development company in India with 10+ years experience. Custom PHP applications, portals, APIs and legacy PHP modernisation.',
        'canonical'=>'https://www.chulbuldesign.com/php-development',
        'h1'=>'PHP Development <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'10+ years of PHP expertise — custom applications, portals and legacy modernisation.',
        'intro'=>'PHP powers over 75% of all websites on the internet. Chulbul Design has 10+ years of PHP development experience — building custom portals, booking systems and complex multi-module business applications for clients across India and internationally.',
        'features'=>['Core PHP & MVC development','Custom portal & web application','Legacy PHP modernisation','Database design & optimisation','Payment gateway & API integration','Server deployment & maintenance'],
        'stats'=>[['num'=>'10+','label'=>'Years PHP Experience'],['num'=>'75%','label'=>'Web Uses PHP'],['num'=>'500+','label'=>'Projects Delivered'],['num'=>'24h','label'=>'Support']],
        'faq'=>[['q'=>'Is PHP still relevant in 2025?','a'=>'Absolutely — PHP 8.x is modern and fast. Laravel and WordPress are PHP-based.'],['q'=>'Can you maintain our PHP application?','a'=>'Yes — bug fixing, feature additions, security patching.'],['q'=>'How much does PHP development cost?','a'=>'Custom PHP app from ₹30,000. Complex portals from ₹80,000.']],
    ],

    // SEO & MARKETING
    'local-seo-services' => [
        'slug'=>'local-seo-services','title'=>'Local SEO Services','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-geo-alt',
        'meta_title'=>'Local SEO Services India | Google Maps & Local Search Ranking — Chulbul Design',
        'meta_desc'=>'Local SEO services for businesses across India. Google Business Profile optimisation, local citations and on-page SEO to rank in local searches and Google Maps.',
        'canonical'=>'https://www.chulbuldesign.com/local-seo-services',
        'h1'=>'Local SEO Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Rank on page 1 when customers search for your service in your city.',
        'intro'=>'"Best dentist in Gurgaon." "Web designer near me." Local searches drive the most ready-to-buy traffic. Chulbul Design\'s local SEO services help businesses rank in the local 3-pack, Google Maps and city-specific organic search results.',
        'features'=>['Google Business Profile optimisation','Local citation building & NAP consistency','On-page local SEO','Review generation strategy','Local link building','Monthly ranking reports'],
        'stats'=>[['num'=>'Pg 1','label'=>'Target in 90 Days'],['num'=>'3x','label'=>'More Local Leads'],['num'=>'Maps','label'=>'3-Pack Ranking'],['num'=>'Monthly','label'=>'Reporting']],
        'faq'=>[['q'=>'How long does local SEO take?','a'=>'Most businesses see improved rankings in 60–90 days. GBP improvements in 2–4 weeks.'],['q'=>'How much do local SEO services cost?','a'=>'From ₹5,000/month for single city. Multi-city from ₹10,000/month.'],['q'=>'Do you manage Google Business Profile?','a'=>'Yes — posts, photos, Q&A and review responses.']],
    ],
    'technical-seo' => [
        'slug'=>'technical-seo','title'=>'Technical SEO Services','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-gear',
        'meta_title'=>'Technical SEO Services India | Core Web Vitals & Site Audit — Chulbul Design',
        'meta_desc'=>'Expert technical SEO in India. Site speed, Core Web Vitals, crawl errors, schema markup and full technical audit. Free consultation.',
        'canonical'=>'https://www.chulbuldesign.com/technical-seo',
        'h1'=>'Technical SEO Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Fix the technical foundation of your website so Google can crawl, index and rank your pages.',
        'intro'=>'Content and backlinks alone won\'t rank your website if Google can\'t crawl it properly. Technical SEO is the foundation — site speed, mobile-friendliness, structured data, canonical tags and Core Web Vitals all impact where you rank.',
        'features'=>['Full technical SEO audit','Core Web Vitals optimisation','Schema markup & structured data','XML sitemap & robots.txt','Canonical tag & duplicate content fix','Crawl error & 404 resolution'],
        'stats'=>[['num'=>'95+','label'=>'PageSpeed Target'],['num'=>'CWV','label'=>'Passed'],['num'=>'Schema','label'=>'Markup Added'],['num'=>'Full','label'=>'GSC Audit']],
        'faq'=>[['q'=>'What is a technical SEO audit?','a'=>'Examines your site for slow load time, broken links, duplicate content, missing schema and crawl errors.'],['q'=>'How much does technical SEO cost?','a'=>'Audit from ₹8,000. Ongoing management from ₹6,000/month.'],['q'=>'Do you fix Core Web Vitals?','a'=>'Yes — most sites achieve Good scores within 2–4 weeks.']],
    ],
    'google-ads-ppc' => [
        'slug'=>'google-ads-ppc','title'=>'Google Ads / PPC Management','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-google',
        'meta_title'=>'Google Ads Management India | PPC Agency Gurgaon — Chulbul Design',
        'meta_desc'=>'Expert Google Ads management in India. Search, display, shopping and YouTube campaigns focused on leads and ROI. Free account audit.',
        'canonical'=>'https://www.chulbuldesign.com/google-ads-ppc',
        'h1'=>'Google Ads & PPC Management <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Stop wasting ad budget — Google Ads campaigns that bring real leads at lower cost.',
        'intro'=>'Google Ads can bring instant traffic and qualified leads — or burn your budget on irrelevant clicks. Chulbul Design manages Google Ads campaigns for businesses across India — search, display, shopping and YouTube — with a focus on reducing cost per lead.',
        'features'=>['Google Search, Display & Shopping Ads','Keyword research & negative keywords','Landing page alignment','A/B testing of ad creatives','Call tracking & lead form setup','Weekly performance reports'],
        'stats'=>[['num'=>'5x','label'=>'Avg ROI Improvement'],['num'=>'60%','label'=>'CPL Reduction'],['num'=>'Weekly','label'=>'Reports'],['num'=>'No','label'=>'Long-Term Lock-in']],
        'faq'=>[['q'=>'Minimum budget for Google Ads in India?','a'=>'Minimum ₹15,000/month ad spend. Management fee from ₹5,000/month.'],['q'=>'How long before results?','a'=>'Leads start within first week. Optimised over 30–60 days.'],['q'=>'Can you audit our existing account?','a'=>'Yes — free Google Ads audit available.']],
    ],
    'social-media-marketing' => [
        'slug'=>'social-media-marketing','title'=>'Social Media Marketing','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-instagram',
        'meta_title'=>'Social Media Marketing Agency India | Meta Ads & Instagram — Chulbul Design',
        'meta_desc'=>'Social media marketing agency in India. Instagram, Facebook, LinkedIn management and Meta Ads for brand awareness and lead generation.',
        'canonical'=>'https://www.chulbuldesign.com/social-media-marketing',
        'h1'=>'Social Media Marketing <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Build your brand on Instagram, Facebook and LinkedIn — with content that converts.',
        'intro'=>'India has over 450 million social media users. Chulbul Design manages social media for businesses across India — content calendars, Meta Ads, follower growth and real leads from Instagram, Facebook and LinkedIn.',
        'features'=>['Social media content calendar & posting','Instagram Reels & creative design','Meta Ads (Facebook & Instagram)','LinkedIn company page management','Community management','Monthly analytics & growth report'],
        'stats'=>[['num'=>'450M+','label'=>'Indian Social Users'],['num'=>'Daily','label'=>'Content Posting'],['num'=>'Meta','label'=>'Ads Certified'],['num'=>'Monthly','label'=>'Reports']],
        'faq'=>[['q'=>'How much does social media management cost?','a'=>'From ₹8,000/month for 2 platforms. With Meta Ads from ₹15,000/month.'],['q'=>'Do you create content and graphics?','a'=>'Yes — all graphics, captions and hashtag strategies. You approve before posting.'],['q'=>'Can you run Meta Ads for local business?','a'=>'Yes — highly effective for restaurants, salons, clinics and retail.']],
    ],
    'content-marketing' => [
        'slug'=>'content-marketing','title'=>'Content Marketing','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-file-earmark-text',
        'meta_title'=>'Content Marketing Services India | SEO Blog Writing & Strategy — Chulbul Design',
        'meta_desc'=>'Content marketing for businesses in India. SEO blog writing, pillar content strategy, case studies and website copywriting to drive organic traffic.',
        'canonical'=>'https://www.chulbuldesign.com/content-marketing',
        'h1'=>'Content Marketing Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Rank on Google with high-quality SEO content — blogs, guides and case studies.',
        'intro'=>'Content is the fuel for SEO. Chulbul Design creates SEO-focused content strategies for Indian businesses — keyword research, blog calendars, pillar pages, service page copy and case studies that build topical authority and drive organic traffic.',
        'features'=>['Keyword research & content planning','SEO blog writing (1000–2500 words)','Service page & landing page copywriting','Case studies & whitepapers','Internal linking strategy','Content performance tracking'],
        'stats'=>[['num'=>'4x','label'=>'More Organic Traffic'],['num'=>'Monthly','label'=>'Blog Publishing'],['num'=>'E-E-A-T','label'=>'Optimised'],['num'=>'KW','label'=>'Research Included']],
        'faq'=>[['q'=>'How many blogs per month?','a'=>'4–8 blogs per month for consistent SEO growth. Quality matters more than quantity.'],['q'=>'How much does content marketing cost?','a'=>'From ₹8,000/month for 4 SEO blogs. Full strategy from ₹20,000/month.'],['q'=>'Do you write in Hindi?','a'=>'Yes — bilingual content in Hindi and English.']],
    ],
    'google-maps-ranking' => [
        'slug'=>'google-maps-ranking','title'=>'Google Maps Ranking','category'=>'SEO & Digital Marketing','cat_color'=>'#ea580c','cat_bg'=>'rgba(234,88,12,.1)','icon'=>'bi-pin-map',
        'meta_title'=>'Google Maps Ranking Services India | Local 3-Pack Optimisation — Chulbul Design',
        'meta_desc'=>'Get your business in Google Maps 3-pack. Google Business Profile optimisation, citations and local signals for better Google Maps ranking in India.',
        'canonical'=>'https://www.chulbuldesign.com/google-maps-ranking',
        'h1'=>'Google Maps Ranking Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Get into the Google Maps 3-Pack — drive walk-in and call traffic from local searches.',
        'intro'=>'The Google Maps 3-pack appears at the top of local search results and drives the most direct calls and walk-ins. Chulbul Design\'s Google Maps ranking service focuses on all the signals Google uses — GBP completeness, reviews, citations and proximity optimisation.',
        'features'=>['Google Business Profile complete setup','Category & attribute optimisation','Photo & post strategy','Review generation & management','Local citation building (50+ directories)','Competitor analysis & gap strategy'],
        'stats'=>[['num'=>'3-Pack','label'=>'Target Position'],['num'=>'5★','label'=>'Review Strategy'],['num'=>'50+','label'=>'Citations Built'],['num'=>'60d','label'=>'Avg Result Time']],
        'faq'=>[['q'=>'How long to rank on Google Maps?','a'=>'Improvement in 30–60 days of GBP optimisation and citation building.'],['q'=>'Do I need a physical address?','a'=>'Yes — Google Maps ranking requires a verified physical address.'],['q'=>'How much does Google Maps ranking cost?','a'=>'From ₹4,000/month including GBP management and citation building.']],
    ],

    // UI/UX & BRANDING
    'logo-design' => [
        'slug'=>'logo-design','title'=>'Logo Design Services','category'=>'UI/UX & Branding','cat_color'=>'#ec4899','cat_bg'=>'rgba(236,72,153,.1)','icon'=>'bi-star',
        'meta_title'=>'Logo Design Services India | Professional Logo Designer — Chulbul Design',
        'meta_desc'=>'Professional logo design in India. Custom logos for startups, SMEs and enterprises — vector formats, brand guidelines and unlimited revisions.',
        'canonical'=>'https://www.chulbuldesign.com/logo-design',
        'h1'=>'Logo Design Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'A logo that represents your brand for the next 10 years — custom, memorable and versatile.',
        'intro'=>'Your logo is the most seen element of your brand. Chulbul Design creates custom logos hand-crafted by our designers — not generated by AI or cloned from templates — to reflect your brand values, target audience and industry.',
        'features'=>['3 initial concepts from scratch','Unlimited revisions','All formats: SVG, PNG, PDF, EPS','Light & dark version','Social media profile sizes','Brand color palette & typography guide'],
        'stats'=>[['num'=>'3','label'=>'Initial Concepts'],['num'=>'∞','label'=>'Revisions'],['num'=>'All','label'=>'File Formats'],['num'=>'5d','label'=>'First Delivery']],
        'faq'=>[['q'=>'How much does logo design cost in India?','a'=>'Logo design from ₹5,000 including 3 concepts and all formats. Brand identity from ₹15,000.'],['q'=>'How long does logo design take?','a'=>'First concepts in 5 working days. Final logo in 10–12 working days.'],['q'=>'Do I get the source files?','a'=>'Yes — AI, EPS, SVG, PNG and PDF. You own 100% of the design.']],
    ],
    'graphic-design' => [
        'slug'=>'graphic-design','title'=>'Graphic Design Services','category'=>'UI/UX & Branding','cat_color'=>'#ec4899','cat_bg'=>'rgba(236,72,153,.1)','icon'=>'bi-palette',
        'meta_title'=>'Graphic Design Services India | Brochure, Poster & Marketing Design — Chulbul Design',
        'meta_desc'=>'Professional graphic design in India. Brochures, flyers, banners, social media graphics, packaging design and marketing collateral.',
        'canonical'=>'https://www.chulbuldesign.com/graphic-design',
        'h1'=>'Graphic Design Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Print and digital design that makes your brand look professional everywhere.',
        'intro'=>'From brochures and visiting cards to social media graphics and packaging — Chulbul Design provides end-to-end graphic design services for businesses across India. Our designers work with your brand guidelines to create consistent, professional collateral.',
        'features'=>['Brochure & catalogue design','Flyer & poster design','Social media graphic templates','Visiting card & stationery design','Banner & hoarding design','Packaging & label design'],
        'stats'=>[['num'=>'Print','label'=>'& Digital Ready'],['num'=>'CMYK','label'=>'Print Colour'],['num'=>'Fast','label'=>'Turnaround'],['num'=>'Brand','label'=>'Consistent']],
        'faq'=>[['q'=>'How much does graphic design cost in India?','a'=>'Visiting card from ₹1,500. Brochure from ₹4,000. Social media template set from ₹6,000.'],['q'=>'Do you provide print-ready files?','a'=>'Yes — CMYK with bleed and trim marks, ready for any print vendor.'],['q'=>'Can you design in our brand colors?','a'=>'Yes — we strictly follow your brand guidelines.']],
    ],
    'branding-identity' => [
        'slug'=>'branding-identity','title'=>'Branding & Identity Design','category'=>'UI/UX & Branding','cat_color'=>'#ec4899','cat_bg'=>'rgba(236,72,153,.1)','icon'=>'bi-gem',
        'meta_title'=>'Branding & Identity Design India | Brand Strategy & Visual Identity — Chulbul Design',
        'meta_desc'=>'Complete branding & identity design in India. Logo, brand guidelines, color palette, typography and visual identity system for startups and enterprises.',
        'canonical'=>'https://www.chulbuldesign.com/branding-identity',
        'h1'=>'Branding & Identity Design <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Build a brand that customers trust, remember and choose over competitors.',
        'intro'=>'A brand is not just a logo — it is the complete visual and emotional identity of your business. Chulbul Design creates comprehensive brand identity systems for startups and growing businesses — from logo design to color palettes, typography, brand voice and guidelines.',
        'features'=>['Brand strategy & positioning','Logo design (primary + alternate)','Color palette & typography system','Brand guidelines document (PDF)','Business card & stationery design','Social media brand kit'],
        'stats'=>[['num'=>'Full','label'=>'Brand System'],['num'=>'Guide','label'=>'Document Included'],['num'=>'All','label'=>'Applications Covered'],['num'=>'3-4wk','label'=>'Delivery']],
        'faq'=>[['q'=>'How much does brand identity cost?','a'=>'Complete brand identity from ₹20,000. Enterprise branding from ₹60,000.'],['q'=>'What is a brand guidelines document?','a'=>'Specifies exactly how logo, colors, fonts should be used — ensuring consistency across all channels.'],['q'=>'Do you help with brand naming?','a'=>'Yes — including domain and trademark availability research.']],
    ],
    'conversion-rate-optimization' => [
        'slug'=>'conversion-rate-optimization','title'=>'Conversion Rate Optimization','category'=>'UI/UX & Branding','cat_color'=>'#ec4899','cat_bg'=>'rgba(236,72,153,.1)','icon'=>'bi-graph-up',
        'meta_title'=>'Conversion Rate Optimization Services India | CRO Agency — Chulbul Design',
        'meta_desc'=>'CRO services in India. Website audit, A/B tests and UX improvements to increase the percentage of visitors who convert to leads or customers.',
        'canonical'=>'https://www.chulbuldesign.com/conversion-rate-optimization',
        'h1'=>'Conversion Rate Optimization <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Get more leads and sales from the same traffic — without spending more on ads.',
        'intro'=>'Most websites convert only 1–3% of visitors. CRO identifies why the other 97% leave without acting — and fixes it. Chulbul Design conducts CRO audits using heatmaps, session recordings and analytics to find friction points, then implements changes that measurably improve your conversion rate.',
        'features'=>['Heatmap & session recording analysis','Conversion funnel audit','A/B testing setup & management','CTA & form optimisation','Landing page UX improvements','Monthly CRO performance reports'],
        'stats'=>[['num'=>'2-4x','label'=>'Conversion Increase'],['num'=>'A/B','label'=>'Testing Included'],['num'=>'Heatmap','label'=>'Analysis'],['num'=>'Data','label'=>'Driven']],
        'faq'=>[['q'=>'What is CRO and why do I need it?','a'=>'CRO improves the % of visitors who take action. Doubling conversion rate = doubling traffic at zero extra ad cost.'],['q'=>'How much does CRO cost?','a'=>'CRO audit from ₹12,000. Ongoing management from ₹10,000/month.'],['q'=>'How long before results?','a'=>'Initial improvements in 2–4 weeks. A/B test results in 4–8 weeks.']],
    ],
    'dashboard-ui-design' => [
        'slug'=>'dashboard-ui-design','title'=>'Dashboard UI Design','category'=>'UI/UX & Branding','cat_color'=>'#ec4899','cat_bg'=>'rgba(236,72,153,.1)','icon'=>'bi-speedometer',
        'meta_title'=>'Dashboard UI Design India | Admin Panel & SaaS UI Design — Chulbul Design',
        'meta_desc'=>'Professional dashboard UI design in India. Admin panels, analytics dashboards, SaaS interfaces and data visualisation — designed for usability.',
        'canonical'=>'https://www.chulbuldesign.com/dashboard-ui-design',
        'h1'=>'Dashboard UI Design <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Complex data made simple — admin panels and analytics dashboards your team will actually use.',
        'intro'=>'A well-designed dashboard reduces cognitive load, speeds up decision-making and improves team productivity. Chulbul Design specialises in admin panels, analytics dashboards and SaaS interfaces that present complex data clearly with intuitive navigation and clean charts.',
        'features'=>['Dashboard wireframing & prototyping','Data visualisation & chart design','Admin panel UI design','Role-based view design','Figma design with developer handoff','Responsive dashboard design'],
        'stats'=>[['num'=>'Figma','label'=>'Based Design'],['num'=>'Dev','label'=>'Handoff Ready'],['num'=>'Role','label'=>'Based Views'],['num'=>'Data','label'=>'Viz Included']],
        'faq'=>[['q'=>'How much does dashboard UI design cost?','a'=>'Basic admin panel from ₹25,000. Complex SaaS dashboards from ₹60,000.'],['q'=>'Do you provide Figma files?','a'=>'Yes — organised Figma files with components and developer annotations.'],['q'=>'Can you design and develop the dashboard?','a'=>'Yes — full-stack design and development using React JS.']],
    ],

    // SUPPORT & SPEED
    'website-maintenance' => [
        'slug'=>'website-maintenance','title'=>'Website Maintenance Services','category'=>'Website Support & Optimization','cat_color'=>'#64748b','cat_bg'=>'rgba(100,116,139,.1)','icon'=>'bi-wrench',
        'meta_title'=>'Website Maintenance Services India | Monthly Website Care — Chulbul Design',
        'meta_desc'=>'Professional website maintenance in India. Monthly updates, security patches, backups, uptime monitoring and content changes. From ₹1,500/month.',
        'canonical'=>'https://www.chulbuldesign.com/website-maintenance',
        'h1'=>'Website Maintenance Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Keep your website secure, updated and performing — without worrying about it yourself.',
        'intro'=>'An unmaintained website is a liability — outdated plugins get hacked, broken links hurt SEO, and slow load times lose customers. Chulbul Design\'s maintenance packages cover monthly updates, security scans, backups, uptime monitoring and content changes.',
        'features'=>['Monthly CMS & plugin updates','Weekly automated backups','Security scanning & malware removal','Uptime monitoring (99.9% SLA)','Monthly content updates','Monthly performance report'],
        'stats'=>[['num'=>'99.9%','label'=>'Uptime Monitoring'],['num'=>'Weekly','label'=>'Backups'],['num'=>'Monthly','label'=>'Updates'],['num'=>'24h','label'=>'Issue Response']],
        'faq'=>[['q'=>'How much does website maintenance cost?','a'=>'From ₹1,500/month for basic WordPress care. With content updates from ₹4,000/month.'],['q'=>'What if my site gets hacked?','a'=>'Malware removal as priority service — typically resolved within 24 hours.'],['q'=>'Can I request content changes?','a'=>'Yes — up to 30 minutes per month. Additional time at ₹500/hour.']],
    ],
    'website-speed-optimization' => [
        'slug'=>'website-speed-optimization','title'=>'Website Speed Optimization','category'=>'Website Support & Optimization','cat_color'=>'#64748b','cat_bg'=>'rgba(100,116,139,.1)','icon'=>'bi-lightning-charge',
        'meta_title'=>'Website Speed Optimization India | PageSpeed 90+ Guaranteed — Chulbul Design',
        'meta_desc'=>'Expert website speed optimization in India. Improve PageSpeed scores, reduce load time and fix Core Web Vitals for WordPress, WooCommerce and custom sites.',
        'canonical'=>'https://www.chulbuldesign.com/website-speed-optimization',
        'h1'=>'Website Speed Optimization <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Slow website? We fix it — guaranteed PageSpeed 90+ or your money back.',
        'intro'=>'A 1-second delay reduces conversions by 7%. If your website takes more than 3 seconds to load, you are losing customers to faster competitors. Chulbul Design takes slow websites and brings them to a PageSpeed score of 90+.',
        'features'=>['Full PageSpeed audit & analysis','Image compression & WebP conversion','CSS/JS minification & deferral','Caching setup (Redis/LiteSpeed)','Database optimisation','CDN integration'],
        'stats'=>[['num'=>'90+','label'=>'PageSpeed Guaranteed'],['num'=>'<2s','label'=>'Load Time Target'],['num'=>'1wk','label'=>'Delivery Time'],['num'=>'CWV','label'=>'Pass Guaranteed']],
        'faq'=>[['q'=>'How much does speed optimization cost?','a'=>'WordPress from ₹8,000. WooCommerce from ₹15,000.'],['q'=>'Do you guarantee PageSpeed improvement?','a'=>'Yes — 90+ on mobile and desktop, or we continue at no extra charge.'],['q'=>'Will it affect my website design?','a'=>'No — speed optimization is entirely under the hood.']],
    ],
    'core-web-vitals-optimization' => [
        'slug'=>'core-web-vitals-optimization','title'=>'Core Web Vitals Optimization','category'=>'Website Support & Optimization','cat_color'=>'#64748b','cat_bg'=>'rgba(100,116,139,.1)','icon'=>'bi-bar-chart',
        'meta_title'=>'Core Web Vitals Optimization India | LCP, CLS & INP Fix — Chulbul Design',
        'meta_desc'=>'Expert Core Web Vitals optimization in India. Fix LCP, CLS and INP issues to pass Google page experience signals and improve search rankings.',
        'canonical'=>'https://www.chulbuldesign.com/core-web-vitals-optimization',
        'h1'=>'Core Web Vitals Optimization <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Pass Google\'s Core Web Vitals — LCP, CLS and INP — and improve your search rankings.',
        'intro'=>'Core Web Vitals are Google\'s official page experience signals. Failing these metrics hurts your search rankings. Chulbul Design diagnoses exactly which elements cause failures and implements targeted fixes to pass all three metrics.',
        'features'=>['LCP optimisation','CLS fix (layout shift)','INP improvement (JS optimisation)','Field data analysis (CrUX)','Google Search Console integration','Before/after CWV report'],
        'stats'=>[['num'=>'LCP','label'=>'<2.5s Target'],['num'=>'CLS','label'=>'<0.1 Target'],['num'=>'INP','label'=>'<200ms Target'],['num'=>'All','label'=>'3 Metrics Fixed']],
        'faq'=>[['q'=>'What are Core Web Vitals?','a'=>'Three Google metrics: LCP (content load speed), CLS (layout shift) and INP (interaction response time).'],['q'=>'How much does CWV optimization cost?','a'=>'WordPress from ₹10,000. Ecommerce from ₹20,000.'],['q'=>'Will fixing CWV improve rankings?','a'=>'Yes — Google uses CWV as a ranking signal.']],
    ],
    'website-migration' => [
        'slug'=>'website-migration','title'=>'Website Migration Services','category'=>'Website Support & Optimization','cat_color'=>'#64748b','cat_bg'=>'rgba(100,116,139,.1)','icon'=>'bi-arrow-left-right',
        'meta_title'=>'Website Migration Services India | Server, Platform & CMS Migration — Chulbul Design',
        'meta_desc'=>'Expert website migration in India. Server migration, CMS migration, HTTP to HTTPS and domain migration with zero downtime.',
        'canonical'=>'https://www.chulbuldesign.com/website-migration',
        'h1'=>'Website Migration Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Migrate your website to a new server, platform or domain — zero downtime, zero SEO loss.',
        'intro'=>'Website migration done wrong can destroy your Google rankings overnight. Chulbul Design handles all types of migrations — server migrations, CMS platform switches, HTTP to HTTPS, domain changes and ecommerce platform migrations — with careful SEO preservation.',
        'features'=>['Server & hosting migration','CMS migration (Joomla/Drupal to WordPress)','HTTP to HTTPS migration','Domain migration with 301 redirects','Ecommerce platform migration','Post-migration SEO monitoring'],
        'stats'=>[['num'=>'0','label'=>'Downtime Target'],['num'=>'0%','label'=>'Data Loss'],['num'=>'301','label'=>'Redirects Setup'],['num'=>'SEO','label'=>'Preserved']],
        'faq'=>[['q'=>'Will migration affect my Google rankings?','a'=>'When done correctly with proper 301 redirects, minimal impact. We monitor for 30 days post-migration.'],['q'=>'How much does migration cost?','a'=>'Server migration from ₹5,000. CMS migration from ₹15,000. Ecommerce from ₹25,000.'],['q'=>'How long does migration take?','a'=>'Server migration 1–2 days. CMS migration 1–2 weeks.']],
    ],
    'website-security' => [
        'slug'=>'website-security','title'=>'Website Security Services','category'=>'Website Support & Optimization','cat_color'=>'#64748b','cat_bg'=>'rgba(100,116,139,.1)','icon'=>'bi-shield-check',
        'meta_title'=>'Website Security Services India | Malware Removal & SSL — Chulbul Design',
        'meta_desc'=>'Professional website security in India. Malware removal, SSL installation, firewall setup and security hardening for WordPress sites.',
        'canonical'=>'https://www.chulbuldesign.com/website-security',
        'h1'=>'Website Security Services <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Protect your website from hackers, malware and data breaches — starting today.',
        'intro'=>'Over 30,000 websites are hacked every day — mostly small business WordPress sites with outdated plugins. Chulbul Design provides complete website security — malware removal, security hardening, firewall setup and monitoring that keeps your site protected 24/7.',
        'features'=>['Malware scan, detection & removal','SSL certificate installation','WordPress security hardening','Web application firewall (WAF)','Login protection & 2FA','Ongoing security monitoring'],
        'stats'=>[['num'=>'24h','label'=>'Malware Removal'],['num'=>'SSL','label'=>'Installation'],['num'=>'WAF','label'=>'Firewall Setup'],['num'=>'24/7','label'=>'Monitoring']],
        'faq'=>[['q'=>'My website has been hacked — what do I do?','a'=>'Contact us immediately. Emergency malware removal within 24 hours.'],['q'=>'How much does security cost?','a'=>'One-time malware removal from ₹5,000. Ongoing monitoring from ₹2,500/month.'],['q'=>'Do you install SSL certificates?','a'=>'Yes — for all hosting environments including cPanel, Nginx and Apache.']],
    ],

    // AI & AUTOMATION
    'ai-chatbot-integration' => [
        'slug'=>'ai-chatbot-integration','title'=>'AI Chatbot Integration','category'=>'AI & Automation','cat_color'=>'#6366f1','cat_bg'=>'rgba(99,102,241,.1)','icon'=>'bi-robot',
        'meta_title'=>'AI Chatbot Integration India | Custom Chatbot for Website — Chulbul Design',
        'meta_desc'=>'AI chatbot integration for Indian businesses. Custom chatbots for lead generation, customer support and WhatsApp automation using GPT and Dialogflow.',
        'canonical'=>'https://www.chulbuldesign.com/ai-chatbot-integration',
        'h1'=>'AI Chatbot Integration <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Automate customer queries, capture leads and provide 24/7 support — with AI chatbots.',
        'intro'=>'An AI chatbot answers questions, qualifies leads and books appointments at 3am — without human involvement. Chulbul Design integrates AI chatbots powered by GPT and Dialogflow into websites, WhatsApp and Facebook Messenger — trained on your business data.',
        'features'=>['GPT-powered website chatbot','WhatsApp Business chatbot','Lead qualification & form filling','FAQ automation & knowledge base','Appointment booking integration','CRM lead handoff'],
        'stats'=>[['num'=>'24/7','label'=>'Automated Support'],['num'=>'70%','label'=>'Query Automation'],['num'=>'GPT','label'=>'Powered'],['num'=>'WA','label'=>'Business Ready']],
        'faq'=>[['q'=>'How much does AI chatbot cost?','a'=>'Basic website chatbot from ₹15,000. WhatsApp chatbot from ₹25,000. Custom GPT-trained from ₹50,000.'],['q'=>'Can it be trained on our products?','a'=>'Yes — trained on your catalogue, FAQs, pricing and policies.'],['q'=>'Does it work on mobile?','a'=>'Yes — website chatbots are fully responsive.']],
    ],
    'whatsapp-automation' => [
        'slug'=>'whatsapp-automation','title'=>'WhatsApp Business Automation','category'=>'AI & Automation','cat_color'=>'#6366f1','cat_bg'=>'rgba(99,102,241,.1)','icon'=>'bi-whatsapp',
        'meta_title'=>'WhatsApp Business Automation India | WhatsApp API Integration — Chulbul Design',
        'meta_desc'=>'WhatsApp Business API automation for Indian businesses. Automated lead follow-ups, order confirmations, appointment reminders and customer support on WhatsApp.',
        'canonical'=>'https://www.chulbuldesign.com/whatsapp-automation',
        'h1'=>'WhatsApp Business Automation <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Automate lead follow-ups, order updates and customer support on WhatsApp — India\'s most-used app.',
        'intro'=>'WhatsApp has over 500 million users in India and a 98% message open rate. Chulbul Design implements WhatsApp Business API automation for lead follow-up sequences, order confirmations, appointment reminders and customer support.',
        'features'=>['WhatsApp Business API setup','Automated lead follow-up sequences','Order confirmation & shipping updates','Appointment reminder automation','Payment link automation','Chatbot for customer support'],
        'stats'=>[['num'=>'98%','label'=>'Message Open Rate'],['num'=>'500M','label'=>'Indian WA Users'],['num'=>'Auto','label'=>'Follow-ups'],['num'=>'24/7','label'=>'Automated']],
        'faq'=>[['q'=>'What is WhatsApp Business API?','a'=>'Official API for automated messages and chatbots — unlike the manual WhatsApp Business app.'],['q'=>'How much does WhatsApp automation cost?','a'=>'Setup from ₹20,000. Complex workflows from ₹40,000.'],['q'=>'Can it integrate with my CRM?','a'=>'Yes — Zoho, HubSpot, Salesforce and custom CRMs.']],
    ],
    'workflow-automation' => [
        'slug'=>'workflow-automation','title'=>'Business Workflow Automation','category'=>'AI & Automation','cat_color'=>'#6366f1','cat_bg'=>'rgba(99,102,241,.1)','icon'=>'bi-arrow-repeat',
        'meta_title'=>'Business Workflow Automation India | Zapier, Make & Custom Automation — Chulbul Design',
        'meta_desc'=>'Business workflow automation in India. Automate repetitive tasks using Zapier, Make, custom scripts and API integrations to save your team hours daily.',
        'canonical'=>'https://www.chulbuldesign.com/workflow-automation',
        'h1'=>'Business Workflow Automation <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Automate repetitive business tasks and save your team 10+ hours every week.',
        'intro'=>'Every business has repetitive tasks that consume hours — manually copying data, sending follow-up emails, updating spreadsheets, generating reports. Chulbul Design automates these using Zapier, Make, custom APIs and scripts — giving your team back hours every day.',
        'features'=>['Zapier & Make (Integromat) automation','CRM to email/WhatsApp automation','Lead form to spreadsheet automation','Invoice & report generation','Cross-platform data sync','Custom API workflow scripts'],
        'stats'=>[['num'=>'10+hrs','label'=>'Saved Per Week'],['num'=>'0','label'=>'Manual Errors'],['num'=>'Custom','label'=>'Workflows'],['num'=>'Fast','label'=>'ROI']],
        'faq'=>[['q'=>'What workflows can you automate?','a'=>'Lead routing, follow-up emails, invoice generation, report creation, data sync — virtually any repetitive digital task.'],['q'=>'How much does workflow automation cost?','a'=>'Simple Zapier automation from ₹8,000. Complex custom API automation from ₹25,000.'],['q'=>'Do I need technical knowledge to manage it?','a'=>'No — we build a simple dashboard so your team can monitor and modify workflows without coding.']],
    ],
    'ai-business-automation' => [
        'slug'=>'ai-business-automation','title'=>'AI Business Automation','category'=>'AI & Automation','cat_color'=>'#6366f1','cat_bg'=>'rgba(99,102,241,.1)','icon'=>'bi-cpu',
        'meta_title'=>'AI Business Automation India | Automate with AI Tools — Chulbul Design',
        'meta_desc'=>'AI business automation services in India. Integrate AI into workflows for content generation, data analysis, customer communication and decision support.',
        'canonical'=>'https://www.chulbuldesign.com/ai-business-automation',
        'h1'=>'AI Business Automation <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Use AI to automate content, analysis and communication — give your business a competitive edge.',
        'intro'=>'Chulbul Design helps Indian SMEs and startups integrate practical AI tools — automated content generation, intelligent lead scoring, AI-powered customer support, data analysis and decision-support systems that run 24/7.',
        'features'=>['AI content generation & scheduling','GPT-based customer support automation','Lead scoring & qualification AI','Automated data analysis & reporting','Document processing & extraction','AI integration with existing systems'],
        'stats'=>[['num'=>'GPT-4','label'=>'Powered'],['num'=>'24/7','label'=>'Automated'],['num'=>'Custom','label'=>'AI Workflows'],['num'=>'ROI','label'=>'Measurable']],
        'faq'=>[['q'=>'What AI tools do you integrate?','a'=>'OpenAI GPT-4, Claude, Google Gemini, Hugging Face and Indian tools like Sarvam AI for Hindi support.'],['q'=>'How much does AI automation cost?','a'=>'AI projects from ₹30,000. Comprehensive AI integration from ₹1,00,000.'],['q'=>'Is AI suitable for small business?','a'=>'Yes — even 5-person businesses benefit from AI for emails, content creation and invoice extraction.']],
    ],
    'ai-content-solutions' => [
        'slug'=>'ai-content-solutions','title'=>'AI Content Solutions','category'=>'AI & Automation','cat_color'=>'#6366f1','cat_bg'=>'rgba(99,102,241,.1)','icon'=>'bi-lightbulb',
        'meta_title'=>'AI Content Solutions India | AI-Assisted Content Creation — Chulbul Design',
        'meta_desc'=>'AI content solutions for businesses in India. AI-assisted blog writing, product descriptions, social media content and multilingual content at scale.',
        'canonical'=>'https://www.chulbuldesign.com/ai-content-solutions',
        'h1'=>'AI Content Solutions <span class="text-[#EE483D]">in India</span>',
        'tagline'=>'Produce 10x more content at a fraction of the cost — AI-assisted, human-reviewed.',
        'intro'=>'Content marketing requires volume. AI generates first drafts at speed, but without human review and SEO strategy the output is generic. Chulbul Design combines AI generation with expert human editing and SEO optimisation to produce quality content at scale.',
        'features'=>['AI-assisted SEO blog writing','Product description generation at scale','Social media caption generation','Email sequence writing','Multilingual content (Hindi + English)','Content calendar & strategy'],
        'stats'=>[['num'=>'10x','label'=>'Content Volume'],['num'=>'Human','label'=>'Reviewed'],['num'=>'SEO','label'=>'Optimised'],['num'=>'Hindi','label'=>'& English']],
        'faq'=>[['q'=>'Is AI content good for SEO?','a'=>'Yes — when properly edited and SEO-optimised by humans. We never publish raw AI output.'],['q'=>'How much does AI content cost?','a'=>'AI-assisted blog writing from ₹2,000 per article. Bulk packages available.'],['q'=>'Can you generate content in Hindi?','a'=>'Yes — Hindi, Hinglish and English with human review.']],
    ],
];
